### ISSUE TITLE
SQL 'AND' criteria for the same fields?

### ISSUE THREAD

**Issue by serjrd** [balderdashy/waterline#1000]
Sorry, I was unable to find this in the documentation.

How do you use the 'and' criteria for the same field names?
My intuitive guess didn't work out :)

E.g.:
This doesn't work:
```js
Lang.find({where:{'and':[{lang_id: 'en', type: 'learning'}, {lang_id:'ru', type:'native'}]}}).exec(console.log)
```
While this one works just fine:
```js
Lang.find({where:{'or':[{lang_id: 'en', type: 'learning'}, {lang_id:'ru', type:'native'}]}}).exec(console.log)
```

**Comment by devinivy** [comment]
Could you share how you resolved this?

**Comment by serjrd** [comment]
Sorry, it was kinda late here, so my brain failed me :)

After posting this issue I quickly realized that in my particular case the query is not that straightforward.

Not sure if it's going to be of any help to others, but I ended up composing an SQL line for the `.query()` method:

```
	sql = """
		SELECT DISTINCT u.id, u.name, u.status, u.current_activity, u.avatar, u.country_code
		FROM user u
		LEFT JOIN lang ll ON u.id = ll.user_id AND ll.type='learning'
		LEFT JOIN lang nl ON u.id = nl.user_id AND nl.type='native'
		...
	"""
```

**Comment by dmarcelino** [comment]
BTW, waterline does not support `AND` yet, there's an open issue for that: #648.

**Comment by serjrd** [comment]
@dmarcelino Yeah, even though it wasn't the right feature for my case, I was really surprised that there's no `and` method. The question raised in #648 looks totally legit.

And in my understanding it behaves exactly like the `or` method, so it should be a really easy feature to add. Or is there something I'm missing about it?

**Comment by dmarcelino** [comment]
> so it should be a really easy feature to add

Are you volunteering to fix it? :smiley: 

> Or is there something I'm missing about it?

From my understanding this will need to be implemented on all/most adapters.

**Comment by serjrd** [comment]
> Are you volunteering to fix it? :smiley:

Well, I could try. Although I don't have a clear understanding of the waterline inner structure.
I implied that It was an easy fix for somebody who's familiar with the code (probably the one who implemented the `or` functionality) :)

> From my understanding this will need to be implemented on all/most adapters.

I think if the maintainers agree to give it a go, it's totally ok to implement it step by step.
It'd probably be better to let the adapter maintainer to implement this function.
