### ISSUE TITLE
Model.update should all entity values be passed or only the desired attributes to update?

### ISSUE THREAD

**Issue by kvindasAB** [balderdashy/waterline#1003]
I have a model which contains several attributes, lets say 10 attributes.

One of the attributes is a count, likeCount for example.

At some point I want to increase the likeCount, but seems that to do it, I should update the whole entity with all the values, not just the likeCount.

The reason I comment this is that when I try to update only the likeCount, I find issues on other validation properties. For example, I have another property which is a number, and then the validation for that one fails saying -"required" validation rule failed for input: NaN-.

This makes me feel like the update operation for updating several collection/table rows is unusable, as I will have to specify all values for each entity.

I ignore if the update is supposed to work this way or there is an issue with the validation module.

Thanks.

**Comment by kvindasAB** [comment]
Hello @devinivy, Im just specifying in the update the attributes I want to update.
For example.

Entity.update(
          {id: myEntityId},
          {likeCount: myLikeCount}
        )

So as you see the where clause specified the entity id, and the update object specifies only the attribute.
Even on that case I get issues on other number properties failing because they are NaN.

To solve this, Im now passing the whole object, not just the likeCount, but that seems counter productive when the final goal is to modify several records at once.

Let me know your thoughts.

**Comment by dmarcelino** [comment]
Hi @kvindasAB, the scenario you mention is more or less covered by [waterline/test/unit/query/query.update.js#L48-L53](https://github.com/balderdashy/waterline/blob/4653f8a18016d2bcde9a70c90dd63a7c69381935/test/unit/query/query.update.js#L48-L53):

Fixture:
```js
          attributes: {
            name: {
              type: 'string',
              defaultsTo: 'Foo Bar'
            },
            age: {
              type: 'integer',
              required: true
            },
            doSomething: function() {}
          }
```

Test:
```js
      it('should change the updatedAt timestamp', function(done) {
        query.update({}, { name: 'foo' }, function(err, status) {
          assert(status[0].updatedAt);
          done();
        });
      });
```

And there is no issue with this,

Still I went a step further and created balderdashy/waterline-adapter-tests#72:

Fixture:
```js
  attributes: {
    name: {
      type: 'string',
      required: true
    },
    age: {
      type: 'integer',
      required: true,
      min: 5,
      max: 20
    },
    description: 'string'
```

Test:
```js
      it('should update model attributes without supplying required fields', function(done) {
        Semantic.Thing.update(thingId, { description: 'An updated thing' }, function(err, things) {
          assert(!err);
          assert(Array.isArray(things));
          assert.strictEqual(things.length, 1);
          assert.equal(things[0].id, thingId);
          assert.equal(things[0].description, 'An updated thing');
          done();
        });
      });
```

Once again everything worked fine. This last test was ran agains all official adapters and all passed the test: https://travis-ci.org/balderdashy/waterline-adapter-tests/jobs/62747990#L1775.

I'm not sure what is happening in your scenario... maybe a `beforeUpdate` or `validate` lifecycle requires a missing field and is throwing the error?

If you provide your model definition and a code snippet where the issue happens we can probably assist you better. Or feel free to modify my test so it breaks and reproduces your issue!

**Comment by dmarcelino** [comment]
@kvindasAB, closing this as inactive, please re-open if you feel this hasn't been fully answered or if you have new information.
