### ISSUE TITLE
DELETE query without WHERE clause on join table

### ISSUE THREAD

**Issue by timestep** [balderdashy/waterline#1008]
I have a many to many relationship between two models where the join table between the two is mysteriously cleared of its data, destroying all relationships between the models.

Investigating the logs in my postgresql server, I've identified this query being run:

```
DELETE  FROM "developer_developments__development_developers" AS "developer_developments__development_developers"   RETURNING *
```

This occurs immediately after I've deleted the developer, and its developments in question and the join table clears itself of the developer data as such:

```
DELETE  FROM "developer_developments__development_developers" AS "developer_developments__development_developers"  WHERE "developer_developments__development_developers"."developer_developments" IN ($1)  RETURNING *
```

I'm not 100% sure of the reason behind this, but I am curious why the database was asked to run the delete query without any where conditions.

I can provide additional information if required.

**Comment by devinivy** [comment]
What version of waterline are you using?

**Comment by timestep** [comment]
"sails": "0.10.5",
"sails-postgresql": "0.10.9",

The package.json file for sails says it uses waterline version ~0.10.9

**Comment by devinivy** [comment]
In your project folder, do you mind sharing the result of,
`grep version node_modules/sails/node_modules/waterline/package.json`?

**Comment by timestep** [comment]
"version": "0.10.9",

**Comment by dmarcelino** [comment]
I believe this was fixed in January v0.10.17:
https://github.com/balderdashy/waterline/commit/4b65fd53a0124d6159941b50ed0fe81dfac09fc1

**Comment by timestep** [comment]
Oh wow. I think you might be right. Is there a way for me to update the waterline orm without updating my version of sails?

**Comment by devinivy** [comment]
`npm update sails` will re-install the version of sails for your project up to the latest version specified in your package.json.  That should update its waterline dependency as well.

**Comment by timestep** [comment]
Thanks guys. This seemed to have fixed the issue.
