### ISSUE TITLE
Sync call

### ISSUE THREAD

**Issue by ameilland** [balderdashy/waterline#1009]
Hi,

Is there a way to call synchronously the find method such as?

var found =  Model.find().exec();

I have something like this in my bootstrap.js (sails.js config).

global.sync = require("synchronize");
    _.each(sails.models,function(model){
        _.map(model,function(attrValue,attrKey){
            if(typeof attrValue=="function"){
                model[attrKey+"Sync"]=sync(attrValue);
            }
        });
    });

But when I call var found =  Model.findSync() the property values is always empty. I guess it's because .exec is not called. But if I call with .exec() it fires an error. exec must have a callback.

Is there a way to do it easily?

Do you support it by default?

Thanks,

**Comment by dmarcelino** [comment]
@ameilland, this is not supported and never will. Node.js is single threaded and doing something like that would make Node.js block while waiting for the DB (ages in CPU time). I suggest you use callbacks or promises. You can read more about this in http://stackoverflow.com/questions/9884418/how-can-i-make-this-call-to-request-in-nodejs-synchronous. If you really insist in making an async method sync'ed (not recommended) you can use https://github.com/abbr/deasync.

**Comment by ameilland** [comment]
Ok it makes sense. But sometimes people can use in a loop a query and wait for the results before going to the next action. And callback can complicate a lot the code. But deasync makes the job perfectly. Thanks,

**Comment by tjwebb** [comment]
> But sometimes people can use in a loop a query and wait for the results before going to the next action. And callback can complicate a lot the code.

@ameilland if you're using node, you should get use to programming asynchronously. node.js is asynchronous by design. This is what "event-driven, non-blocking I/O means". From nodejs.org:

> Node.js uses an event-driven, non-blocking I/O model that makes it lightweight and efficient, perfect for data-intensive real-time applications that run across distributed devices.
