### ISSUE TITLE
Associations not being saved

### ISSUE THREAD

**Issue by wayne-o** [balderdashy/waterline#1010]
Say I have the following models:

```
module.exports = {
        tableName: 'location',
	attributes: {
		name: {
			type: 'string'
		},
		eventInstance: {
			model: 'eventInstance',
			columnName: 'eventInstanceId'
		}
	}
};

module.exports = {
    tableName: 'eventInstance',
    attributes: {
        name: { type: 'string' },
        locations: {
            collection: 'location',
            via: 'eventInstance'
        }
    }
};
```

I would expect the following to work:
```
Location.create({
    name: l.name,
    eventInstance: model.eventInstance.id
}).exec(function(err, savedLocation) {
    if (err) {
        winston.error(err);
        rej(err);
    }
    model.eventInstance.locations.add(savedLocation); 
    model.eventInstance.save(function(err){
        if (err) {
            winston.error(err);
            rej(err);
        }

        winston.info('done saving ' + savedLocation.name);
        res(savedLocation);
    });
});
```
However - eventInstanceId is always null on location - i am actually trying to force it twice here!

I have also tried

```
 eventInstance: model.eventInstance
```

and all host of other connotations... nothing seems to take...

Any ideas? This is using Postgres btw

**Comment by dmarcelino** [comment]
How are you retrieving `model.eventInstance`? I can't see any `Location.find().populate('eventInstance')` in your code...

**Comment by wayne-o** [comment]
That happens a step previously and it is a valid populated eventInstance model. It's id is 1

**Comment by wayne-o** [comment]
```
var ei = {
					name: model.clash_finder.current_import.desc,
					slug: helpers.slugify(model.clash_finder.current_import.desc),
					start: new Date(model.clash_finder.current_import.startDate * 1000)
				};

				EventInstance.create(ei, function(err, saved) {

					if (err) {
						winston.error(err);
						reject(err);
					}

					model.eventInstance = saved;

					model.saved_import_data.importFor = saved;

					resolve(model);

				});
```

**Comment by dmarcelino** [comment]
> eventInstanceId is always null on location

By "location" which particular variable are you referring? Is it `savedLocation`?

**Comment by wayne-o** [comment]
The location.create comes back with an ID for eventInstance but looking in the db it is always null

**Comment by dmarcelino** [comment]
So, from your app perspective it's fine, is it just at the DB level that things are not what you expect?

Is the FKey being saved in another column, for example `eventInstance`, instead of `eventInstanceId`?

**Comment by wayne-o** [comment]
So yeah savedLocation has the ID but the db is null

**Comment by wayne-o** [comment]
Nope. It doesn't store any reference at all.

Weirdly the code works elsewhere using other models. So artist has a one to many with images and the same code, but with artist and image works. The model definitions are the same pretty much except for the names of the models being referenced.

**Comment by dmarcelino** [comment]
```javascript
    model: 'eventInstance',
```

Try `model: 'eventinstance'`, lower case.

The rationale is that `model` fields takes the identity of the collection and the identity must be lowercase ([docs](https://github.com/balderdashy/waterline-docs/blob/master/models.md#identity)). Sails is likely lowercasing `'eventInstance'` for the `identity` when it passes the collections to waterline.

**Comment by wayne-o** [comment]
Ok, I'll try that. Is this likely a bug?

**Comment by dmarcelino** [comment]
Nah, just a frustrating limitation of waterline. At some point I guess waterline will either:

1. support cased identities;
2. lower case identities automagically.

I vote for 1.

The problem in this case is that sails.js is lower casing the identity behind the scenes hiding this (documented) particularity of waterline.

**Comment by wayne-o** [comment]
It works - if I remove the locations property from the eventInstance... This isn't good :p

**Comment by dmarcelino** [comment]
Try adding `identity: 'eventinstance'` to the eventInstance model definition. I'm not a 100% sure how sails processes the model definitions.

**Comment by dmarcelino** [comment]
Closing this as inactive, please re-open at any time if you have new information or believe this hasn't been fully answered.
