### ISSUE TITLE
required === notNull?

### ISSUE THREAD

**Issue by aars** [balderdashy/waterline#1012]
It seems that the `required` flag is only used in Model validation, and the `notNull` flag is translated to `NOT NULL` for the underlying database.

Is it a good idea to have `required` reflected in `notNull`? Since mismatching those does not make sense, it would mean the Model validation accepts a null value, but the database doesn't, or the other way around. Both cases are broken, but the former most.

Adding a case for `required` that overrides `attr.notNull` with the same value as `required` here would suffice I think:
https://github.com/balderdashy/waterline/blob/master/lib/waterline/core/schema.js#L155

Thoughts?

**Comment by dmarcelino** [comment]
Hi @aars, that's a very interesting question. From a validation standpoint they are indeed very similar, check [required](https://github.com/balderdashy/anchor/blob/master/lib/match/rules.js#L19-L26) vs. [notNull](https://github.com/balderdashy/anchor/blob/master/lib/match/rules.js#L81) code.

The only advantage I can think of in keeping them as they are is that enforcing a `required` validation doesn't impose database constraint as `notNull` does, but that would probably be an edge case.

Not sure what was the original intention for this difference, not even sure if it was intentional. Do you know @particlebanana?

**Comment by aars** [comment]
@dmarcelino What would be the actual use case of this enforced 'required` but non `notNull` edge case? I don't think there is one.

**Comment by dmarcelino** [comment]
I can image cases where you have more than one process using the DB and one process may need less restrictions than the other. Example, one automated process pre-populates records in a DB. Then that DB is exposed via a web service to a human who has the task of enriching those records. In a case like this you may want the automated process to get away from filling a given field but you may want to enforce the human to fill it. I'm sure this won't be common, like I said, an edge case.

**Comment by aars** [comment]
When you define your data model and specify that a property is `required`, in my opinion, you are specifying that that property is `required` in your data model. Just that. To ensure correctness.

It starts to get confusing when the definitions of a data model act one way on input (checking for existence of a required property), and another on output (db-write), since the required flag does not have an effect towards my database. I can also safely retrieve a record from my database that is missing a required value. IMHO That's simply broken.

In the edge case you describe, the property is simply not required in the data model. When it becomes required it should either migrate that data to a model where the property is required, or the requiredness of the property is enforced in the input validation. Not in the ORM.

**Comment by dmarcelino** [comment]
> When you define your data model and specify that a property is required, in my opinion, you are specifying that that property is required in your data model. Just that. To ensure correctness.

I would agree with this if the properties used in model definition were all DB constraints but they are not, it's a mix between [validations](https://github.com/balderdashy/waterline-docs/blob/master/models.md#validations) and [DB constraints](https://github.com/balderdashy/waterline-docs/blob/master/models.md#attribute-properties). For example, `unique` is purely a constraint that has no validation associated with. On the other hand `email` is a validation that has no DB constraint associated with. It gets bit blurry in other cases, for example, `notNull` is both validation and constraint.

**Comment by aars** [comment]
That is exactly why it is confusing :)

One thing that we could improve anyhow are the docs. They could be more clear about what validations, db contraints and/or both are.

Personally I think enforcing `notNull` on `required` is a good choice, but we could make it so `required` implies `notNull`, and `notNull` itself could be used to override it to `false` if someone really really wants to.

**Comment by dmarcelino** [comment]
> One thing that we could improve anyhow are the docs. They could be more clear about what validations, db contraints and/or both are.

@eddieajau is doing a great job in balderdashy/waterline-docs/pull/71: Refactoring docs. Feel free to add comments to the PR to further improve it :wink: 

> Personally I think enforcing `notNull` on `required` is a good choice but we could make it so `required` implies `notNull`, and `notNull` itself could be used to override it to `false` if someone really really wants to.

I'm not sure that's less confusing that what exists now :) With the extra nuisance of potentially not being backwards compatible.

In my opinion, the good thing of the current way `required` / `notNull` work is that the developer has options:
* `required` - validation at the ORM level, don't enforce in the DB;
*  `notNull` - validation at the ORM level plus DB constrain.

The bad thing is that, as you pointed out, it's confusing what effect each option has on the DB. At this point I'm personally not sure if we should change `required` behaviour or just improve the docs.

I would also love to know what the original authors (@balderdashy/owners) had in mind when they created `required` and `notNull`.

**Comment by aars** [comment]
@dmarcelino I agree. It might just get more confusing ;) At least now I know (and I was told that's half the battle). I'm curiouabout the original intent as well.

I'll comment on the docs. Thanks for your time.

**Comment by dmarcelino** [comment]
@aars, check https://github.com/balderdashy/waterline/issues/1047#issuecomment-111140584, `notNull` may become different than `required` after all. Would love to hear your opinion on that thread.

**Comment by eddieajau** [comment]
I think it's worth updating the docs to note the exact behaviour the `required` is testing for. I'm happy for you to assign this issue to me and I'll work on something after the new structure is merged if you like.

**Comment by dmarcelino** [comment]
Lets continue discussing this issue in balderdashy/waterline-docs#86.
