### ISSUE TITLE
double, currency support

### ISSUE THREAD

**Issue by calidion** [balderdashy/waterline#1024]
float is not enough for a lot of circumstances.
double and currency are needed for better performance and data description.

**Comment by dmarcelino** [comment]
Hi @calidion, the current supported types are very aligned to javascript so they can be used by any adapter (an adapter can have any datastore behind or even some REST service). The solution for this will be to allow adapters to extend the supported types themselves to allow more specific types in a way that doesn't break interoperability with other adapters. Please check #819 and PR #981 which will allow that.
