### ISSUE TITLE
Unable to retrieve records from database

### ISSUE THREAD

**Issue by andyjessop** [balderdashy/waterline#1028]
I'm trying to retrieve a record with this:

    var users = User.find({ username: "andy" }).then(function(users){
		return users;
	});

	console.log(users);
	return res.send(users);

But I get returned:

    {
        "isFulfilled": false,
        "isRejected": false
    }

**Comment by dmarcelino** [comment]
Hi @andyjessop, you have your `console.log()` outside the `then()` statement hence it's being executed before `User.find()` completes and all you get is and unfulfilled `promise` (not the query results). Try:

``` javascript
    var users = User.find({ username: "andy" }).then(function(users){
	  console.log(users);
	  res.send(users);
          return users;
	});
```

I suggest you read more about asynchronous development, callbacks and promises.
