### ISSUE TITLE
Rename autoPk id column

### ISSUE THREAD

**Issue by ameilland** [balderdashy/waterline#1029]
Hi,

Is there a way to rename the auto generated column id when autoPK option is enabled?

Thanks,

**Comment by dmarcelino** [comment]
Hi @ameilland, none that I'm aware of.

If you are using an adapter that supports [`autoIncrement`](https://github.com/balderdashy/waterline-docs/blob/32e3e8bed3915a043b89c42cc9f97c6a97fdf7d8/models.md#autoincrement) you should be able set another field as your [`primaryKey `](https://github.com/balderdashy/waterline-docs/blob/32e3e8bed3915a043b89c42cc9f97c6a97fdf7d8/models.md#primarykey) by doing something like:

```javascript
{
  // ...
  autoPK: false,
  attributes: {
    myNewId: {
      type: 'integer',  // or 'string' depending on your own adapter/DB
      primarykey: true,
      autoIncrement: true
    }
  }
}
```

Let us know if that doesn't work.

**Comment by dmarcelino** [comment]
Please re-open if this hasn't been fully answered.
