### ISSUE TITLE
Cross database population after find

### ISSUE THREAD

**Issue by stellarashes** [balderdashy/waterline#1030]
When searching for model A by an association (say, B), then populating B, the results will always be empty even if results are found.  So:

`A.find({B: [1, 2, 3]}).populate('B')`

will always give empty array.

I've only tested on MySQL so I'm not sure if it applies to all.

Here's a test demonstrating this: https://github.com/stellarashes/waterline-test

Result when I run it: 
npm test

  Cross-database association/population
    √ should be able to set up data (56ms)
    √ should be able to populate B
    √ should be able to find by B
Unhandled rejection AssertionError: expected [] not to be empty
    1) should be able to find by B and populate B

**Comment by dmarcelino** [comment]
Hi @stellarashes, I believe the issue is not "Cross database" and not even the `.populate` but:
``` javascript
A.find({B: [1, 2, 3]});  // where B is an association and not a "regular" field
```

Currently, to the best of my knowledge, there is no official support for this. It may be working with some adapters but it's not spec'ed nor there are any [integration tests](https://github.com/balderdashy/waterline-adapter-tests/) for that. So you may be lucky... or not. Some related issues which should deal with that problem:

1. Need a way to query associated object's attributes #266  
2. [Feature Request] populate indexes for has-Many associations #532

Until the above issues are implemented I don't think it will be possible (to reliably) achieve what you are trying to do.

**Comment by stellarashes** [comment]
Maybe the proper way to do this in waterline is querying B and B having one-to-many relation to A then.  The strange thing is that the MySQL adapter does return the right result without populating, but I guess since it's not officially supported, it was just luck that returned the right rows.

**Comment by dmarcelino** [comment]
> Maybe the proper way to do this in waterline is querying B and B having one-to-many relation to A then. 

You mean something like: `B.find([1, 2, 3]).populate('A')`? Yes, I think that should work.

**Comment by miehilmie** [comment]
Weird, for me it's working properly. 

```District.find({state: ["MY-01","MY-02"]).populate('state').exec(console.log)```give correct value

```
[
...
...
{ state: 
     { code: 'MY-02',
       name: 'Kedah',
       createdAt: '2015-05-07T21:55:38.970Z',
       updatedAt: '2015-05-07T21:55:38.970Z',
       id: '554bdf5a161aa85030ec9826' },
    name: 'SG.PETANI',
    createdAt: '2015-05-10T18:38:01.798Z',
    updatedAt: '2015-05-10T18:38:01.798Z',
    id: '554fa589ce716d6032e92834' },
  { state: 
     { code: 'MY-02',
       name: 'Kedah',
       createdAt: '2015-05-07T21:55:38.970Z',
       updatedAt: '2015-05-07T21:55:38.970Z',
       id: '554bdf5a161aa85030ec9826' },
    name: 'SUNGAI KARANGAN',
    createdAt: '2015-05-10T18:38:01.799Z',
    updatedAt: '2015-05-10T18:38:01.799Z',
    id: '554fa589ce716d6032e92835' } 
]
```

Btw, I do set state's `code` as `primaryKey: true` in it's model attribute

**Comment by dmarcelino** [comment]
@miehilmie, like I said earlier in https://github.com/balderdashy/waterline/issues/1030#issuecomment-105297519 this may work in some adapters and in some particular scenarios but waterline doesn't guarantee it will work. There is no official support or tests for this. A similar case has been discussed in #469.

Out of curiosity, which adapter are you using?

**Comment by miehilmie** [comment]
@dmarcelino , I'm using sails-mongo adapter

**Comment by dmarcelino** [comment]
It's probably best to continue this discussion in #266 for now, check https://github.com/balderdashy/waterline/issues/266#issuecomment-107531782. Please re-open if you feel differently.
