### ISSUE TITLE
Update on a model with a one-to-many association has an unexpected behavior

### ISSUE THREAD

**Issue by benjamintalou** [balderdashy/waterline#1031]
Hello there.
I'll try to explain my problem with a simple example.

I have two models (Postman and Letter) related by a many-to-one association:

```javascript
{
    identity: 'postman',

    attributes: {
        name: {
            type: 'string',
            required: true
        },
       letters: {
           collection: 'letter',
            via: 'postman_id'
       }
    }
}
```

```javascript
{
    identity: 'letter',

    attributes: {
        address: {
            type: 'string',
            required: true
        },
       postman_id: {
            model: 'postman'
       }
    }
}
```

Using Create, I can populate both of my tables with consistant data. Let's say:

Postman
```
{"name":"John, id:"1"}
{"name": "Paul", "id": "2"}
```

Letter
```
{"address":"First address", id: "1", "postman_id": "2"}
{"address":"Second address", id: "2", "postman_id": "1"}
{"address":"Third address", id: "3", "postman_id": "2"}
{"address":"Forth address", id: "4", "postman_id": "2"}
```

Now, I want to change Paul's name by "Another Paul".

```Postman.update(2, {name: 'Another Paul'}, callback)```

The update works on the Postman model, but all the letters that belong to Paul lost their "postman_id"  to an empty value.

I tried to add the "required" constraint on the letter.postman_id field, in that case the update on the Postman failed because of a constraint violation on a Letter (makes sense as this fields seems to be updated with an empty value ).

I don't understand why the Letter models are updated during this process.
Am I missing something?

Thank you for your help.

**Comment by dmarcelino** [comment]
Hi @benjamintalou, `Postman.update(2, {name: 'Another Paul'}, callback)` shouldn't indeed touch the association `'letters'`. A few questions:
* `{name: 'Another Paul'}` is this the actual data you are passing to `.update()`? Are you sure no association data is being passed?
* which adapter and respective version are you using?
* which version of waterline are you using?

**Comment by benjamintalou** [comment]
Oh my bad.
My mistake was to directly use a result from a findOne request to update my item, so an association data was passed. Shouldn't it be fobidden to pass this kind of values?

Thanks for your quick reply and your help!

**Comment by dmarcelino** [comment]
> Shouldn't it be fobidden to pass this kind of values?

Not at all, since waterline *supports* nested updates. The behaviour still needs some work though, check #975.

You're welcome! :wink:
