### ISSUE TITLE
Group the attributes 

### ISSUE THREAD

**Issue by akshitjain** [balderdashy/waterline#1034]
How can we group the attributes in waterline 
eg:

```js
var User = Waterline.Collection.extend({
  identity: 'user',
  connection: 'myLocalMongo',
  autoPK: false,
  attributes: {
person:{
    id:{
       type: 'integer',
       primaryKey: true
    },
    first_name: {
      type:'string'
    },
    middle_name:{
      type:'string',
      defaultsTo:'kumar'
      },
    last_name: {
      type:'string'
    }
}
  details:{
  age:{
      type:'integer',
      defaultsTo:20
    },
 sex:{
     type:string
   }
}
  }
});
```

**Comment by dmarcelino** [comment]
Hi @akshitjain, in waterline you can't have attributes nested in other attributes. Please note that waterline is a multi-adapter/db ORM and contrary to Mongo not all DBs support querying nested documents/records. You can however:
* Move the nested attributes to another model and then associate it with first one using [associations](https://github.com/balderdashy/waterline-docs/blob/master/associations.md), or...
* Use the [json](https://github.com/balderdashy/waterline-docs/blob/master/models.md#data-types-and-attribute-properties) attribute and save your nested attributes as a json.

**Comment by dmarcelino** [comment]
Please re-open if you think this is not fully answered.
