### ISSUE TITLE
.save() and .populate() aren't friends

### ISSUE THREAD

**Issue by anasyb** [balderdashy/waterline#1037]
```
User.findOne('xyz').populate('posts').exec(function(err, user){
  user.comments.add('someCommentID');
  user.save();
})
```
This is trying to re-insert all posts into user?! Of course it throws off an `already exists` error (and sometimes even goes ahead and inserts duplicate records into the join table https://github.com/balderdashy/sails-mongo/issues/288 !!!). Somehow related to https://github.com/balderdashy/waterline/issues/975 and the other issues referenced in there, but not sure its the same thing.
On mongo.

P.S.: not sure if `user.comments.add('someCommentID');` is needed to reproduce the error, but that's what I have in my code. Maybe its just the `.save()`.

**Comment by devinivy** [comment]
Related: this old PR #898 fixing #858, where `save` and `populate` were not behaving very nicely together.  In your example, are Users and Posts in a one-to-many or many-to-many relationship?

**Comment by anasyb** [comment]
Thanks @devinivy, as awesome as always!
- sorry haven't caught that issue and PR, looks very similar
- Yeah I think I am still on 10.18.
- This happened in a one-way relationship: user has many posts, but post has no user. I think (but not sure) waterline assumes it's many-to-many.

**Comment by devinivy** [comment]
I highly suggest upgrading past 0.10.18.  There's a data integrity danger if you populate an incomplete collection (say, by using population criteria) then save.

**Comment by dmarcelino** [comment]
Hey @anasyb, did updating waterline fix the issue?

**Comment by dmarcelino** [comment]
Closing this as inactive, please re-open if the problem persists.
