### ISSUE TITLE
Schema Diagramming Tool

### ISSUE THREAD

**Issue by gunish** [balderdashy/waterline#1038]
Hi,

Is there an automatic way to generate an ORD / ERD from the waterline models ? Something on the lines of SchemaSpy ?

I am looking for a schema diagraming tool to visualise the Models which I created for my SailsJS app.

If there is such a thing!

Thanks In advance!

**Comment by devinivy** [comment]
I've never heard of such a thing, but I think it would be great.  @tjwebb do you have any idea?

**Comment by tjwebb** [comment]
Yea, like a visual entity-relationship mapping tool. I think this would be really cool. It might be worth asking the folks at treeline.io if they have anything in the works.

**Comment by gunish** [comment]
One way i am trying to work around to getting something going is to utilise the ability to change adapters, here is what I did :

1. Installed MySql on my machine, 
2. Changed the adapter from my sails application from mongodb to mysql 
3. Ran schemaspy on mysql. 

Schema Spy Re-verse engineers diagrams like this : http://schemaspy.sourceforge.net/sample/relationships.html

But I have run into a hickup, 
* when I lifted the sails application, it created the tables in mysql but it did not create the relationships (PK , FK etc), maybe there is a way to enforce that ? 

So I was able to get the table description out, but the real nice stuff around reverse engineered relationships is missing.  

What do you guys think ?

**Comment by devinivy** [comment]
@gunish there's a feature request for this in the sails-mysql project: https://github.com/balderdashy/sails-mysql/issues/172

Currently you _do_ have to add FK contraints manually, which I think is a bit of a shortcoming.  Would love a PR!

**Comment by dmarcelino** [comment]
Closing this as inactive, please re-open if you feel this hasn't been fully answered. Thanks

**Comment by gunish** [comment]
Sorry just noticed the comments from @devinivy , yes thats cool, for now in my project, we resorted to doing it manually, but there should be an easy win if we were able to get a a simple drawing library to perform some static code analysis and draw out an ERD. schemaspy is old and very good, we want something basic and in the browser.
