### ISSUE TITLE
find-where with array attributes don't do deep comparisons

### ISSUE THREAD

**Issue by givanse** [balderdashy/waterline#1050]
If an attribute is defined as an Array, this query: `where({ arrAttr: [1, 2] })` returns empty results, its probably doing object comparison `[1, 2] == [...]`, unless I'm using the wrong syntax.

I expected a deepEquals-style comparison for this.

Where do I find the source code where this is happening?

**Comment by givanse** [comment]
So, this should be treated as text comparisons for SQL adapters (use like, contains, regexp).

And what I described seems to be specific to `sails-disk`.

**Comment by dmarcelino** [comment]
Hi @givanse, these comparisons would be handled by the adapters: [sails-disk](https://github.com/balderdashy/sails-disk), in the case of sails-mysql and sails-postgresql both rely on [waterline-sequel](https://github.com/balderdashy/waterline-sequel) to generate the SQL queries.
