### ISSUE TITLE
Random data deletions?

### ISSUE THREAD

**Issue by wayne-o** [balderdashy/waterline#1058]
Hi 

I am not sure this is a waterline issue but I can't think what else it could be. We have a postgres DB which we use waterline to interact with.

Every now and then a random table will have it's data deleted! Today it was our users table but it could be any table. 

We've searched the logs (when it first happened we turned on logging for literally everything) and we can't find anything hinting at delete or truncate on the users table - it's just gone!

Does anyone have any clues what this could be?

**Comment by wayne-o** [comment]
OK so going through the logs on the server I can actually see there are delete table statements:

```
2015-06-13 11:51:22 UTC LOG:  statement: DROP TABLE "eventInstance";
2015-06-13 11:51:22 UTC LOG:  statement: DROP TABLE "filteredlineup";
2015-06-13 11:51:33 UTC LOG:  statement: DROP TABLE "image";
2015-06-13 11:53:00 UTC LOG:  statement: DROP TABLE "artist";
2015-06-13 11:53:29 UTC LOG:  statement: DROP TABLE "attempt";
2015-06-13 11:53:30 UTC LOG:  statement: DROP TABLE "auth";
2015-06-13 11:53:30 UTC LOG:  statement: DROP TABLE "campsite";
2015-06-13 11:53:30 UTC LOG:  statement: DROP TABLE "discoursesso";
2015-06-13 11:53:30 UTC LOG:  statement: DROP TABLE "eventInstance";
2015-06-13 11:53:30 UTC LOG:  statement: DROP TABLE "filteredlineup";
2015-06-13 11:53:40 UTC LOG:  statement: DROP TABLE "image";
2015-06-13 11:53:41 UTC STATEMENT:  DROP TABLE "image";
2015-06-13 11:55:19 UTC LOG:  statement: DROP TABLE "artist";
2015-06-13 11:55:48 UTC LOG:  statement: DROP TABLE "attempt";
2015-06-13 11:55:48 UTC LOG:  statement: DROP TABLE "auth";
2015-06-13 11:55:49 UTC LOG:  statement: DROP TABLE "campsite";
2015-06-13 11:55:49 UTC LOG:  statement: DROP TABLE "discoursesso";
2015-06-13 11:55:49 UTC LOG:  statement: DROP TABLE "eventInstance";
2015-06-13 11:55:49 UTC LOG:  statement: DROP TABLE "filteredlineup";
2015-06-13 11:55:59 UTC LOG:  statement: DROP TABLE "image";
```

LOADS of them!

Why is waterline doing this? the model hasn't changed in ages!

**Comment by particlebanana** [comment]
You need to make sure your migrations are off. I'm guessing you have your migrate strategy set to `drop` or `alter` (which is the default). If using Sails in production mode it should never touch your database or if you set the migration strategy to `safe` your database won't be touched.

**Comment by tjwebb** [comment]
Yea, what @particlebanana said. If this is in production, then like any node.js application, you should set `NODE_ENV=production`.

**Comment by kevinburkeshyp** [comment]
That feels backwards though, shouldn't data safety be something you have to
opt out of ?

Understand it's probably too late to change in this instance, but I
sympathize a lot with the OP.

-kevin

On Jun 13, 2015, at 19:46, Travis Webb <notifications@github.com> wrote:

Yea, what @particlebanana <https://github.com/particlebanana> said. If this
is in production, then like any node.js application, you should set
NODE_ENV=production.

—
Reply to this email directly or view it on GitHub
<https://github.com/balderdashy/waterline/issues/1058#issuecomment-111773490>
.

**Comment by devinivy** [comment]
@dmarcelino what's the state of those changes made to migration defaults?  I think this behavior has changed in recent versions of waterline.

**Comment by tjwebb** [comment]
> That feels backwards though, 

Sails **does** warn you even in dev mode about the migrations, and won't even load your app until you manually select a migrate option at a console prompt. That prompt only goes away once you've manually configured a migrate setting in the config files. Therefore, you have `alter` or `drop` in your configs, and you did not set `NODE_ENV` to production, nor did you start sails with the `--prod` flag. In production mode, Sails has a hardcoded override that forces `safe` migrations. The OP has blown through two levels of safeguards Sails has in place to try to protect against this situation.

For those reasons, I'm having a difficult time being very receptive to the argument that Sails makes it too easy to corrupt data. 

The convention-over-configuration approach of Sails is relevant and useful during development, but deploying to production should be treated as **a big deal**, where there's no substitute for careful and proper configuration. If you don't tell Sails that it's in production mode, and you have it configured incorrectly, then Sails doesn't know that it needs to save you from yourself.

**Comment by wayne-o** [comment]
I run sails with sails debug and never see that output btw :)

I do feel it could be made clearer that it is experimental and you (most-likely will?) probably lose data if you use anything other than safe...

This has cost us no end of headache and we have had to re-initialise our system loads of times because of data corruption - I'm just glad we found out what it was!! We haven't gone live yet so it's not technically production but the fact we were losing data was a real headache.

Now then - how are we all managing change in Postgres if we aren't using alter?!

Aside from all of this - we are loving sails + waterline for our backend - super super productive (coming from .NET I guess even my gran would be a more productive API framework but still! )

**Comment by devinivy** [comment]
I think the question here is answered, so I'm going to close this out.  If there's actually more to say here, just flag me to reopen it!

**Comment by kevinburkeshyp** [comment]
We just put migrations in a folder, sorted by date, and run them by hand, with a checklist. Not the "most scalable" or whatever, but it works..

**Comment by tjwebb** [comment]
> I run sails with sails debug and never see that output btw :)
> This has cost us no end of headache and we have had to re-initialise our system loads of times because of data corruption 

@wayne-o Then just like the OP, you've manually set migrate already. But I don't need to argue with you, I can just show you what **actually** occurs:

```
tjwebb@latitude:/home/tjwebb $ sails generate new test1
info: Created a new Sails app `test1`!
tjwebb@latitude:/home/tjwebb $ cd test1/
tjwebb@latitude:/home/tjwebb/test1 $ sails generate api TestModel
info: Created a new api!
tjwebb@latitude:/home/tjwebb/test1 $ sails lift

info: Starting app...

-----------------------------------------------------------------

 Excuse my interruption, but it looks like this app
 does not have a project-wide "migrate" setting configured yet.
 (perhaps this is the first time you're lifting it with models?)
 
 In short, this setting controls whether/how Sails will attempt to automatically
 rebuild the tables/collections/sets/etc. in your database schema.
 You can read more about the "migrate" setting here:
 http://sailsjs.org/#/documentation/concepts/ORM/model-settings.html?q=migrate

 In a production environment (NODE_ENV==="production") Sails always uses
 migrate:"safe" to protect inadvertent deletion of your data.
 However during development, you have a few other options for convenience:

 1. safe  - never auto-migrate my database(s). I will do it myself (by hand) 
 2. alter - auto-migrate, but attempt to keep my existing data (experimental)
 3. drop  - wipe/drop ALL my data and rebuild models every time I lift Sails

What would you like Sails to do?

info: To skip this prompt in the future, set `sails.config.models.migrate`.
info: (conventionally, this is done in `config/models.js`)

warn: ** DO NOT CHOOSE "2" or "3" IF YOU ARE WORKING WITH PRODUCTION DATA **

prompt: ?:  


```
