### ISSUE TITLE
how to render selected fields

### ISSUE THREAD

**Issue by kuangyunsheng** [balderdashy/waterline#1059]
Hi:

  I use the Waterline ORM for my Sails Js applications.
  For queries, I would like to render selected fields.

  In the documentation, there is select method :
```js
  User.find()
  .select({name:1})
  .sort('name')
  .exec(function(err, users) {
    // Do stuff here
  });
```

But, it renders all the fields of the User model. 
why?

Thanks﻿

**Comment by dmarcelino** [comment]
Hi @kuangyunsheng, where did you see such `.select` example? That's wrong and not implemented yet (#73).

The correct way of using `select` can be found in https://github.com/balderdashy/waterline-docs/blob/5cc4b64207a8cb8e81c53358c7d6024e26e02147/queries/query-language.md#select:

```js
Model.find({ where: { age: { '<': 30 } }, select: ['name'] })
```

**Comment by kuangyunsheng** [comment]
I had done this according to the doc, e.g.:

sails console

sails>User.find({select:['userid']}).limit(1).exec(function(err,result){console.log(result)});
undefined
sails> [ { userid: 'user1',
    username: 'user1',
    createdAt: Mon Jun 08 2015 14:44:46 GMT+0800 (中国标准时间),
    updatedAt: Tue Jun 09 2015 14:28:35 GMT+0800 (中国标准时间),
    id: '557539de0b2db8d40e5e6d92' }]


It return all fields.

**Comment by dmarcelino** [comment]
Which adapter are you using? Sails-mongo did not support `select` until recently (balderdashy/sails-mongo#281), a fix has been made and it will go out in the next release (v0.11.3 I believe).
