### ISSUE TITLE
Waterline select fields in query

### ISSUE THREAD

**Issue by natarajanp** [balderdashy/waterline#1063]
Model.find({ where: { age: { '<': 30 } }, select: ['name'] }) is not working, but it is mentioned in the doc https://github.com/balderdashy/waterline-docs/blob/master/queries/query-language.md (Last line in this link)

Is the select feature available or is it something wrong in the doc?

**Comment by devinivy** [comment]
Make sure your adapter is up to date.  Up until recently, sails-mongo had a bug with select.  Which adapter are you using and what is its version?

**Comment by natarajanp** [comment]
will check.. Thanks... I'm using sails-mongo@0.10.8

**Comment by dmarcelino** [comment]
From https://github.com/balderdashy/waterline/issues/1059#issuecomment-112361427:

> Sails-mongo did not support select until recently (balderdashy/sails-mongo#281), a fix has been made and it will go out in the next release (v0.11.3 I believe).

We probably should push a new sails-mongo version as this is the 2nd or 3rd issue about it...

**Comment by dmarcelino** [comment]
Closing this as inactive, feel free to re-open if you feel this hasn't been fully answered.
