### ISSUE TITLE
Mapping models/attributes to tables/columns with underscore?

### ISSUE THREAD

**Issue by Jarzka** [balderdashy/waterline#1064]
Hi

It seems that waterline maps models and their attributes to tables and their columns using camelCase, ie. for example a model RaceCar, with a topSpeed attribute, maps to database table racecar and topSpeed column. Is it possible to use underscores in mapping (RaceCar -> race_car & topSpeed -> top_speed) since they are far more common in databases than camelCase?

I know I can do this my defining custom table and column names for models but I would not like to do this for every single model and attribute.

Is it even necessary to rewrite all table's column names as attributes in models?

**Comment by dmarcelino** [comment]
Hi @Jarzka,

Regarding model names (I take you mean identity), this has to be lower case. Check the [model definition docs](https://github.com/balderdashy/waterline-docs/blob/master/models/models.md#how-to-define-a-model) so there is no camelCase conversion going on there. In other words using `identity: 'RaceCar'` is invalid and you need to use: `identity: 'racecar'` or `identity: 'race_car'`. It's a known limitation that we won't to fix at some point.

Regarding the attributes names. I don't believe there is any conversion going on. If you name an attribute `'top_speed'` that should work.

In other words, the following should be valid:

```js
{
  identity: 'race_car',
  attributes: {
    'top_speed': 'float'
  }
}
```

And map to a `race_car` table and a `top_speed` column without needing to use `tableName` or `columnName`.

> Is it possible to use underscores in mapping (RaceCar -> race_car & topSpeed -> top_speed) since they are far more common in databases than camelCase?

Do you have data to back this? Waterline supports SQL (MySQL, PostGres, etc) and NoSQL (MongoDB, Redis, OrientDB, etc) and even supports any kind of service that has an adapter for. So I'm no so sure that underscores are generally more common than camelCase. Either way waterline does not enforce camelCase so this shouldn't be an issue.

**Comment by dmarcelino** [comment]
Closing this as inactive, please re-open if you feel this hasn't been fully answered.
