### ISSUE TITLE
Model.create times out with no clues as to why.

### ISSUE THREAD

**Issue by kheide** [balderdashy/waterline#1066]
I've become sorely desperate. 

I have an AuthController where I have a function called register that calls Users.create() for a user to register. If I leave out any required fields it throws me an error, if I give it everything the want it wants it nothing happens. The request just times out. Model.create works elsewhere. 

```javascript 
    Users.create({email: email, username: username, tenant: tenant}).exec(function (err, user) {
      console.log(err);
      console.log(user);
      if (err) {
        return res.serverError(err);
      }
      if (user) {
        // We create a registrationToken for use to complete the registration and set a password
        var registrationToken = jwToken.issue({id: user.id});
        user.registrationToken = registrationToken;
        user.save();
        return res.ok({
          action: 'registrationSuccess',
          message: 'Registration was successful'
        });
      }
    });
```

This is the code which I am trying to run. None of those console.log statements print anything at all. Nothing is printed in console when I set logging to silly. It's just completely dead.

**Comment by devinivy** [comment]
Which adapter are you using?  Is it sails-mongo, by chance?  This is eerily similar to https://github.com/balderdashy/sails-mongo/issues/300 :(

Can you check to see if the query callback isn't being called, but the operation is actually succeeding (the record is created)?

**Comment by kheide** [comment]
Thanks for the quick response. Much appreciated! 

Yeah, i've tried doing just Users.create(); but I get no action in the DB. I don't see anything on the mongo console and no records gets created in the db. 

PS. yeah its sails-mongo. Running 0.10.6 as there was another bug that made me have to downgrade.

**Comment by devinivy** [comment]
If you manually try to create the record using `Collection.native`, does it succeed?

**Comment by kheide** [comment]
Collection.native worked!

**Comment by devinivy** [comment]
This does point to an issue with the adapter, sadly.  If anyone can provide a failing test that would be a great start.  It seems like this sort of issue would definitely be caught by the waterline test suite.

**Comment by kheide** [comment]
I'm not a great tester. If you can point me in the right direction on how to provide you with a test I would be glad to contribute.

**Comment by dmarcelino** [comment]
Hi @kheide, please take a look at the tests in https://github.com/balderdashy/waterline/tree/master/test/integration/model, or if you prefer to do something that hits the adapters/DBs take a look at https://github.com/balderdashy/waterline-adapter-tests/tree/master/interfaces/semantic. Let us know if you have any questions.

**Comment by kheide** [comment]
I have narrowed this down to not being a sails-mongo issue as it happens even if I switch to sails-disk or any other adapter. It has also started happening to some of my update queries aswell without me knowing exactly whats triggering it, but I have a feeling it has something to do with associations.

**Comment by particlebanana** [comment]
@kheide I see you have some sort of tenant system setup? How is that working?

```javascript
Users.create({email: email, username: username, tenant: tenant})
```

**Comment by kheide** [comment]
Hey banana! Yes as a matter of fact I do. 

It's not rocket science. All models have a tenant attribute. Clients authenticate with a jwt token which also has the tenant ID in it. I have a policy that sets req.options.where so only tenant specific data is retrieved. I also have a policy which adds the tenant to the post request on create (and removes it on update). 

I have disabled all these policies while troubleshooting this problem though so I do not fear that it is my amateurish tenancy setup thats causing it :-)

**Comment by particlebanana** [comment]
So to narrow down we can start at something that is known to work and backtrack from there. Obviously `Model.create` works in Waterline and is well tested. So lets get the request out of the picture and just run the following commands:

```javascript
sails console
```

Now in the console do a single create and log the result:

```javascript
Users.create({ email: 'foo@foo.com', username: 'foobar' }).exec(console.log);
```

That will either succeed or fail but you will get a result back. If not something on the connection to your database is off I would guess and is timing out.

**Comment by kheide** [comment]
I already tried that. And the Model.create also works fine when I do it from Postman and hit POST myapi.com/users

**Comment by kheide** [comment]
This is where it happens in the code. I have narrowed it down. 

waterline/lib/waterline/query/dql/create.js Line 73 

```javascript
    beforeCallbacks.call(self, valuesObject, function(err) {

      if(err) return cb(err);
      createValues.call(self, valuesObject, cb);
    });
```

beforeCallbacks never seem to enter its callback function because anything in there is never run.

**Comment by kheide** [comment]
Ok we can close this now. I have found the problem. It's me, not Waterline! :D 

I had a beforeCreate callback that had an if clause checking for user.password where the else didnt run cb(). Unfortunately you can see the error further up in my code as I was not sending the password into Model.create(). 

Thanks for your help tho :-)

**Comment by dmarcelino** [comment]
That sometimes happens :) Thanks for letting us know.
