### ISSUE TITLE
Save datetime fractions of second

### ISSUE THREAD

**Issue by murhum1** [balderdashy/waterline#1075]
I'm using the datetime attribute in my model and would like to save accurate timestamps for my records. I'm using the sails-mysql adapter, and even after modifying the field into datetime(3) after initializing the model, it doesn't seem to save the fractions of second, but rather sets them to hh:mm:ss.000. Is this a waterline-related issue or sails-mysql related?

**Comment by dmarcelino** [comment]
Hi @murhum1, this is not a waterline core issue but a [sails-mysql adapter](https://github.com/balderdashy/sails-mysql) issue, namely in its helper library waterline-sequel. There is an open pull request to support milliseconds, check PR balderdashy/waterline-sequel#24.

**Comment by devinivy** [comment]
Good call @dmarcelino!  Should we move this conversation over there?

**Comment by dmarcelino** [comment]
Yes, I think that's better.

**Comment by devinivy** [comment]
See you all over at balderdashy/waterline-sequel#24!  Is that okay, @murhum1?
