### ISSUE TITLE
Waterline in the browser with bower?

### ISSUE THREAD

**Issue by avimar** [balderdashy/waterline#1079]
Hi, I see there's a bower config, but I don't see any examples of how to use it.. nor what to use it with.

E.g. there's an adapter for rest -- https://github.com/zohararad/sails-rest/tree/v0.1.0-waterline-v0.10 so I would have expected to theoretically share my model definition between server and client and then use the same query syntax on client and server. But I don't see a bower config there nor any other particular examples of how I'd use waterline in the browser. Is there any point?

**Comment by devinivy** [comment]
I don't personally know of anyone who has tried this out.  I imagine the dependencies will be rather heavy for realistic browser use, but I invite anyone interested to address this.

I would love to see an adapter meant for browser use that hits a blueprint-style API for data.

**Comment by Ryanc1256** [comment]
would be cool for a adapter based off local storage :+1: 
Would be pretty close to the redis one, since it's just uses keys the same as what local storage does.

**Comment by devinivy** [comment]
I think a great first step would be to see how large waterline and its dependencies would be in browser.

**Comment by Ryanc1256** [comment]
haha, yeah im scared to see :stuck_out_tongue:

**Comment by dmarcelino** [comment]
Closing this for now as it seems inactive, please re-open if you feel this hasn't been fully answered.
