### ISSUE TITLE
changelog or release notes?

### ISSUE THREAD

**Issue by shaunc** [balderdashy/waterline#1081]
I see from the recent releases you are making fast progress on this -- thats great; thank you!

It would be great if you could maintain a change-log or some release notes so I could more easily figure out if I wanted to upgrade.....

**Comment by devinivy** [comment]
I like that idea.  I suggest https://www.npmjs.com/package/mdchangelog .

**Comment by dmarcelino** [comment]
We should highlight the main changes in [waterline/releases](https://github.com/balderdashy/waterline/releases) like we do in [sails-orientdb/releases](https://github.com/appscot/sails-orientdb/releases)...

**Comment by dmarcelino** [comment]
I don't think there is much to do here for now so I'm closing this issue. Thanks for the *heads up*, we'll try to improve things going forward.

**Comment by shaunc** [comment]
Sure thing -- thanks!
