### ISSUE TITLE
Postgres with migrate: 'alter': Resets auto increment value

### ISSUE THREAD

**Issue by mmiller42** [balderdashy/waterline#1092]
I know migrate is experimental, but I thought this was worth mentioning.

When setting up a model that relies on Postgres, if `migrate` is set to `"alter"`, it appears that after adding some records and then destroying them, after a restart (lifting Sails), the IDs are reused.

For example:

```js
sails console
User.create({ email: 'my@email.com', password: 'hello' }).exec(sails.log); // id = 1, expected id = 1
User.destroy(1).exec(sails.log);
User.create({ email: 'my@email.com', password: 'hello' }).exec(sails.log); // id = 2, expected id = 2
User.destroy(2).exec(sails.log);
<Ctrl + C>
<Ctrl + C>
sails console
User.create({ email: 'my@email.com', password: 'hello').exec(sails.log); // id = 1, expected id = 3
```

**Comment by dmarcelino** [comment]
Hi @mmiller42, `'alter'` strategy as [currently implemented](https://github.com/balderdashy/waterline/blob/master/lib/waterline/adapter/sync/strategies/alter.js) in waterline core is pretty simple, it essentially saves the table data, drops the table, re-creates the table and then re-inserts the data (hence not suited for production). Anyway, the `'alter'` strategy itself does nothing to the `ids`. Having little experience with Postgres I'm guessing Postgres is resetting the `ids` after the table drop. Is that configurable at the Postgres level?

**Comment by mmiller42** [comment]
Ah, that entirely makes sense. That probably isn't possible then, as I'm pretty sure Postgres stores the autoincrement value as metadata on the table so it's dropped.

**Comment by mmiller42** [comment]
This would then be a feature enhancement request, but alter could be enhanced to capture the current auto-increment value and restore it when rebuilding the table, before applying the data inserts.

```sql
SELECT nextval('{{table name here} }}_{{ pk column name here }}_seq'); -- fetches the next autoincrement value
```
After dropping, you could 

```sql
ALTER SEQUENCE {{table name here }}_{{ pk column name here }}_seq RESTART WITH {{ next autoincrement value here }};
```

Then, since the data will be restored with the ID set on it, I'd assume then that the IDs of the existing records would be preserved, while new records would start with the existing auto-increment value.

**Comment by dmarcelino** [comment]
Sounds reasonable but would need to be done in the [sails-postgresql project](https://github.com/balderdashy/sails-postgresql) after waterline allows adapters to override migrate strategies. Please raise an issue in that project and close this one. Thanks!

**Comment by mmiller42** [comment]
Thanks, will do!
