### ISSUE TITLE
How can I use a feature like TTL (Time to live) on a MongoDb field?

### ISSUE THREAD

**Issue by SudoPlz** [balderdashy/waterline#1097]
I'm trying to create [a field that expires after some seconds](http://docs.mongodb.org/manual/tutorial/expire-data/) in MongoDB. 

How can I do that with waterline?

**Comment by dmarcelino** [comment]
Hi @SudoPlz, currently there is no `ttl` interface in waterline core so you would need to to use sails-mongo `.native()` method ([docs](http://sailsjs.org/documentation/reference/waterline-orm/models/native)) to accomplish that.

**Comment by SudoPlz** [comment]
Thank you, I found out how to do it, so I leave it here in case someone needs it later on. https://github.com/balderdashy/sails-mongo/issues/311

**Comment by lennym** [comment]
Found this issue from a google search for the same problem. Wrote https://www.npmjs.com/package/sails-hook-ttl in response.
