### ISSUE TITLE
Sails Waterline “Or” clause not working

### ISSUE THREAD

**Issue by vijrej** [balderdashy/waterline#1104]
I tried a lot of time to figure out getting an OR clause working in sails without success.

I am using Sails-MySql adapter.

Have anyone of you done anything like this already? I would appreciate some help.

Basically this is what I want to do:

Do an OR clause on a set of fields along with an AND on another set of fields.

Something like this:

FdbDevice.find().where( or : [ { deviceCategory: “cardiology valve bioprosthesis” }, { deviceCategory: “nephrology haemodialysis catheter” } ] } )
                              .where (  { catalogNumber : “Z286004” },  { modelNumber: “Z286004” })
                              .exec

**Comment by dmarcelino** [comment]
Hi @vijrej, your query, looks invalid for a couple of reasons:
* `where( or : [ { deviceCategory: “cardiology valve bioprosthesis” }, { deviceCategory: “nephrology haemodialysis catheter” } ] } )`: your first `or` is not preceded by `{`;
* `.where ( { catalogNumber : “Z286004” }, { modelNumber: “Z286004” })` you are providing 2 objects to `where`.

Can you try:

```js
FdbDevice.find().where({
  or: [
    { deviceCategory: “cardiology valve bioprosthesis” },
    { deviceCategory: “nephrology haemodialysis catheter” } 
  ],
  catalogNumber: [“Z286004”, “Z286004”]
} )
.exec(/*...*/);
```

I strongly suggest you read [waterline docs: query language](https://github.com/balderdashy/waterline-docs/blob/master/queries/query-language.md) and check some query examples in the [waterline adapter tests](https://github.com/balderdashy/waterline-adapter-tests/tree/master/interfaces/queryable/modifiers).

**Comment by dmarcelino** [comment]
Any updates on this @vijrej?
