### ISSUE TITLE
Support queries with raw `sort` and `where` strings

### ISSUE THREAD

**Issue by dbkaplun** [balderdashy/waterline#1107]

**Comment by devinivy** [comment]
Can you provide more info?  Which adapter are you thinking of?

**Comment by dbkaplun** [comment]
I'm using `sails-postgresql`. I would like to be able to calculate a new column for every row and sort by it. Right now I'm doing this manually via `Model.query('SELECT')` but it would be nice to be able to do this via ORM.

**Comment by particlebanana** [comment]
I'm not sure I follow this. Can you expand on what you are asking or give a full example?

**Comment by dbkaplun** [comment]
Absolutely! I want to query my DB using `.find()`, but with an added column `computedColumn` that might contain the result of `CASE WHEN user.id = 1 THEN 2 ELSE 3 END` and have it returned in the result set. I was thinking of something like this:
```js
User.find({select: ['computedColumn'], where: {
  createdAt: {'>=', new Date()},
  computedColumn: {raw: 'CASE WHEN user.id = 1 THEN 2 ELSE 3 END'}
}});
```
Does that make more sense?

**Comment by dmarcelino** [comment]
Something like `raw: 'CASE WHEN user.id = 1 THEN 2 ELSE 3 END'` makes sense for SQL adapters but how would this feature be translated for NoSQL adapters such as MongoDB or Redis? Any ideas?

**Comment by devinivy** [comment]
Mongo: an object to merge into `$sort` maybe.  Redis: not applicable?  @dmarcelino maybe this could be an adapter `feature`.

**Comment by particlebanana** [comment]
This is pretty close to just writing a native query. As long as we have a nice way to turn data returned from a native query into a Waterline model I think we are good. Right now `new User._model()` seems to work fine.

**Comment by dbkaplun** [comment]
I disagree the decision to close this ticket. Right now, I have to copy the very long query that Waterline generates and use `Model.query`. As fields are added to the model and its associations, this becomes less and less scalable. This feature would not break backwards compatibility and would add significant power to Waterline.
