### ISSUE TITLE
Is there any way to determine the SQL of a query before executing?

### ISSUE THREAD

**Issue by dbkaplun** [balderdashy/waterline#1108]

**Comment by devinivy** [comment]
Which adapter?  I know sails-mysql has a logging option via environment variable `LOG_QUERIES` which can be enabled.

**Comment by dbkaplun** [comment]
I'm using `sails-postgresql`. Ideally I could intercept the query before it was run, modify it, and then execute it.

**Comment by devinivy** [comment]
There's no way to do that using sails-postgresql.  Sounds like you'd want a wrapper to the node-mysql module, or to see if that module has such options.  Closing– can reopen if you have further questions, though.
