### ISSUE TITLE
MongoDB, groupBy with limit and skip

### ISSUE THREAD

**Issue by lukaszpaczos** [balderdashy/waterline#1109]
Hi,

It's possible to limit records grouped by something?

I tried all combinations of:

Model.find({
                    groupBy: ['order'],
                    sum: ['count'],
                    limit: 2,
                    skip: 20
                });

Model.find().groupBy('order').sum('count').limit(2)

And for all cases i always got all records :/

Cheers

**Comment by dmarcelino** [comment]
Hi @lukaszpaczos, would you mind submitting failing tests to waterline-adapter-tests [groupBy.modifier.test.js](https://github.com/balderdashy/waterline-adapter-tests/blob/master/interfaces/queryable/modifiers/groupBy.modifier.test.js)?

**Comment by dmarcelino** [comment]
Closing this as inactive, please re-open if you feel differently.

**Comment by ckken** [comment]
some problem

**Comment by ckken** [comment]
same problem
