### ISSUE TITLE
SQLite Adapter

### ISSUE THREAD

**Issue by tymat** [balderdashy/waterline#1111]
It's 2015 and still no SQLite3 support.

**Comment by randallmeeker** [comment]
Its 2015!!! Why doesn't anyone tell me these things!!!!!!

Adapters are community supported. There looks like there was one that was started a while back out there. You could ping them and see if you could work on updating theirs. 

https://github.com/AndrewJo/sails-sqlite3

**Comment by tymat** [comment]
https://github.com/AndrewJo/sails-sqlite3/commits/master  

Seems like the last commit was 2013.  Did he died?

**Comment by randallmeeker** [comment]
I don't know. Why don't you ping that repo and find out. Or you could start fresh. Waterline has come along way since 2013.

**Comment by blah238** [comment]
A bit OT but [Bookshelf](https://github.com/tgriesser/bookshelf)/[Knex](https://github.com/tgriesser/knex) works great with SQLite3, PostgreSQL, etc. I have written my own `orm` and `blueprints` hooks to use those instead of Waterline and its adapters. Unfortunately they are not open-source at this time, but they weren't that hard to make.

**Comment by tjwebb** [comment]
> It's 2015 and still no SQLite3 support.

It's 2015 and Waterline is still an open-source project that is supported by the community. As @randallmeeker mentioned, adapters are community-built and community-supported. If it doesn't exist, that means there hasn't been sufficient community interest in building it.

I recently re-wrote the postgres adapter using knex.js, which supports SQLite3: https://github.com/waterlinejs/postgresql-adapter. Maybe you can use some of those ideas to build a SQLite adapter.

**Comment by tjwebb** [comment]
https://github.com/waterlinejs/sqlite3-adapter

**Comment by dmarcelino** [comment]
Great work @tjwebb :clap:
