### ISSUE TITLE
defaultsTo: function()

### ISSUE THREAD

**Issue by tcf909** [balderdashy/waterline#1112]
I'm using an instance of sails 0.11 and have found that defaultsTo: function() { return 'whatever'; } doesn't work. The result is no property being saved to the database. If I change the line of code to defaultsTo: 'whatever' the property is saved to the database with the value 'whatever'.

Waterline version: "0.10.26",

**Comment by tcf909** [comment]
Nevermind. Apologies for the bad report. It has something to do with the way I'm extending classes getting rid of the defaultsTo: methods.

**Comment by devinivy** [comment]
Ah, no worries!  Thanks for letting us know.
