### ISSUE TITLE
Association Properies

### ISSUE THREAD

**Issue by stuk88** [balderdashy/waterline#1117]
Hi
I would like to ask for a feature to add more properties to the join table / relationship connection(in graph DB)
like, date of creation of the association, and custom properties.
how do i do that?

```
{
   attributes: {
   car: {
       collection: 'Driver',
       via: 'id',
       properties: {
              dateCreated: 'date',
              driver_type: {
                  enum: ['a','b','c']
              }
       }
   }
}
```

**Comment by devinivy** [comment]
This seems to fall under 0.11.x-scheduled feature of through associations.  That has an active issue at #705, so I'm closing this as a duplicate.  If there's some specific concern you have that isn't covered by #705, I'll be happy to continue the conversation here.

Also, you may try-out through associations per my comment: https://github.com/balderdashy/waterline/issues/705#issuecomment-60945411.
