### ISSUE TITLE
WLValidationError obscures the original error

### ISSUE THREAD

**Issue by kevinburkeshyp** [balderdashy/waterline#1119]
This is confusing, because for any other type of error, you can get the useful information by reading `err.originalError`, except certain types of uniqueness constraints, which don't persist this information.

**Comment by dmarcelino** [comment]
Hi @kevinburkeshyp, is this the same as balderdashy/sails-postgresql#179 / PR balderdashy/sails-postgresql#180 or does this problem requires changes in waterline core?

**Comment by kevinburkeshyp** [comment]
It depends on the library I believe... at least for `sails-postgresql` the original error never makes it to Waterline so nothing could be done about it in core

**Comment by dmarcelino** [comment]
OK, should we close this issue and focus on balderdashy/sails-postgresql#179 / other adapters then?

**Comment by kevinburkeshyp** [comment]
Sure

**Comment by dmarcelino** [comment]
Thanks
