### ISSUE TITLE
Bug? Too many association created after model.update(ID,{...}) 

### ISSUE THREAD

**Issue by misterch0c** [balderdashy/waterline#1123]
I have a one to one association as described in the waterline doc:
```
    //in partie.js
            score: {
            model: 'score'
        },
    //in score.js
        partie: {
            model: 'partie'
        },
```
And I call this function which create a score and associate it to a partie at some point:
```
    function addScore(partie_id, rez){
    console.log("caaaaaaaaaaaaaaaaled");
    console.log(partie_id);
    Score.create({array:rez, partie:partie_id}).exec(function(e,score){
        Partie.update(partie_id,{score:score.id}).exec(function(err,data){
            console.log("add scooooore");
        })
    });}
```
So this should only create an association for the partie corresponding to the partie_id but it does create associations for ALL parties. I see the console.log only once so I'm sure this function is only called once. 
Any idea what could be happening here?
It's strange because if I open robomongo I see only the right partie has a score. But if I make a find in my code or check the blueprint then they're all there.

**Comment by devinivy** [comment]
Which adapter (sails-mongo?) and version of waterline are you using?  I'd also like to see your `find` calls and/or relevant parts of your model definitions, since it sounds like the correct association has been created in the DB.

**Comment by misterch0c** [comment]
Yes, sails-mongo. I'm using sailsjs v 0.11. Waterline is version 0.10.17
I created a gist with my complete model and all the code involved. https://gist.github.com/misterch0c/a139365abd9eca5e4918 I put the result for 2 parties to be short but if I have 50 it will update the 50.
And just in case, I know that the partie_id is hardcoded in calculateScore. I use it that way to debug. So if I delete all score from the db and remove the association from the partie. After I call calculatescore with the hardcoded partie_id and all the parties are updated with the association
Thanks for your help

**Comment by particlebanana** [comment]
If you specifiy a valid criteria object it should work. In update only sending in an id key isn't valid.

```javascript
User.update({ id: '55d4a28aa62473ce7dd9dfb5' }, {
    pet: pet.id
})
```
