### ISSUE TITLE
Model.find({ where: { age: { '<': 30 } }, select: ['name'] })  is no work

### ISSUE THREAD

**Issue by ckken** [balderdashy/waterline#1125]
has any option when i haven't set?

**Comment by dmarcelino** [comment]
Are you using sails-mongo? From https://github.com/balderdashy/waterline/issues/1059#issuecomment-112361427:

> Sails-mongo did not support select until recently (balderdashy/sails-mongo#281), a fix has been made and it will go out in the next release (v0.11.3 I believe).

**Comment by ckken** [comment]
yes

**Comment by ckken** [comment]
i want ask when the next version publish

**Comment by dmarcelino** [comment]
@particlebanana, @devinivy, we've seen this issue popping up some 4 times now... is there anything preventing us from releasing sails-mongo v0.11.3?

**Comment by particlebanana** [comment]
@dmarcelino haven't looked at it but if theres a patch that needs to be published and the tests are passing we can publish it.

**Comment by dmarcelino** [comment]
Looking at the sails-mongo [commits since last release](https://github.com/balderdashy/sails-mongo/compare/v0.11.2...master), the `select` seems to be the only change. I think it's worth releasing since we had some 4 issues open due to this. @devinivy, any concerns?

**Comment by devinivy** [comment]
That sounds good.  The mongo adapter has had a fair amount of issues recently– any other low-hanging fruit we can expedite into the release?
