### ISSUE TITLE
Filter by array?

### ISSUE THREAD

**Issue by wayne-o** [balderdashy/waterline#1128]
Guys, I have a Message model which has a Tags (array) property - say I want to pull out all messages with the "test" tag - how would I do this through the REST API?
Or if that's not possible, and I need to create a specialised endpoint, how would I achieve this using the query language?

**Comment by wayne-o** [comment]
No one able to help?

**Comment by atiertant** [comment]
if you have a many to many relation on message and tag,you could do something like that: 

`tag.findOne(label: 'test').populate('messages');`

**Comment by wayne-o** [comment]
Unfortunately this is just an array property on the model...

I'm a bit surprised this hasn't been considered to be honest

**Comment by atiertant** [comment]
give your model definition please

**Comment by wayne-o** [comment]
//Message.js:

```
module.exports = {
  connection: 'somePostgresqlServer',
  attributes: {
    user: {
      model: 'user'
    },
    campsite: {
      model: 'campsite'
    },
    message: {
      type: 'string'
    },
    originatingIp: {
      type: 'string'
    },
    userAgent: {
      type: 'string'
    },
    comments: {
			collection: 'comment',
			via: 'message'
		},
    tags: {
      type: 'array'
    }
  },
  processTags: function(message){
    var m = message.message.match(/#\w+/g);
    message.tags = m;
    return message;
  },
  beforeCreate: function(newlyInsertedRecord, cb){
    newlyInsertedRecord = this.processTags(newlyInsertedRecord);
    cb();
  }
};
```

//Comment.js

```
module.exports = {
  connection: 'somePostgresqlServer',
  attributes: {
    comment: {
      type: 'string'
    },
    originatingIp: {
      type: 'string'
    },
    userAgent: {
      type: 'string'
    },
    user: {
      model: 'user'
    },
    message: {
      model: 'message'
    },
    tags: {
      type: 'array'
    }
  },
  processTags: function(record){
    var m = record.comment.match(/#\w+/g);
    record.tags = m;
    return record;
  },
  beforeUpdate: function(newlyInsertedRecord, cb) {
    newlyInsertedRecord = this.processTags(newlyInsertedRecord);
    cb();
  },
  beforeCreate: function(newlyInsertedRecord, cb){
    newlyInsertedRecord = this.processTags(newlyInsertedRecord);
    cb();
  }
};
```

**Comment by devinivy** [comment]
We could turn this into a feature request.  If anyone wants to implement it on the adapters, which would be non-trivial in most cases, that would be great.  You can try using `contains: 'test'` for your criteria, but to ensure that it works, you'd have to become familiar with your adapter's implementation of `contains`.  Which adapter are you using?

**Comment by wayne-o** [comment]
postgres adapter

**Comment by atiertant** [comment]
@devinivy don't know how array and json are implement in waterline but if they are just specific string,it could be implement directly in waterline

**Comment by wayne-o** [comment]
It comes into the db as "['string, 'string']" if that helps?

I.e. the field materializes as a string - the value a serialized JSON string

**Comment by atiertant** [comment]
@wayne-o the question is who stringify the array : the adapter or waterline ...

**Comment by devinivy** [comment]
The adapters are responsible for serializing the json, then waterline will attempt to unserialize it from a string if the adapter doesn't do so.

**Comment by atiertant** [comment]
@wayne-o an other solution would be to add a other string attibute with a columnName that point to the array column and use string contain value with quote.

**Comment by wayne-o** [comment]
Would I be better off using a Tag table or just having the tags as a string?

**Comment by devinivy** [comment]
A tag table is more complex but more flexible.  It will work better for the types of queries you're trying to make if you're going to use a relational database like postgres that doesn't have the idea of a "tag" built into it.

**Comment by atiertant** [comment]
it depends of what you need in your aplication,i think using a tag table with unique label is better.

**Comment by wayne-o** [comment]
OK - I will look to using a table :/
