### ISSUE TITLE
How can I listen a record update event?

### ISSUE THREAD

**Issue by cage1618** [balderdashy/waterline#1129]
Now, I want listen a event when a record has been updated?

**Comment by devinivy** [comment]
You can make an event emitter and add it into the beforeUpdate or afterUpdate collection lifecycle callbacks if you'd like!  But waterline does not currently have an eventing system.  See https://github.com/balderdashy/waterline-docs/blob/master/models/lifecycle-callbacks.md#callbacks-on-update

Going to close this, but we can carry on the conversation if you'd like!

**Comment by gaurav21r** [comment]
@devinivy Shouldn't this be done using `PubSub` in the Adapters?
https://github.com/balderdashy/sails-docs/blob/0.9/adapter-specification.md#pubsub-interface

**Comment by devinivy** [comment]
@gaurav21r sails achieves this with a "sails hook", but waterline doesn't have any such functionality itself.  @cage1618 if you're using sockets with sails and need to notify a client of changes to a record, you might want to look into pub/sub as @gaurav21r suggested.
