### ISSUE TITLE
Are there any plans for implementing connection to InfluxDB, opentsdb or other Time Series DBs?

### ISSUE THREAD

**Issue by 9minds** [balderdashy/waterline#1130]
Are there any plans for implementing connection to InfluxDB, opentsdb or other Time Series DBs?

**Comment by devinivy** [comment]
There are no plans that I know of to create an official adapter for a time series database, but I can happily point you the right direction to create a community adapter if you'd like!  A good place to start looking is here: https://github.com/balderdashy/sails-generate-adapter
