### ISSUE TITLE
Error: READONLY You can't write against a read only slave.

### ISSUE THREAD

**Issue by luigonsec** [balderdashy/waterline#1135]
Hi! I'm using waterline to query a Redis DB. The problem is that this DB is slave of other, and I don't need to write anything on it. When I run sails.js, I get this error:

Error: READONLY You can't write against a read only slave.

I think that Waterline is trying to write something inside Redis. I think this beacause I have already seen information written by Waterline, and I would like to avoid this. 

Could you help me?
Thanks a lot!

**Comment by devinivy** [comment]
Hey there!  I have a few questions.

1. Are you using the sails-redis adapter?
2. Can you post your connection configuration?
3. Do you have a reason to believe this is an issue with Waterline rather than the adapter you're using?
4. Specifically what Waterline call are you making that you expect to read and not write to the redis store?

**Comment by luigonsec** [comment]
Hi devinivy, thanks for you attention.

I have the code on my proffesional computer and now I'm at home, so there are things that I can't answer. 

First off, I would say that is an issue with waterline because I have launched my app against a Redis which was not slave of any one and works fine. But now, I launch the app against a slave and I get the error. Well, I have to say that the main proof is that in the first Redis appeared a key like "waterline:sequences:..." And I think this what

**Comment by luigonsec** [comment]
(Sorry I sent by error)

I think that these key is what waterline is trying to write in the Redis that is slave of other. Have you information enough ? I will post whatever you need tomorrow.

Thanks a lot

**Comment by particlebanana** [comment]
Waterline will only write when you start your app if your `migrate` setting is set to `drop` or `alter`. In this situation you should turn off migrations by setting `migrate: 'safe'`.
