### ISSUE TITLE
Custom  adapter mixed response

### ISSUE THREAD

**Issue by sajov** [balderdashy/waterline#1136]
I'am working on a solr adapter and looking for a way to use a mixed response with docs , count, facet, spellcheck and so on.

How can i Return this Mixed results to that model?
Using the custom method "query" can handle that. I was just thinking about a smarter way.
Any guesses are welcome

**Comment by particlebanana** [comment]
It won't pass any of the Waterline test if you return anything other than the records. 

You are free to make adapters that return anything for your own use though! It just won't be plug-and-play if you have a codebase working on an existing adapter.
