### ISSUE TITLE
.save() returns undefined is not a function

### ISSUE THREAD

**Issue by CiscoKidxx** [balderdashy/waterline#1139]
Gist can be found here:
https://gist.github.com/CiscoKidxx/bc9b08afc89f6bcfcb4d

Error is indicated at line 84. "Undefined is not a function"

I know user is defined. If I console log user right before the save command, it has data.

Let me know what else is needed to look at this.

**Comment by CiscoKidxx** [comment]
![capture](https://cloud.githubusercontent.com/assets/12367476/9725713/2c0a1b00-55ae-11e5-960e-323bc7a310a4.PNG)

**Comment by devinivy** [comment]
Can you specify the version of waterline you're using?

**Comment by CiscoKidxx** [comment]
Yes sorry: "waterline": "~0.10.17"

**Comment by devinivy** [comment]
Ah, please start by ensuring you have the latest patch version– 0.10.25.

**Comment by CiscoKidxx** [comment]
Installed 0.10.26 just now and same issue.

**Comment by devinivy** [comment]
Ah, I think I may see it.  Change [line 77](https://gist.github.com/CiscoKidxx/bc9b08afc89f6bcfcb4d#file-usercontroller-js-L77) to use `findOneById` rather than `findById`.  I think your `user` is an array.

**Comment by CiscoKidxx** [comment]
Dead on man. Thank you.
