### ISSUE TITLE
$regex operator

### ISSUE THREAD

**Issue by erick2014** [balderdashy/waterline#1146]
sup guys, im trying to implement a query like this, usin waterline orm,

.find({"name":{$regex:'lam'} })
    .exec(function(err,seller){
      if(err){
        res.send(err);
      }else{
        console.log(seller);
        res.send(seller)
      }
    })

But it doesnt find nothing, if i try this, instead:

.find({ $and:[ {"rol":"salesMan"},{"name":/lam/} ] })

it works, but i dont know how to pass the /lam/ as parameter, for example:
var queryCriteria="/"+req.params.name+"/";

.find({ $and:[ {"rol":"salesMan"},{"name":queryCriteria} ] })

thx in advanced!

**Comment by erick2014** [comment]
I have found a soultion, I dont know if it is the best one, but works:

.find({  $and:[ {"rol":"salesMan"},{"name":{contains:req.params.name}} ]  })

**Comment by particlebanana** [comment]
Neither of these are valid Waterline queries. It appears you are using Mongo and the query is being passed straight through to the mongo driver. If you would like to use the native mongo driver you can use the `.native` method in sails mongo.

You could do something like the following using Waterline:

```javascript
.find({
  rol: 'salesMan',
  name: {
    contains: 'mike'
  }
})
```

**Comment by erick2014** [comment]
It worked perfectly, thanks buddy, I appreciate your help!
