### ISSUE TITLE
Model instance looks like undefined

### ISSUE THREAD

**Issue by shaunc** [balderdashy/waterline#1149]
In nodejs debugger repl, my Model instance seems to be undefined:

    > newInstance
    undefined

However, it is in fact a model instance:

    > newInstance.toObject()
    { id: '8749',
      type: 'folder',
      name: 'baz',
      path: '/baz',
      parent: '8746' }

I'm not sure what is happening... `newInstance.toString()` returns `'[object Object]'` and `newInstance.valueOf()` returns newInstance.

This is quite annoying while debugging, as I have several times tried to chase down bugs because some value is undefined when it isn't. Any suggestions on how to fix?

**Comment by particlebanana** [comment]
I can't find anything wrong with Waterline testing this out. If you create a variable outside the callback and then assign a value to it inside the query callback it's undefined after but inside the callback it's good. You can also access it after assigning it to `sails.myTestInstance` so I think it's more the repl having aggressive garbage collection or something. If you track it down to something in Waterline re-open this with the findings but I can't find any issues with Waterline here.

**Comment by shaunc** [comment]
NB the statements above were in order: -- ie if you type `newInstance` by itself returns undefined, then immediately afterwards `newInstance.toObject()` returns the object content. So it isn't "repl having aggressive garbage collection" it is much more probably connected to "toString"... (or toValue() ...?)

perhaps you could point out where "toString()" is defined in Waterline? (It would be nice if it were overrideable, btw)
