### ISSUE TITLE
string primaryKey is always length:255

### ISSUE THREAD

**Issue by Wizzercn** [balderdashy/waterline#1150]
id: {
type: 'string',
primaryKey: true,
size: 100
},

in database :
varchar(255) NOT NULL

**Comment by devinivy** [comment]
This is not a waterline-specific problem since the adapters are responsible for the actual table definitions– could you please open an issue with the relevant adapter?

**Comment by RWOverdijk** [comment]
@Wizzercn You're right and we're sorry for that. I've moved the issue to [the relevant adapter](https://github.com/balderdashy/sails-mysql/issues/251) and also submitted [a fix for the problem](https://github.com/balderdashy/sails-mysql/pull/250), so the wheels are in motion.
