### ISSUE TITLE
.query undefined

### ISSUE THREAD

**Issue by granteagon** [balderdashy/waterline#1151]
In sails console, I should be able to:

User.query("SELECT * FROM USER")
But I get undefined is not a function, meaning .query is undefined.

I've reinstalled/updated sails and waterline, as well as sails globally and I still get the same error.

Thanks!

**Comment by devinivy** [comment]
Which adapter are you using?  The query method would be implemented at the adapter level.

**Comment by granteagon** [comment]
Thanks, I’ll check with sails-postgresql then.

/ Grant
