### ISSUE TITLE
Many-to-many Self referencing creates 2 Tables

### ISSUE THREAD

**Issue by KeKs0r** [balderdashy/waterline#1152]
Hi,

I don't know what I am doing wrong, I also googled this, but did not find a solution. I have a user model, that allows following and being followed by other users:

```javascript
    attributes: {
        following: {
            collection: 'user',
            via: 'follower',
            dominant: true
        },
        follower: {
            collection: 'user',
            via: 'following'
        },
}
```

This model ends up in 2 tables:
user_follower__user_following
user_following__user_follower

And also If I e.g. add a user:
```javascript
me.following.add(otherID);
me.save(function(err,res){
    User.find(me.id)
            .populate('following')
            .exec(function(err,res){
                    expect(res.following).array().length(1) // <-- but this is actually empty
            });
})
```

**Comment by mikermcneil** [comment]
Thanks for posting, @KeKs0r.  The issue queue in this repo is for _verified bugs_ with documented features only, please;  no feature requests, questions, or commentary-- and also no bug reports about undocumented features or unofficial plugins.  Please review our [contribution guide](https://github.com/balderdashy/sails/blob/master/CONTRIBUTING.md) for our process for feature requests and questions.

Thanks so much for your help!
