### ISSUE TITLE
Calling destroy method with empty array of ids removes all documents

### ISSUE THREAD

**Issue by gongxiancao** [balderdashy/waterline#1159]
I have a web server built with sails 0.10.5 + waterline 0.10.26 + sails-mongo 0.10.6.
The case is:
```js
    async.series([
      function (done) {
          Notification.create({
            name: 'test'
          }, done);
      },
      function (done) {
          Notification.destroy({id: []}, done);
      }], _.noop):
```
I assume the destroy call will do nothing, but it removed the documents created in the first step.
Not sure if this issue happens on the latest release.

**Comment by devinivy** [comment]
Which adapter are you using?

**Comment by devinivy** [comment]
Okay, step one will be to look at the original and parsed criteria used to destroy the records here: https://github.com/balderdashy/sails-mongo/blob/master/lib/collection.js#L268

Does the `done` callback correctly receive an array of all the records that were destroyed?

**Comment by gongxiancao** [comment]
Yes, the done callback received all the documents, and the collection is cleared.

And, at https://github.com/balderdashy/sails-mongo/blob/master/lib/collection.js#L254
The criteria argument is {}.

**Comment by dmarcelino** [comment]
We should cove this in our API tests, somewhere in: [waterline-adapter-tests - destroy.js](https://github.com/balderdashy/waterline-adapter-tests/blob/master/interfaces/semantic/destroy.js).

**Comment by particlebanana** [comment]
A criteria of `{}` will match all records. We need to add something so that if it comes across an empty `IN` criteria as the only item to exit the query with no results rather than try and mangle the query.

**Comment by particlebanana** [comment]
Added https://github.com/balderdashy/waterline-adapter-tests/commit/00278fcefce0cbbbf07564f178009f03462cd201 to the test suite. I couldn't recreate this in any of the adapters. I'll give it another run through though.

**Comment by particlebanana** [comment]
Tested in mongo with the code block above and it kept the records. Calling this one closed.
