### ISSUE TITLE
How to show SQL script?

### ISSUE THREAD

**Issue by Wizzercn** [balderdashy/waterline#1161]
I would like to ask how to print the execution of the SQL script?

console.log()  or  sails.log()...?

Mysql...

**Comment by devinivy** [comment]
On the current version of the sails-mysql adapter you can pass an environment variable `LOG_QUERIES=true` to log the queries to stdout.

**Comment by japel** [comment]
@devinivy do you think it could be possible to do this on waterline level, so its not up to the adapters to expose logging?

**Comment by devinivy** [comment]
We can't log SQL queries on the waterline-level, since waterline doesn't run those queries (the adapter does).  What we could do is create an adapter spec for logging low-level database instructions, then allow waterline to aggregate those logs in a way that's convenient for the developer.
