### ISSUE TITLE
How to customize the ManyMany/OneOne/OneMany table name

### ISSUE THREAD

**Issue by Wizzercn** [balderdashy/waterline#1162]
Automatically generated association table, table name is too long and not friendly, I would like to ask how to customize the table name, thank you.

now has table:
--
    sys_menu
    sys_role
    sys_menu_roles__sys_role_menus

i want :
--
    sys_menu
    sys_role
    sys_role_menu

model :
--
    menus: {
      tableName:'sys_role_menu',//可以不？
      collection: 'Sys_menu',
      via: 'roles'
    }

**Comment by devinivy** [comment]
You'll have to investigate use of through associations, which generally work but are not fully supported.  There's also some related issues to checkout if you want to know about history of this in the project: #725 #497 https://github.com/balderdashy/waterline-schema/issues/20 .  That last issue will be used to complete this feature.

Current use of through associations is outlined here: https://github.com/balderdashy/waterline/issues/705#issuecomment-60945411
