### ISSUE TITLE
Databases

### ISSUE THREAD

**Issue by kennetpostigo** [balderdashy/waterline#1164]
## Request
Hey, Waterline is amazing! I just wanted to request you guys make it usable for RethinkDB.

**Comment by devinivy** [comment]
There are two community adapters for rethinkdb:
https://www.npmjs.com/package/waterline-rethinkdb
https://www.npmjs.com/package/sails-rethinkdb

I'm not sure of the state of those adapters, but it looks like there's at least a good starting place.
