### ISSUE TITLE
Transformation should not be named json since it doesn't output json

### ISSUE THREAD

**Issue by aaronz8** [balderdashy/waterline#1167]
https://github.com/balderdashy/waterline/blob/master/lib/waterline/utils/transformations.js

Seems like it outputs stringified json rather than actual js object. I encountered the issue when trying to stream mongo data:

        mongoStream.on('data', function(d) {
          console.log(d);
        });

and kept on getting output:

    [{blahblahobject0}
    ,{blahblahobject1}
    ,{blahblahobject2}
    ,{blahblahobject2}]

rather than expected:

    {blahblahobject0}
    {blahblahobject1}
    {blahblahobject2}
    {blahblahobject2}

**Comment by aaronz8** [comment]
for reference, to get around this I used

        var mongoStream = this.models.someModel.stream(query, {
          write: function(model, index, cb) {
            cb(null, model);
          },
          end: function(cb) {
            cb(null);
          }
        });

**Comment by particlebanana** [comment]
@aaronz8 JSON is stringified in the spec. What you would like back is the actual javascript objects which you get in your override.
