### ISSUE TITLE
Can you set the Comment attribute on a field name in Postgres?

### ISSUE THREAD

**Issue by guyellis** [balderdashy/waterline#1172]
Is there a way to set the Comment attribute on a Postgres field when defining it in JSON?

I've tried without luck:

```javascript
attributes: {
		name: {
			type: 'string',
			required: true,
			comment: 'This is the user name'
		},
		...
}
```

**Comment by devinivy** [comment]
Hey, that's a great question.  You might want to file this question in the sails-postgresql repo.  That said, I don't _believe_ this is supported.  But it would be a nice feature to add!

**Comment by guyellis** [comment]
Thanks!
