### ISSUE TITLE
Access of collection objects(s) within adapter?

### ISSUE THREAD

**Issue by khkiley** [balderdashy/waterline#1174]
I just started looking at using Waterline with a SQL Server database. 

I immediately noticed that all columns in a table are returned in the record set, not just the columns identified on the model.

So I started looking into the SQL server adapter and saw that it submits a "SELECT * FROM [collection]".  I wanted to rewrite the adapter to perform a proper select with the specified columns. I quickly noticed that "collection" that is passed to the "find" method is a table name, and not a collection object. Furthermore, the collection, being the table name instead of the collection identity, would make it difficult to know what collection is being retrieved because a table may belong to more than one collection.

Are there any suggestions on how to grab the collection object that is associated with the request ?

Thanks,

Kurt

**Comment by particlebanana** [comment]
@khkiley look into using [waterline-sequel](https://github.com/balderdashy/waterline-sequel) for the adapter. It expands out select queries to only select columns it knows about. It's used in both the postgresql and mysql adapters.

**Comment by khkiley** [comment]
@particlebanana Thank you for the quick response. This looks very promising.

First question though, does waterline support multiple collections with the same table name ? 

I am doing some testing based on what I found in the postgres adapter and I am seeing inconsistent and mixed definitions for the collections when I define three collections with different column selections against the same table.

If I remember correctly, the documentation says the identity of the collections need to be unique, but the table name does not seem to have the same restriction. But it looks like the definitions are getting all glommed together.

Thanks,

Kurt
