### ISSUE TITLE
how to do counts 

### ISSUE THREAD

**Issue by chacliff** [balderdashy/waterline#1178]
Hi i've checked the waterline docs and not found any information on how to retrieve counts of queries. 
pet.find().where(breed: "terrier").then(function(dogs){
reply(dogs); 
}); 
so this would get all the dogs information that fits the bill but how can i just get the count of how many dogs fit this query without gathering all their data. This seems like a waste of resources to retrieve it all and then get a count of the array from an array object. 
This page lists count as a method but then doesn't supply an example. 
https://github.com/balderdashy/waterline-docs/blob/master/queries/query.md

Help with this would be greatly appreciated

**Comment by particlebanana** [comment]
```javascript
Pet.count({ breed: 'terrier' }).then(function(numOfDogs) {
///
});
```

**Comment by chacliff** [comment]
that would simply return all the dog documents with all the contents of each one stored in an array of dog. so then you would have to call numOfDogs.length. But would retrieving all this data not be tolling on a server to retrieve. This is in the event of 1000's of pets or 10,000's or even 100,000's or more? I am trying to confirm that numOfDogs would come back as a number 23, 1020, 10020. etc?

**Comment by devinivy** [comment]
In the example @particlebanana gave above, `numOfDogs` comes back as an integer.  Waterline will count these as efficiently as the adapter's `count` method.  If the adapter you're using does not have a `count` method, then waterline will `find` the records then count the array length.  There's a discussion about this over at #1142.

**Comment by chacliff** [comment]
oh i'm sorry i didn't see the part where it said "Pet.count" the syntax is so similar i missed the actual solution.
