### ISSUE TITLE
Checking values in database before allowing an update

### ISSUE THREAD

**Issue by Alaneor** [balderdashy/waterline#1181]
1. Let's say I have an existing User model saved in database.
1. Let's say I want this model's name to be updated to a new value, but only allow such update if the user's `suspended` attribute in database is not `true`.

**How do I achieve this?**

My approach so far has been to write a `beforeUpdate()` hook, but:

1. I don't know how to get the user's ID which is about to be updated (if there is any way)
1. I don't know how to obtain the model's current data from the database - the lifecycle callback only gets the properties to be changed.

Thanks for any guidance on this matter!

**Comment by particlebanana** [comment]
Update takes criteria. So you can do:

```javascript
User.update({ username: 'foo', suspended: false })
.set({ name: 'foo bar' })
.exec(/.../)
```

It will only update records that match the search criteria.

**Comment by Alaneor** [comment]
But if I do not have the user's ID, I have no way to ensure only that user ID will be updated.

For example, the update query

```js
User.update({ givenName: 'Robert', suspended: false }).set({ givenName: 'Trebor' })
// ...
```
might update one record or it might update thousands. But what I really want is to update only one record.

Note that I use Waterline with Sails.js and this particular case utilises the blueprints API. So in the above example, a user does an update to _/users/123_ and I want to update only that particular user.

Thanks for your help!

**Comment by devinivy** [comment]
I think I understand– in that case you'll have to do something like this,
```js
User.findOne({ givenName: 'Robert', suspended: false })
.then(function(user) {
  user.givenName = 'Trebor';
  return user.save();
})
.then(function(updatedUser) {
  // Voila
})
.catch(function(err) {/***/});
```

**Comment by particlebanana** [comment]
In the above example you have the user's id - 123.
