### ISSUE TITLE
Adds support for arrays on populate, like populate(['drivers','tickets'])

### ISSUE THREAD

**Issue by luislobo** [balderdashy/waterline#1191]
Guys, just FYI, I've added a new syntax for populate, so you can just write ```cars.populate(['drivers'], ['tickets'])``` instead of ```populate('drivers').populate('tickets')```
It's in PR #1190.

**Comment by particlebanana** [comment]
Cool!

**Comment by luislobo** [comment]
Let me know if it needs anything else

**Comment by luislobo** [comment]
merged already
