### ISSUE TITLE
Bad toJSON override breaks one-to-many associations

### ISSUE THREAD

**Issue by uncletammy** [balderdashy/waterline#1197]
Sails: v. 0.11.2
Waterline: v. 0.10.26
Adapter: only tested on sails-postgresql v.0.10.16

Overriding a model's `toJSON` method with a function that has no return value results in a partial failure populating associated model instances (on the many side).

For example: 

##### User.js
```javascript
module.exports = {
  attributes: {
    pets: {
      collection: 'Pet',
      via: 'owner'
    }
  }
};
```

##### Pet.js
```javascript
module.exports = {
  attributes: {
    owner: {
      model: 'User'
    },
    toJSON: function(){
    	console.log('I am inattentive!');
    }
  }
};
```

This will result in `Pet`s who's  `owners` can be populated but `User`s who's `pets` key have value `[null]` upon attempting to populate the field.

Obviously, people should write proper `toJSON()` overrides but I didn't expect this behavior therefore spent hours debugging.  @particlebanana, is this expected behavior? Should it throw? Should it use a private `toJSON()` method? If this is expected, I'll close this issue out and add a note to the docs.  Otherwise, let me know and I'll gladly submit a patch. :hankey:

**Comment by devinivy** [comment]
Nice find there.  I don't think that `toJSON` should be called on these records.  I think the place to look is here: https://github.com/balderdashy/waterline/blob/abd20f792d095a80655ce944839dfe7686d08c91/lib/waterline/model/lib/defaultMethods/toObject.js#L173-L174

I understand that when transmitting these associated records over the wire, you'd want the `toJSON` method to be used.  But that can be achieved in a different way.  Perhaps it could call `toObject` instead, and let the object returned by `toObject` inherit the model instance's `toJSON` method?  If objects within an object have `toJSON` methods, stringifying the parent object will call `toJSON` on the child objects.

**Comment by weyert** [comment]
Interesting. I agree that conversation to JSON is not something Waterline should care about. That's a framework/Sails issue. I would just return the model object to the framework which then can call toJSON()?

**Comment by particlebanana** [comment]
So the `toJSON` isn't anything special here. It's actually a part of `JSON.stringify`. So when you are overriding it you are overriding the function that will be called whenever `JSON.stringify` is used.

> If an object being stringified has a property named toJSON whose value is a function, then the toJSON() method customizes JSON stringification behavior: instead of the object being serialized, the value returned by the toJSON() method when called will be serialized. 

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify

It's probably best to use `.toObject` somewhere in you code and edit this value manually there.

**Comment by uncletammy** [comment]
He's like the Hercules of javascript only pi times sexier 

[]=={:::::::::::::>
