### ISSUE TITLE
Update() method and required fields

### ISSUE THREAD

**Issue by fernandofranca** [balderdashy/waterline#1206]
Am I missing the point or update() really needs an object with all of the "required" fields?

In this case I'm using sails-mysql adapter and sails 0.11.0.

I'm trying to update just some of the fields and the only way I could achieve it was:
1) obtaining the object and it's fields
2) modifying the object with the updated fields
3) update()

    TheModel.findOne()
      .where({ id: userId })
      .then(function (foundObj) {

        var updatedObj = foundObj;

        for(var k in updates){
          updatedObj[k] = updates[k];
        }

        TheModel
          .update({ id: userId }, updatedObj)
          .then(function (updated) {
            res.redirect('/admin/user/whatever');
          })
          .catch(function (err) {
              return res.redirect('/admin/user/whatever');
          });

      })
      .catch(function (err) {
        return res.redirect('/admin/user/whatever');
      });

**Comment by particlebanana** [comment]
Update will only update the values you send it. So if you are updating a required value and trying to null it out you will get an error. Otherwise you can update away. Can you attach a failing example?

**Comment by fernandofranca** [comment]
```
TheModel.
  .update({ id: userId }, updatedObj)
  .then(function (updated) {
    //nope
    return res.redirect('/admin/user/profile/success'); 
  })
  .catch(function (err) {
    //nope
    logError(new Error(err.originalError));
    return res.redirect('/admin/user/profile/failure'); 
  });
```

If ```updatedObj``` object is missing any of the required fields it will return nothing and will not throw nothing. In fact it will result in a timeout.

**Comment by fernandofranca** [comment]
I was wrong, this can be ignored.

My model's beforeUpdate method were missing its next() call. This is why no promises were fullfiled.

I am sorry.
