### ISSUE TITLE
are waterline have cli / terminal test like django orm?

### ISSUE THREAD

**Issue by wandyirawan** [balderdashy/waterline#1217]
hi.. some time i missing test / query on to cli like django.. are waterline have cli version to test query like django orm.. 

Thanks..

**Comment by devinivy** [comment]
Waterline doesn't have this feature.  If I need an interactive CLI to test my models, I add one to my application.  Sails has this out of the box, and hapi has a useful plugin called https://github.com/hapijs/reptile .
