### ISSUE TITLE
Update method updates all records if criteria parameter is undefined

### ISSUE THREAD

**Issue by ajkitson** [balderdashy/waterline#1226]
If the `update` receives `undefined` as the first parameter, it updates all records:

```js
sails> User.update(undefined, { name: 'test' }, function (err, users) { console.log(err, users.length) })
undefined
sails> null 206
```

Is this intended behavior? Based on [the docs](http://sailsjs.org/documentation/reference/waterline-orm/models/update) listing it as a required param, I would expect to get an error instead of updating all records. Feels a bit dangerous since passing undefined is likely a programming mistake.

**Comment by devinivy** [comment]
Version of waterline and adapter are you using?

**Comment by ajkitson** [comment]
Using waterline 0.10.26 and the postgres adapter 0.10.8

**Comment by particlebanana** [comment]
Thanks @ajkitson let's discuss in #1228

**Comment by prisonier** [comment]
And then results a HUGE memory leak

**Comment by mikermcneil** [comment]
For future reference, there's more information and tips on diagnosing memory leaks in Node apps, and on reproducing+reporting suspected memory leaks in Sails here: https://github.com/balderdashy/sails/issues/3782#issuecomment-238679052
