### ISSUE TITLE
How do I use counters? i = i + 1

### ISSUE THREAD

**Issue by whm0627** [balderdashy/waterline#1231]
Hi guys. I had been browsing the documentations and didn't find any guide of doing things like: 
Update 'user' set notificationNum = notificationNum + 1; 
Is there any way we can achieve this?

Sorry if I missed any duplicated requests.

**Comment by atiertant** [comment]
@whm0627 this is not supported for now,if you use an sql adapter you can use `query` method

**Comment by particlebanana** [comment]
Correct you will need to do a native query for this.
