### ISSUE TITLE
Waterline automatically update the entry after creation

### ISSUE THREAD

**Issue by pierreburgy** [balderdashy/waterline#1240]
Hi all,

I have a model 'user' with two relations (many-to-one and many-to-many).

The model 'user' as an attribute named 'password' (type string) which should contains the encrypted password of the user.

I use the lifecycle callbacks 'beforeCreate' and 'beforeUpdate' to encrypt the password:

```js
// Before create.
beforeCreate: function (user, next) {
  hashPassword(user, next);
},
```

```js
// Before update.
beforeUpdate: function (user, next) {
  hashPassword(user, next);
}
```

```js
function hashPassword(user, next) {
  if (user.hasOwnProperty('password')) {
    bcrypt.hash(user.password, 10, function (err, hash) {
      user.password = hash;
      next(err, user);
    });
  } else {
    next(null, user);
  }
}
```

```js
var params = {
  username: 'myName',
  email: 'contact@compamy.com',
  password: 'myPassword',
  myManyToOneRelation: [],
  myManyToManyRelation: []
}

let user = yield User.create(params):
```

When I create a new `user`, the `user` is `created` and then `updated`. So, the password is encrypted, saved, then encrypted again (from the previous crypt) and saved. So the user can not use it to login...

Do you have any idea why the `user` is updated after its creation?

Thanks in advance,

Pierre

**Comment by pierreburgy** [comment]
So, apparently this line is the reason of the issue : https://github.com/balderdashy/waterline/blob/master/lib/waterline/utils/nestedOperations/create.js#L61

Is it really needed ?

**Comment by pierreburgy** [comment]
Actually yes, it is needed for the 'add' function : https://github.com/balderdashy/waterline/blob/master/lib/waterline/utils/nestedOperations/create.js#L53

**Comment by sylvainlap** [comment]
+1

**Comment by pierreburgy** [comment]
Should I encrypt the password from the controllers...?

**Comment by particlebanana** [comment]
@pierreburgy the issue is coming from the following values that you are passing to the `create` method:

```javascript
myManyToOneRelation: [],
myManyToManyRelation: []
```

This is triggering the nested updates feature which goes through the flow above. It takes care of "syncing" all the associated values. We've spoke about it before and believe it's a bad feature that should be at least wrapped with a flag that can turn them off. In this case if you remove the collection association keys it won't hit the `.save` method.

**Comment by pierreburgy** [comment]
Thanks for your answer @particlebanana. I agree, and we must keep this feature which can be pretty useful, so a flag is a good idea.

In the meantime, I'm gonna use the controller to encrypt the password.

**Comment by devinivy** [comment]
@pierreburgy I've also seen people use `isHashed()` from https://github.com/davidwood/node-password-hash to deal with cases like this and avoid double-hashing.  I do my password hashing in waterline's `beforeValidate()`.

**Comment by pierreburgy** [comment]
Awesome @devinivy thanks a lot !

**Comment by devinivy** [comment]
@pierreburgy Oops– didn't mean to send you to a deprecated module!  I don't know if bcrypt has a similar `isHashed()`, but I'm sure there's something similar and up-to-date out there!

**Comment by sylvainlap** [comment]
https://github.com/davidwood/node-password-hash/blob/a7eb48c52118352a45a6ef8fb419f4efdbf58f07/lib/password-hash.js#L63

easy to implement with bcrypt. But if someone put 3 "$" in its plain password, this function will believe that it's a hash.

**Comment by devinivy** [comment]
Yeah, that's pretty lame!

**Comment by pierreburgy** [comment]
That's a shame, it would have been the best option...
