### ISSUE TITLE
auto generate model from mysql database

### ISSUE THREAD

**Issue by Name-less** [balderdashy/waterline#1244]
Hello, I would like to now if there is some tools in order to generate waterline models (with foreign keys, primary ...) from an existing mysql schema ? I am trying to do it my self without real success concerning foreign keys.
Thanks

**Comment by voycey** [comment]
I was just coming to open this ticket! Most of the larger frameworks have this ability, and as sails is pushing convention over configuration there shouldn't be a reason why it couldn't be done here.

There should even be the possibility of an "Auto schema" in the model whereby you don't have to define one at all, this keeps it lean and things agile and especially increases RAD.

You could give the choice of defining a schema or if no schema is available then one is produced from the database adapter (this seems the sensible place to put it as often it will be database specific how you produce this information).

**Comment by particlebanana** [comment]
Would love to see a [proposal](https://github.com/balderdashy/sails/blob/master/CONTRIBUTING.md#submitting-a-proposal) for what this would look like. If anyone wants to work that through and submit a PR for one that would be great.

**Comment by magicdawn** [comment]
FYI: https://github.com/sequelize/sequelize-auto for Sequelize

**Comment by servo1** [comment]
Here is a generator I originally created for waterline, a slight bit of modification and it will work.  It also covers foreign keys to implement owns (but requires some rewrite for waterline/sequelize).

https://github.com/servo1/mysqlAutoModels

**Comment by magicdawn** [comment]
And https://github.com/magicdawn/waterline-auto 😂
