### ISSUE TITLE
[Request] Changelog

### ISSUE THREAD

**Issue by moisesrodriguez** [balderdashy/waterline#1247]
Having a changelog would be much appreciated in case we want to upgrade our current version of Waterline. There could new features or something that behaves differently to previous version. Looking at commits It's pretty much impossible between releases tell what belongs where.

**Comment by particlebanana** [comment]
Done! [Changelog](https://github.com/balderdashy/waterline/blob/master/CHANGELOG.md)

**Comment by moisesrodriguez** [comment]
@particlebanana much appreciated
