### ISSUE TITLE
Suggestion to use MongoDB like query api

### ISSUE THREAD

**Issue by talamaska** [balderdashy/waterline#1251]
1. it looks weird when you type { '!' : value } or { '>' : value }
2. Better readability $gt, $gte, $not, $or
3. well known syntax
4. You already took from there find, update, exec, where, limit, skip etc
5. not too much of a change right? it's just strings that could be replaced
6. Possibility to extend waterline and put our own replacements, query keywords, methods etc

**Comment by particlebanana** [comment]
@talamaska we are not looking to switch up the criteria language that much anytime soon. Extending it sounds interesting though. Would you mind making a PR to the backlog section of the [Roadmap](https://github.com/balderdashy/waterline/blob/master/ROADMAP.md) to track this request?

**Comment by talamaska** [comment]
@particlebanana I guess it should be in Backlog? Who should I point as owner?

**Comment by particlebanana** [comment]
@talamaska you can skip the owner part
