### ISSUE TITLE
Implicit filtering(Joins)

### ISSUE THREAD

**Issue by girishla** [balderdashy/waterline#1257]
This feature request has been discussed in #597   before and has been closed without any proper resolution.  I wanted to create a fresh one explaining what we are missing out by not having it and hopefully pay the attention it deserves.

I think everyone will agree that Relational databases are still the data powerhouses of a vast majority of the Enterprise world. Even with mongodb,elasticsearch and the dozens of other NoSQL DBs, RDBMS's are here to stay. 
With that in mind, I'd like to point out that one of the most powerful features of enterprise systems built over traditional Relational databases is the ability to apply data visibility security rules applied implicitly through inner joins with 1:M and M:M tables.  This pattern can be seen in almost all the most successful ERP systems such as Oracle EBS, Peoplesoft, SAP and Siebel. 
Transactional data is logically partitioned by its association with a 1:M or M:M table and security slices/views are applied on it such as "My View", "My team View", "My Org View" etc etc. The security slice is nothing but an inner join to an 1:1, 1:M or M: M table. Needless to say, this way of logically partitioning data allows for massively scaling apps in the relational world.
This cannot be achieved with waterline ORM without resolving the issue raised by @RWOverdijk

So can we please please discuss this and take it fwd ?

**Comment by RWOverdijk** [comment]
I still like this idea :) I've been playing with a solution, but it's not final yet... Thanks for reopening this case @girishla.

**Comment by girishla** [comment]
Excellent. Looking fwd to it. I'm happy to help with tests etc if required.

**Comment by girishla** [comment]
One thing to be wary about is the effects of  the join cartesian product cardinality.

so considering your example....

`userModel.find({
    'firstName': { startsWith: 'a' }
    media: {type: 'avatar'},
    profile: {eyeColor: 'green'}
})
.populate('userMedia')
.populate('userProfile')
.exec(/** **/)`

If there are multiple media of type 'avatar' under the same User, you will get multiple instances of the User model due to the join cartesian product. So the cardinality must be handled somewhere. 

I know very little about the waterline codebase to help with the actual solution but I can contribute in other ways hopefully.

**Comment by girishla** [comment]
One thing to be wary about is the effects of  the join cartesian product cardinality.

so considering your example....

```

userModel.find({
    'firstName': { startsWith: 'a' }
    media: {type: 'avatar'},
    profile: {eyeColor: 'green'}
})
.populate('userMedia')
.populate('userProfile')
.exec(/** **/)

```

If there are multiple media of type 'avatar' under the same User, you will get multiple instances of the User model due to the join cartesian product. So the cardinality must be handled somewhere. 

I know very little about the waterline codebase to help with the actual solution but I can contribute in other ways hopefully.

**Comment by RWOverdijk** [comment]
You're right. And that's one of the things missing in the feature I added, allowing you to filter based on association criteria. However, this will probably result in fetching the many side, joining the one, and populating them as expected.

**Comment by girishla** [comment]
By "fetching the many side" if you mean sending a separate SQL for it, then it would be counter-productive wouldn't it? To me the main thing is the push-down to the DB as a JOIN to source else you'll end up shifting around a lot of data, no ?
The thing is I want to implement data-security at the datasource level and not pull in more data to the ORM than I need to

**Comment by RWOverdijk** [comment]
Well yes, but that's now how populate works. You want one source table, and many other values for it. Otherwise you'll end up fetching a lot more records for the many side (if you don't group the results). Which, sure, works... But isn't very optimal.

**Comment by girishla** [comment]
Sorry for not following up. Just back from holiday. 
This is increasingly looking like something I will have to implement by bypassing waterline. Do let me know of any progress you make with this. I'd still be interested.

**Comment by particlebanana** [comment]
@girishla @RWOverdijk would love to see a full [proposal](https://github.com/balderdashy/sails/blob/master/CONTRIBUTING.md#submitting-a-proposal) for what queries would look like with `innerJoins`.

I'm working a [new interchange query encoding](https://github.com/particlebanana/waterline-query-builder/blob/master/docs/syntax.md) that would support all types of joins. Would need to be worked out what that looks like in Waterline though. 

Ideally I would like to expose the various join types in a more explicit way than the syntax @RWOverdijk has in this and in #597. Submit this as a PR where a spec can be worked out.
