### ISSUE TITLE
how to define the element type of an array attribute?

### ISSUE THREAD

**Issue by ilaipi** [balderdashy/waterline#1258]
Hello, I'm new to sails, but I can't find any sample about this:

```
module.exports = {
    phone: {
        type: 'array',
        element: 'string',    //tell sails fill the array with string
    }
}
```

How can I do?  Thanks

**Comment by devinivy** [comment]
Are you trying to set a default value for the array?  You can use `defaultsTo`.
```
module.exports = {
    phone: {
        type: 'array',
        defaultsTo: function() {
            return ['string'];
        }
    }
}
```

**Comment by ilaipi** [comment]
@devinivy Thanks, but I think you have misunderstood me.

```
['string', 'string']
```
this is an string-array

```
[model, model]
```
this is an model-array

```
[1, 2]
```
this is an integer-array

so, when I define an attribute type `array`, how do you know what type of element I want to put into it?

**Comment by devinivy** [comment]
Oh, I understand now.  Waterline doesn't support typing arrays like you're describing.  You can, however, write a custom validator to be used on that attribute: https://github.com/balderdashy/waterline-docs/blob/master/models/validations.md#custom-validations

**Comment by ilaipi** [comment]
OK, I will try it.Thanks
