### ISSUE TITLE
Models inheritance

### ISSUE THREAD

**Issue by KirillSuhodolov** [balderdashy/waterline#1271]
Don't find information in docs.
Is it exists any way to implement models inheritance?

STI, MTI or just share same fields between different models. May be something like Rails Concerns

**Comment by particlebanana** [comment]
You can extend the model object with whatever properties you want, it a normal javascript object before it's instantiated. There isn't a specific way to go about model inheritance though. If you want models to share properties create a file with the attributes and extend the model definition using something like lodash's `_.extend`.

**Comment by KirillSuhodolov** [comment]
@particlebanana using _.merge with deep cloned another model throw waterline error

**Comment by particlebanana** [comment]
Hey @KirillSuhodolov can you post an example of what you tried? I was thinking along the lines of:

```javascript
// api/models/user.js
module.exports = _.merge({
  attributes: {
    age: 'integer'
  }
}, require('../utils/baseModel'));
```

```javascript
// api/utils/baseModel.js
module.exports = {
  attributes: {
    name: {
      type: 'string',
      required: true
    }
  }
};
```
