### ISSUE TITLE
E_VALIDATION regression bug

### ISSUE THREAD

**Issue by marcusnielsen** [balderdashy/waterline#1275]
After running npm install, suddenly we get `Error (E_VALIDATION) :: 1 attribute is invalid`

This seems to work and not work in Waterline 0.10.28.

Any new `npm install` will fail with our latest stable code.
I have a collegue who zipped up his node-modules-foler, and it works for me using that.

We solved it temporarily by running `npm shrinkwrap`, via the working copy of node_modules.

I then made a fix where the previous team had a row: ` var WLValidationError = require('../../node_modules/sails/node_modules/waterline/lib/waterline/error/WLValidationError.js');`; I now tried to install waterline 0.10.28 and do: ` var WLValidationError = require('waterline/lib/waterline/error/WLValidationError.js');`

Then I got the same error as above on an isolated test. 

I went into our project's waterline and did `npm shrinkwrap` and compared the results with the sails/waterline part of our project shrinkwrap. You can see the results here: https://gist.github.com/marcusnielsen/b390dd438a31989042a9 .

**Comment by particlebanana** [comment]
Hey @marcusnielsen sorry to hear that. What attribute validations are failing? We pushed a new version of Anchor (our validation library) not too long ago but there weren't any breaking changes. Can you post the validations you have set on that failing attribute?

**Comment by marcusnielsen** [comment]
Usually the consultant team made some custom validations like so:
```
var MasterClient = {
  // Enforce model schema in the case of schemaless databases
  schema: true,
  attributes: {
org_number: { type: 'string', required: true, beCountryCodeFormatted: true, uniqueIfNotDeleted: asyncValidations.uniqueIfNotDeleted },

// SNIP

types: {
    uniqueIfNotDeleted: function(org_number, result){
      return result;

    },

// SNIP

var asyncValidations = {
  uniqueIfNotDeleted: function(cb) {
    var id = this.id;
    sails.models.masterclient.find({org_number: this.org_number, deleted: {'!': true} })
    .exec(function(err, mClients){
      if(id){
        mClients = _.reject(mClients, "id", id);
      }
      return cb(_.isEmpty(mClients));
    });
  },
};
```
Error output: 

```
Invalid attributes sent to MasterClient:
 • org_number
   • "uniqueIfNotDeleted" validation rule failed for input: 'SE8765432123'
``` 
Stack trace: https://gist.github.com/marcusnielsen/05dc9267e68c8e1c97c5

Note that it happens when barrels runs. And as I said before, exactly the same project code works with the right node_modules structure, but not if we npm install without our current shrinkwrap.

**Comment by marcusnielsen** [comment]
I'm pinpointing the culprit by deleting node_modules and pasting the working ones from the shrink-wrapped folder. So far: 
* Barrels gave the same error.
* Sails gave no error.
* Sails/waterline gave no error.

I will move down the tree and keep trying to find the smallest unit that removes the error and then give you an update.

**Comment by marcusnielsen** [comment]
Changing sails to install `"waterline": "=0.10.28"` and running npm install works. 
=0.10.29 and =0.10.30 does not work.

**Comment by marcusnielsen** [comment]
So 0.10.28 does not include anchor. I guess sails does some magic fallback to include another anchor.

Including anchor from 0.10.29 into node_modules in 0.10.28 breaks our tests with above error.

Removing anchor from 0.10.29 node_modules makes our tests pass without the above error.

Is this sufficient info for you to work with?
Suggestions?

**Comment by particlebanana** [comment]
Anchor `0.11.0` was set in Waterline `0.10.29` so it sounds like that is it. It could be related to https://github.com/sailsjs/anchor/issues/102. I'm not quite sure whats going on with that custom definition but that issue on Anchor could be a start to your debugging.

**Comment by marcusnielsen** [comment]
Tried to fix `return cb(_.isEmpty(mClients));` to `return cb({valid: _.isEmpty(mClients)});`, and it now throws an error on the next async validator. So this should be easy to go through and fix. Thanks for the link! It saved our asses this time!

Off-topic: I read in sailsjs/anchor#102 that this is not the documented way for doing async validation. Then what is the documented way?

**Comment by mikermcneil** [comment]
@marcusnielsen thanks for the follow-up!

> Then what is the documented way?

@marcusnielsen @particlebanana Re documentation: custom validations are documented: http://sailsjs.org/documentation/concepts/models-and-orm/validations#?custom-validation-rules

That said, in the interest of being completely transparent on my personal opinions towards this feature and the way it affects the structure of a Sails app, I added some background on the topic [here](https://github.com/balderdashy/sails/issues/3425#issuecomment-171861331).

**Comment by marcusnielsen** [comment]
> [..]write complex custom validations using services or machines and calling those helper functions before updating or creating records[...]

These are the docs I'm looking for!

I actually had the discussion of going with lifecycle hooks to avoid multiple DB lookups during validation.
But the docs just list the hooks, and doesn't tell us the best place for custom async validations: http://sailsjs.org/documentation/concepts/models-and-orm/lifecycle-callbacks .

So the reasoning from us as a team was that custom validations via lifecycle hooks felt like an undocumented approach, and would be too risky in the long run. So to politely ask the question a bit differently: 

Is there a documented way of doing async custom validations? 

It doesn't even need to be official, just something to throw out to the team that's not my own interpretations of what's being said here. We all agreed on our current implementation being not-so-good.

**Comment by particlebanana** [comment]
@marcusnielsen not that I know of off the top of my head. To be honest I don't use custom validations so I'm not aware of pitfalls using them. 

For normal async validations there are some docs in [here](https://github.com/balderdashy/waterline-docs/blob/master/models/validations.md).

**Comment by marcusnielsen** [comment]
Summary of my perspective: Don't use the documented way of doing custom validations (above link provided by @particlebanana). 

Use lifecycle hooks. But that's undocumented, and doesn't seem to be able to access anything but values provided into the #beforeValidate(values, cb) method. See docs: https://github.com/balderdashy/waterline-docs/blob/master/models/lifecycle-callbacks.md

So we can close this bug, but I still don't know how to do validations in a good fashion.
