### ISSUE TITLE
Paginate multiple model [feature request?]

### ISSUE THREAD

**Issue by Oldwo1f** [balderdashy/waterline#1280]
Hi everyone.

I would like to render 2 models in the same page (Article and Event). But for that i need a way to paginate theses instances.
For exemple (3 item per page order by date DESC)
>page 1 :  1 article and 2 events
>page2 : 3 articles
>page 3: 2 articles 1 event

on page 2 i have to fetch article number 2,3 and 4 
on page 3 i have to fetch article number 5,6 and the event number 3

**Is there a way to achieve that with waterline ?** If not pass this issue as feature request.

**Comment by particlebanana** [comment]
Hey @Oldwo1f you can find the [paginate docs here](https://github.com/balderdashy/waterline-docs/blob/master/queries/query.md#paginate). I'm not sure what you mean by two models but the query logic would be the same.

**Comment by Oldwo1f** [comment]
I saw the paginate docs, but i didnt found my answer here.

Its like i want to  fetch all my **Articles** and all my **Events**, then put all these stuff in a single array, then sort it by date. and Then paginate the results.

i dont know if this is more explicit.

btw, thank for your anwser

**Comment by particlebanana** [comment]
So first to be aware you are going to lose all the the benefits of using paging if you are pulling your entire dataset into memory on each query. You will also probably crash your server eventually depending on the data size.

You can do this but it's outside the scope of what Waterline is responsible for. You will need to make the two queries, concat the array, sort it by some attribute and then slice off the records you want to send.

**Comment by Oldwo1f** [comment]
Yeah, i know this is a shitty solution, i does not want to do this....

Is there a waterline solution to do this?

If not, i ll probably have to store my article and my event in the same Model article, with one attribute that say if its an article or an event (but i ll lose the Validation prossess. . .)

I dont think i have a good solution to do this.

**Comment by tomercagan** [comment]
Hi, I know this might be late but I'd put in my solution to a similar problem in case others come here... 

We wanted to create a "timeline" of "event" of various types. We resolved it by creating a third model/table that links to the other ones. 

For example (sorry in case of sketchy syntax), Timeline.js:
```
module.exports = {
    schema: true,
    autoCreatedAt: true,
    autoUpdatedAt: true,
    autoPK: true,
    attributes: {
        type: {
            type: 'string'
        },
        event: {
            model: 'Event'
        },
        article: {
            model: 'Article'
        },
```

In `Event` and `Article` you can automatically add an instance of Timeline which is related to the original entity setting the required field. Alternatively, put all the logic for creating event/article in before/after create of a timeline entity (then you can possibly have one route).

Now you can use the `Timeline` model to do pagination according to whatever logic is required. You may want to add additional meta-data in `Timeline` schema for supporting whatever else is needed in your pagination.

Hopes this helps... I think it is more efficient than loading whole tables...
