### ISSUE TITLE
buildDynamicFinders use attribute names instead of column names

### ISSUE THREAD

**Issue by HaKr** [balderdashy/waterline#1290]
Would it not be appropriate to use the attribute names in the Dynamic Finder method names?

Now I have column names with table name repeated in it, plus they have underscores. In instances of a model, one can use friendly attribyte names, but for the findBy methodes one must fall back to the column name

**Comment by particlebanana** [comment]
@HaKr thanks, marking as a bug. Could you attach a quick test case? 

Also note in the future the dynamic finder methods will probably be deprecated but they will be around until a 1.0 release candidate more than likely.

**Comment by HaKr** [comment]
Thanks for the response.

Just curious what concept will replace the findBys. From Ruby on Rails I do
appreciate these

Regards
Op 28 jan. 2016 18:07 schreef "Cody Stoltman" <notifications@github.com>:

**Comment by particlebanana** [comment]
I haven't specced anything out yet but it will probably just be removed. The overhead of attaching functions to the model for each attribute just isn't worth the maintenance cost. These two are just too similar to keep both: `findByName('foo')` and `find({ name: 'foo' })`.

If you have a real use case that makes the first version better I would love to hear it though!

**Comment by HaKr** [comment]
I would say profiling, but foremost optimization.

findBy({}) has to parse the parameter each call and build the SQL from
there.

findByXXX() you can (possibly even through the singleton pattern) prepare
the statement [SELECT c1,c2...cn FROM table WHERE XXX like ':xxx'] and
cache that prepared statement.

2016-01-28 18:28 GMT+01:00 Cody Stoltman <notifications@github.com>:

**Comment by HaKr** [comment]
/**
 * Test Model dynamic finders to use attribute names instead of column names
 */


describe('Models must have Finders by attribute name, not by column name',
function() {
    var should = require('should');

    var User;
    var user;

    /**
     * Build a test model
     */

    before(function(done) {
var Waterline = require('waterline');
var sailsMemoryAdapter = require('sails-memory');
var waterline = new Waterline();

var userCollection = Waterline.Collection.extend({
   identity: 'user',
   connection: 'default',
   migrate: 'alter',
   autoPK: false,
   autoCreatedAt: false,
   autoUpdatedAt: false,
   tableName: 'HR.tbl_users',

   attributes: {
name: {
      type: 'string',
      columnName: 'USER_NAME'
    },
firstName: 'string',
migrate: 'safe',

   }
});

waterline.loadCollection(userCollection);

var config = {
   adapters: {
'memory': sailsMemoryAdapter
   },

   connections: {
default: {
   adapter: 'memory'
}
   }
};

waterline.initialize(config, function (err, ontology) {
   if (err) {
return console.error(err);
   }

   User = ontology.collections.user;

   User.create({ // First we create a user.
   firstName: 'Neil',
   name: 'Armstrong'
}).then(function (created_user) {
user = created_user;
}).catch(function(err){ // If any errors occur execution jumps to the catch
block.
   console.error(err);
}).finally(function(){
done();
});
});


    });

it('Models must have Finders by attribute name, not by column name',
function(){
User.should.have.property('findByFirstName').and.be.a.Function();
User.should.not.have.property('findByUSER_NAME');
User.should.have.property('findByName').and.be.a.Function();
});

it('The user instance must have the correct attributes', function(){

user.should.have.property('name');
user.should.have.property('firstName');
user.should.not.have.property('USER_NAME');
});

});


2016-01-29 9:20 GMT+01:00 Harry de Kroon <harry.de.kroon@gmail.com>:

**Comment by particlebanana** [comment]
Fixed in #1298
