### ISSUE TITLE
Support database schema names in models

### ISSUE THREAD

**Issue by HaKr** [balderdashy/waterline#1291]
We use Oracle. Like many other SQL databases, Oracle uses the concept of schemas. It would be very helpfull to be able to have support for this.

E.g.

Contracts table in A schema and Invoices table in B schema.

SELECT * from "A"."Contracts";

SELECT * from "B"."Invoices";

**Comment by particlebanana** [comment]
@HaKr I don't maintain any of the oracle adapters but we have [schema support](https://github.com/balderdashy/sails-postgresql#model-level-config) at the model level for the postgresql adapter. That might be something you could get the oracle maintainers to add.

Currently we don't have a per connection config in userland but it's something I'm actively working on for future versions of the project.
