### ISSUE TITLE
reuse validation logic in the browser?

### ISSUE THREAD

**Issue by divramod** [balderdashy/waterline#1292]
hey, 

i really like the waterline approach to unify database access.

i wanted to ask if it is possible to reuse the waterline validation logic in the browser, with for example react, to not have this part written two times for different environments.

or should i use node-validator and browseryfy it?

this would coincide with the DRY principle you implemented for the database access.

**Comment by particlebanana** [comment]
Hey @divramod the validation library used by Waterline is [Anchor](https://github.com/sailsjs/anchor). There was a build script at one point for it to work in the browser but I haven't actually used it on the front-end so I'm not sure of it's quality.
