### ISSUE TITLE
feature request: createOrUpdate

### ISSUE THREAD

**Issue by chacliff** [balderdashy/waterline#1299]
a lot of databases have this capability natively can we add support for this? 

your findorCreate function is nice, but you have no way of knowing whether or not you found or created so then you have to run a subsequent update after completion to ensure that the document is up to date. 
A feature such as createOrUpdate would solve this problem and enhance the community experience. 

model.createOrUpdate(  search criteria, [values, callback] )

**Comment by chacliff** [comment]
it appears this is probably being solved in https://github.com/balderdashy/waterline/issues/790
which i found while reading another issue that solves it. i think someone can confirm and close. my mentioned call above was a very simplified version that didn't need options and should of probably been name updateOrCreate.

**Comment by particlebanana** [comment]
`Upserts` are currently on the backlog section of the [Roadmap](https://github.com/balderdashy/waterline/blob/master/ROADMAP.md#pending-proposals) awaiting a formal proposal. If you would like to put one together that would be great!
