### ISSUE TITLE
Handshake inactivity timeout (MySQL)

### ISSUE THREAD

**Issue by ronenteva** [balderdashy/waterline#1305]
A website that is working fine for a long time, suddenly constantly getting:

    Could not connect to MySQL:
    Handshake inactivity timeout

Any idea what might be causing that?

**Comment by particlebanana** [comment]
Looks similar to [this](https://github.com/felixge/node-mysql/issues/1239) issue on node-mysql.

**Comment by particlebanana** [comment]
This issue was moved to balderdashy/sails-mysql#284
