### ISSUE TITLE
primaryKey selection should be a bit more decisive

### ISSUE THREAD

**Issue by kevinburkeshyp** [balderdashy/waterline#1308]
This code in lib/waterline/core/index.js

```javascript
  // Set the collection's primaryKey attribute
  Object.keys(schemaAttributes).forEach(function(key) {
    if (hasOwnProperty(schemaAttributes[key], 'primaryKey') && schemaAttributes[key].primaryKey) {
      self.primaryKey = key;
    }
  });
```

will choose the last column that has a `primaryKey` set to a truthy value and clobber any other values that have been set along the way. It seems like this could be a little better:

- if it's just going to choose the last one, you could loop backwards and then `break` when you get the first value
- if it's accidental, you could `break` after the first assignment to `self.primaryKey`
- if it's a bad input, you could abort if the user defines two primaryKey fields.

**Comment by particlebanana** [comment]
Ideally we would error out in the `schema` builder if it finds a collection that has two primary keys. The primary key definition is a bit misleading, obviously in the physical schema you can have composite primary keys, but Waterline needs some sort of unique attribute per record.

I am going to move this to [Waterline-Schema](https://github.com/balderdashy/waterline-schema) so we can track it there.

**Comment by particlebanana** [comment]
This issue was moved to balderdashy/waterline-schema#38
