### ISSUE TITLE
findOrCreate and afterCreate = bug ?

### ISSUE THREAD

**Issue by prisonier** [balderdashy/waterline#1309]
Hi,

I have exactly the same problem than in [issue 165](https://github.com/balderdashy/waterline/issues/165), the afterCreate function in my model is triggered even if the model already exists. 

In my controller
```javascript
Video.findOrCreate(videos).then(res.ok)
```

In my model
```javascript
  afterCreate: (values, next) => {
    console.log('post video on facebook : '+values.name)
    next()
  }
```

If I call my controller twice, I will have the whole array called videos printed twice.

Thanks for your help

**Comment by particlebanana** [comment]
@prisonier the `findOrCreate` method is not meant to be used with arrays. It will not detect each individual record in the find portion.

You will need to do individual calls to `findOrCreate` for each item in the array.

**Comment by prisonier** [comment]
@particlebanana thanks for your answer. 

Maybe I didn't understand the [doc](http://sailsjs.org/documentation/reference/waterline-orm/models/find-or-create) but I think it says that you can use an array with that function.
