### ISSUE TITLE
.count broken for booleans 

### ISSUE THREAD

**Issue by chacliff** [balderdashy/waterline#1312]
I am using a mongo adapter with waterline and trying to check an isActive flag in the database. It is always returning 0 no matter what value i put into the criteria for the boolean. 

The database has the document showing as 1 | 0, and when i do a command line.

`db.<database>.count({isActive})` 

it returns 1376745 on my particular db. 

i am currently getting around this by doing a native call with waterline. 

`<db>.native(function(err, collection){
    collection.count({isActive: 1}).then(function(err, results){
         console.log(results);
    }
});`

**Comment by mikermcneil** [comment]
@chacliff thanks for the report!  Would you mind providing more details about you Waterline version, the version of Node you're using, as well as the version of sails-mongo?

**Comment by chacliff** [comment]
node version 4.2.6
from my package.json file
waterline 0.11.0
sails-mongo 0.12.0

**Comment by particlebanana** [comment]
> db.<database>.count({isActive})

You need to use Waterline criteria syntax here:

```
db.<database>.count({ isActive: true });
```

**Comment by chacliff** [comment]
in hindsight i wish i put more specific info in here about where i was having this issue and the code that was failing. i'll be sure to do that better next time. thanks guys
