### ISSUE TITLE
"Saved Record" of instance method *.save() is always undefined

### ISSUE THREAD

**Issue by jianpingw** [balderdashy/waterline#1318]
I tested this on Waterline 0.11.0, with both disk and postgresql adapter.

`myModel.save(function(err, savedRecord) {
  // savedRecord is always null
});`

The .save() method indeed saves the change, however the "Saved Record" parameter of the callback function is always null.

According to the documentation (http://sailsjs.org/documentation/reference/waterline-orm/records/save) and example, we should get a Saved Record.

**Comment by devinivy** [comment]
This is actually a breaking change in 0.11 that you can find described here: https://github.com/balderdashy/waterline/releases/tag/v0.11.0

Feel free to open an issue in the waterline-docs repo if it is no longer up to date.

**Comment by jianpingw** [comment]
Thanks @devinivy. I will close this issue.
