### ISSUE TITLE
Creating an index on string attributes does not work

### ISSUE THREAD

**Issue by tyronedougherty** [balderdashy/waterline#1354]
**Waterline version**: 0.12.1
**Node version**: v5.4.1
**NPM version**: 3.3.12
**Operating system**: OS X El Capitan 10.11.5 

<hr/>

Hi guys,

When adding an index property to an attribute of type 'string', the value will not be indexed. Here's an attribute definition that I want to be indexed:
```
user: {
            type: 'string',
            index:true,
            notNull: true,
            required: true,
            uuidv4: true
        },
```
I'm using the `sails-redis` adapter, but no matter what I do I cannot get it to be indexed. Interestingly, it will index the primary key I've got, which I'd manually set to be a uuid (which is still a string):
```
id: {
            type: 'string',
            primaryKey: true,
            defaultsTo: uuid.v4,
            unique: true,
            index: true,
            uuidv4: true
        }
```

Has anyone got any idea why my string primary key will be indexed, but any other other string attribute can't be indexed?

Many thanks! 😄

**Comment by particlebanana** [comment]
I'm not sure how sails-redis handles indexing for arbitrary attributes (if it does at all). You can try asking over there. For adapters with auto-migrations they will get an index built when the migrations run.

**Comment by tyronedougherty** [comment]
sails-redis does appear to support indexes for arbitrary attributes.

Interestingly I discovered this in [the docs](https://github.com/balderdashy/waterline-docs/blob/master/models/data-types-attributes.md):

> There is currently an issue with adding indexes to string fields. Because Waterline performs it's queries in a case insensitive manner we are unable to use the index on a string attribute. There are some workarounds being discussed but nothing is implemented so far. This will be updated in the near future to fully support indexes on strings.

Is this still accurate @particlebanana ? If so, any ideas why, or if there are any workarounds being implemented in the near future?

Thanks again for your help I really appreciate it!
