### ISSUE TITLE
Model creation fails - waterline defaultsTo not working because of strict condition

### ISSUE THREAD

**Issue by xhallix** [balderdashy/waterline#1400]
**Waterline version**: 0.11.0
**Node version**: 5.10.1
**NPM version**: 3.8.6
**Operating system**: Windows 10

<hr/>

I'm updating my model from a simple form, where some not mandatory fields can be ommitted.
During a POST this defaults, for example for `square_meter` to `square_meter : ''``.

Since I've set those fields to `defaultsTo` I would expect the ORM to handle this.
Here is my model. 

MyModel.js

```
module.exports = {
    attributes  : {
       //... more code 
        additional_costs : {
            type: 'float',
            defaultsTo : 0.00
        },
        square_meter : {
            type: 'float',
            defaultsTo : 0.00
        },
        notes : {
            type: 'longtext'
        },
        updatedAt : 'datetime'
    }
};
```

In waterline `lib/waterline/query/dql/create.js` I found the rootcause in line 90 - 95

```
 for (var key in this.attributes) {
    if ((!hop(values, key) || values[key] === undefined) && hop(this.attributes[key], 'defaultsTo')) {
      var defaultsTo = this.attributes[key].defaultsTo;
      values[key] = typeof defaultsTo === 'function' ? defaultsTo.call(values) : _.clone(defaultsTo);
    }
  }
```

Should this not only check for undefined but also for an empty string?

Thanks for you opinion. If you like I can make a PR.

Best

**Comment by mikermcneil** [comment]
@xhallix To make sure I'm following you, you have: `defaultsTo: ''`, right?  That should totally work, as long as no value was provided for the corresponding attribute.  That is, the value must === undefined.  On create, `defaultsTo` should only take affect if the provided value for that attribute is strictly equal to `undefined`.

If that's different from the behavior you're seeing, let me know asap and I'll take a closer look.  Thank you!

**Comment by xhallix** [comment]
In my case, on my model I have `defaultsTo : 0.00`. 
When the Model is created the model Attribute is not `undefined` but ` '' `. So if the intended behavior is that only ` === undefined ` should be considered this is not a Bug. If possible, could you let me know why this is Händler strictly for ` undefined `?

Thanks

**Comment by mikermcneil** [comment]
> If possible, could you let me know why this is handled strictly for undefined?

@xhallix good question:  The issue is that sometimes you actually want to persist empty string (`''`), zero (`0`), `false`, or `null` -- all of which are falsey values that would fail an `if(val)` test in JavaScript, and all of which are different than `undefined`.  In cases like this, it can be annoying, but for example if you were trying to store `false` or clear something out with `null`, it'd come in handy.  It's this way in order to help the behavior as easy to understand and reason about as possible.

In this case, if you want your API to treat empty string as undefined, then I think the right answer is to do something like the following in your action:

```js
// If `square_meter` is provided as an empty string, understand that
// to mean the same thing as if it was not sent at all:
var squareMeter = req.param('square_meter');
if (squareMeter === '') {
  squareMeter = undefined;
}

// ...

MyModel.create({
  square_meter: squareMeter,
  additional_costs : req.param('additional_costs'),
  notes: req.param('notes')
}).exec(function (err) {
  if (err) {
    return res.serverError(err);
  }//-•
  
  // ...

  return res.ok();

});
```

**Comment by mikermcneil** [comment]
@xhallix if you need this for all of your request parameters, you might do something like this:

```js
// Build a dictionary (plain JavaScript object) consisting of all the
// incoming request parameters -- except for those that were sent
// with a value of empty string ("").
var allParamsPruned = _.omit(req.allParams(), function (value){
  if (value === '') { return true; }
});
```



And if you find yourself running into this use case _a lot_, then you might even make a hook that does it for you; e.g.:

```js
// api/hooks/pruner/index.js
module.exports = function(sails) {
  return {
    routes: {
      before: {
        'all /*': function (req, res, next) {

          // Attach a custom method on `req`:

          /**
           * @returns {Dictionary}
           *   All request parameters... except for those w/ empty string on the RHS.
           */
          req.getAllParamsPruned = function getAllParamsPruned (){
            var allParamsPruned = _.omit(req.allParams(), function (value){
              return value === '';
            });
            return allParamsPruned;
          };

          return next();
        }
      }
    }
  };
};
```

**Comment by xhallix** [comment]
@mikermcneil thanks for the suggestions and also the explanation.
I already made some class which transforms such values to the given format 👍
