### ISSUE TITLE
Why some Waterline adapters return the documents being destroyed?

### ISSUE THREAD

**Issue by luislobo** [balderdashy/waterline#1411]
**Waterline version**: all
**Node version**: any
**NPM version**: any
**Operating system**: any

<hr/>

I normally use sails-mongo and it historically returned the "destroyed" objects after the destroy method. While doing some research on the adapter itself (trying to make it faster) I realized that returning the destroyed documents is not something that comes for free: it actually performs a find before doing the destroy, so if I do a destroy on a millon documents collection, it will probably blow out because of memory, in an operation that should not return documents/results.

I've checked that sails-mysql, sails-disk does return records also, but not sails-postgresql, sails-memory.

I suggest that all destroy operations should *not* return the documents/objects being deleted (even if that will actually break some code we have), because of consistency between adapters, performance, and memory consumption.

Also, the documentation says nothing about returning documents:
https://github.com/balderdashy/waterline-docs/blob/master/queries/query-methods.md#destroy-criteria--callback-

What do you think @particlebanana?

I could help you in refactoring the supported adapters that actually return documents.

**Comment by particlebanana** [comment]
@luislobo yup it was deprecated in Waterline `0.11` I believe. Waterline `0.13` which will be released before the end of the year will refactor some things to make adapters faster and as part of that I'll clean up the mongo adapter to bring it up to speed. There is a new driver we are going to implement as well.

The tough part is in Mongo and MySql `update` does something similar I believe - could just be MySql. I think the solution for that was to pass a flag in to determine if you don't want an additional find to take place and instead just get back the number of items updated.

**Comment by luislobo** [comment]
Yeah, I was thinking about that too, adding some options where you can configure `{fetchModels:true}` or something similar.

Let me know if you need some help on refactoring stuff, specially MongoDB and/or Redis.

**Comment by luislobo** [comment]
Also, this might be added too to the https://github.com/balderdashy/waterline/blob/master/ROADMAP.md#v013 notes... as it kind of matches the same usecase as the update

**Comment by mikermcneil** [comment]
@luislobo @particlebanana yeah definitely another meta key here would work out nicely.  Only thing I'm not sure about is if we can get it in all the adapters before v1. 

Regardless, we can go ahead and spec it out.  The most consistent thing w/ the other mtea key would be to do `.meta({ dontReturnRecordsOnDestroy: false })` (and have the default be `true`).  My hunch is that that's probably the right short-term solution.  But double negatives are always kind of confusing.

My other concern is that the return type otherwise (when not returning records) is going to change in WL 0.13, because it'll be the raw result from the driver (which is a report -- a dictionary with e.g. `numRecordsDestroyed: 3`).  And the weird thing is, if you're doing an isObject check on it, it's going to be easy to end up fooling your existing code into thinking it's an array, which is bad, and easy to miss during an upgrade.

At first I was thinking that some kind of single generic meta key like `resultKind` or `fetch` would do the trick (like specifying a log level).  For example,  you could specify `.meta({fetch: 'records'})` to get the entire records, or 'ids' for just the pk values, 'report' for the raw report, or '' for nothing at all (`undefined`).  But I'm beginning to think that would actually make things more arcane rather than less.  You tell me.

On the other hand, maybe the right thing to do here (slightly longer-term) is to partition it further, embedding the raw report slightly differently.  For example:

```javascript
// Pardon all the users.
User.update({ banned: true })
  .set({ banned: false })
  .exec(function (err) {
    // ...
    // (+ could have done `function (err, unused, report) {`
    //  and then `report.numRecordsUpdated`)
  });
```

```javascript
// Archive selected tickets.
Ticket.update({ id: req.param('selectedTicketIds') })
  .meta({ fetch: true })
  .exec(function (err, archivedTickets) {
    // ...
    // (+ could have done `function (err, archivedTickets, report) {`
    //  and then `report.numRecordsUpdated`)
  });
```



```javascript
// Delete all banned users
User.destroy({ banned: true })
  .exec(function (err) {
    // ...
    // (+ could have done `function (err, unused, report) {`
    //  and then `report.numRecordsDestroyed`)
  });
```

```javascript
// Delete selected tickets.
Ticket.destroy({ id: req.param('selectedTicketIds') })
  .meta({ fetch: true })
  .exec(function (err, deletedTickets) {
    // ...
    // (+ could have done `function (err, deletedTickets, report) {`
    //  and then `report.numRecordsDestroyed`)
  });
```

**Comment by mikermcneil** [comment]
@luislobo @particlebanana meanwhile, we could just go with what you're suggesting, Luis, and not worry about the raw report at all (i.e. we could pass it through as the 3rd cb arg in adapters where we already have it anyway-- so's we're all set up for later -- but we wouldn't necessarily expose it to userland right away  Unless it's easy.  Then we might as well).

This way, we'd solve the problem of the _.isObject check and kill two birds with one stone.  So we'd end up with something like this:


```javascript
// Pardon all the users.
User.update({ banned: true })
  .set({ banned: false })
  .exec(function (err) {
    // ...
  });
```

```javascript
// Archive selected tickets.
Ticket.update({ id: req.param('selectedTicketIds') })
  .meta({ fetch: true })
  .exec(function (err, archivedTickets) {
    // ...
  });
```



```javascript
// Delete all banned users
User.destroy({ banned: true })
  .exec(function (err) {
    // ...
  });
```

```javascript
// Delete selected tickets.
Ticket.destroy({ id: req.param('selectedTicketIds') })
  .meta({ fetch: true })
  .exec(function (err, deletedTickets) {
    // ...
  });
```

**Comment by mikermcneil** [comment]
@luislobo This also has the nice side effect of allowing us to handle this for createEach (and this way, out of the box, createEach() could just return nothing):

```javascript
// Enroll currently-logged-in user in the specified courses,
// using existing courses from the database when possible,
// and creating any new ones.
sails.datastore().transaction(function (db, done){

  User.findOne({ id: req.session.id })
  .usingConnection(db)
  .exec(function (err, loggedInUser) {
    if (err) { return done(err); }
    if (!loggedInUser) { return done(new Error('Consistency violation: Corrupted session - no such user ('+req.session.id+') exists in the db.')); }

    Course.find({
      code: { in: req.param('courseCodes') }
    })
    .select('code')
    .usingConnection(db)
    .exec(function (err, existingCourses) {
      if (err) { return done(err); }
    
      var newCourseCodes = _.difference(req.param('courseCodes'), _.pluck(existingCourses, 'id'));
      var newCourseSeeds = _.reduce(newCourseCodes, function (memo, code) {
        memo.push({ code: code, originallyEnteredByUser: req.session.id });
        return memo;
      }, []);

      Course.createEach(newCourseSeeds)
      .usingConnection(db)
      .meta({ fetch: true })
      .exec(function (err, newCourses){
        if (err) { return done(err); }

        User.addTo(loggedInUser.id, 'enrolledIn')
        .these(_.pluck(newCourses.concat(existingCourses), 'id'))
        .usingConnection(db)
        .exec(function (err){
          if (err) { return done(err); }
          
        });//</ addToCollection >
      });//</ createEach >
    });//</ find >
  });//</ User.findOne >
}, function (err) {
  if (err) { return res.serverError(err); }

  // All done!
  return res.ok();

});//</ transaction() >

**Comment by luislobo** [comment]
I really like the idea of having .meta({ fetch: true }).
It could also support some way of configuring how are you going to fetch them, by default it retrieves the models, but you could optionally pass .meta({fetch:true, fetchSelect: '*', populate: ['groups'], populateCondition: {deleted:false})
We can get really fancy :)

**Comment by mikermcneil** [comment]
@luislobo it's now implemented!

**Comment by luislobo** [comment]
@mikermcneil awesome! Loving the changes documented in https://github.com/balderdashy/waterline/blob/master/README.md#meta-keys, now it's very flexible and helps in improving performance.
