### ISSUE TITLE
afterUpdate is triggered before association is finished with add/save

### ISSUE THREAD

**Issue by l1br3** [balderdashy/waterline#1422]
**Sails version**: 0.12.10
**Waterline version**: 0.11.6
**Adapter**: sails-mongo@0.12.2
**Node version**: 7.3.0
**NPM version**: 3.10.10
**Operating system**: Debian 8 x64

<hr/>

Hi all,

If you add a record to a model and then save it, the afterUpdate lifecycle callback will be called but the model isn't yet associated so you cannot access it with a findOne.

I've made a [fresh repo](https://github.com/l1br3/sails-afterupdate-populate-bug) where you can find all steps to very easily reproduce the behaviour. Just clone, lift and look at the console.

Thanks for your awesome work on this project.

**Comment by l1br3** [comment]
@particlebanana any feedback on this ? Is this something wanted or a bug ? Or maybe an enhencement ?

**Comment by l1br3** [comment]
up

**Comment by particlebanana** [comment]
The `save` command is badly executed unfortunately 😿. In the next version of Sails/Waterline that's in beta now we actually removed it completely.

But basically the way it works when using `.add` and `.remove` is to queue up individual operations to run. Then when you call `.save()` it first takes what's in the record currently (minus the new operations) and updates the record. So imagine the following situation:

```javascript
User.findOne({ name: 'foo' }).exec(function(err, user) {
  if (err) {
    return; // handle the error case
  }

  if (!user) {
    return; // handle the missing user case
  }

  // Update the user's name
  user.name = 'bar';

  // Add a pet to the user's pets collection
  user.pets.add({ name: 'fluffy' });

  // Save the user
  user.save(function(err) {
    // user saved and pet added
  });
});
```

The order looks like:

* First run the `User.update()` command to update the user's name
* Then look at any queued up operations and create the pet linking it to the user

So the fact that you have `afterUpdate` being called without the associated records collections makes sense here. 

What we did in Sails v1 is to ditch the instance methods all together. So there is no longer a `.add`, `.remove`, or `.save` method. Instead you have `Model.addToCollection` and `Model.removeFromCollection`.

In your case I would refactor it to be a Model method that does the linking and then runs whatever you have in your lifecycle callback. So for example:

```javascript
// Channel Model
module.exports = {

  attributes: {

    name : {type: 'string'},

    messages: {
      collection: 'message',
      via : 'channels'
    },

  },

  // Now whenever you want to do that logic just call:
  // Channel.linkMessages(123, {}, cb);
  // This is also future proof for Sails v1 because it can easily be updated.
  linkMessages(channelId, messageData, cb) {
    Channel.findOne({ id: channelId }).exec(function(err, channel) {
      channel.add(message);
      channel.save(function(err) {
        Channel.findOne(values.id).populate('messages')
        .then(unpopChannel => {
          console.log(unpopChannel)
          cb();
        });
      });
    });
  }
};
```

**Comment by l1br3** [comment]
@particlebanana thanks for your message ! I know understand what happen. 
I've done something similar than your suggestion :)

**Comment by l1br3** [comment]
And I'll wait for 1.x to refactor
