### ISSUE TITLE
Model.find().sort(string) is not working

### ISSUE THREAD

**Issue by mrded** [balderdashy/waterline#1448]
**Waterline version**: 0.13.0-5
**Node version**: 7.5.0
**NPM version**: 4.1.2
**Operating system**: macOS 10.12.3 (16D32)

<hr/>

Just noticed, after updating Waterline 0.13.0-3 -> 0.13.0-5 I got following code broken:

    Company.find(ids).sort('unpublishOn DESC');

`.sort()` makes no effect here, it doesn't sort companies. All items still sort by ids.

**Comment by particlebanana** [comment]
@mrded thanks, I'll look into it.

**Comment by particlebanana** [comment]
@mrded I couldn't recreate this with the latest version of Waterline (0.13.0-6) so it might be fixed or it could be an adapter issue. Which adapter are you using here?

**Comment by mrded** [comment]
I'm using `sails-mysql` adapter.

**Comment by mrded** [comment]
Just checked it, and it's still not working. 

```
{
  "sails": "1.0.0-22",
  "waterline": "0.13.0-rc1"
  "sails-mysql": "1.0.0-5"
}
```

**Comment by mrded** [comment]
Oh, sorry. Every thing is fine now. Thanks :)
