### ISSUE TITLE
Update Many-To-Many-Through Relationship not dropping associations

### ISSUE THREAD

**Issue by chase-bleyl** [balderdashy/waterline#1453]
**Waterline version**: 0.11.9
**Node version**: 6.9.4
**NPM version**: 3.10.10
**Operating system**: macOS Sierra

<hr/>

I am having an issue with the many-to-many through association where I can't update properly. On update, it doesn't seem to be dropping the associations before writing the new ones. Thus, `update()` won't remove associations that aren't valid anymore.

I have recreated this issue at https://github.com/chase-bleyl/test-update. 

I have three models:

- Assignment
- AssignmentTag
- Tag

In `/api/controllers/AssignmentController` I have the update function. I will pass in an array of Tag ids that omits some IDs that are present and adds some new ones. The new IDs are added correctly, but the old IDs aren't removed, which leads me to believe that [the associations aren't dropping properly](http://sailsjs.com/documentation/reference/waterline-orm/models/update#?notes) before the add.

What is confusing is that I can read/write fine from these associations. I can populate the Tag objects from the Assignment, and the `.update()` adds the new tags to the Assignment object fine.

Any idea what I am doing wrong here?

**Comment by particlebanana** [comment]
Hey @chase-bleyl the nested association stuff is pretty wonky in Waterline 0.11. In the latest version that will ship with Sails v1 we went ahead and removed the nested "syncing" and added methods for adding, removing, and replacing associations.

We are working full speed to try and get that version out the door but I'll take a look when I get a spare minute and see if I can quickly track it down. All of these models are using the same database correct?

**Comment by chase-bleyl** [comment]
Thanks @particlebanana for addressing this. You are correct - all these models are hitting the same DB.

**Comment by particlebanana** [comment]
Alright @chase-bleyl it should be all patched up in Waterline `0.11.10`. If you re-install Sails it should pick it up.

**Comment by chase-bleyl** [comment]
I just tested and update on through associations seems to be working fine. Thank you @particlebanana !
