### ISSUE TITLE
Populate multiple levels down

### ISSUE THREAD

**Issue by npfitz** [balderdashy/waterline#256]
I'm wondering if there are any plans to have the populate function populate multiple levels down. For example, if I have a Document, which has a collections of Comments, and those Comments each have a Creator attribute that points to a User model, Should I be able to do something like: 
````
Document.findOne(1)
.populate("comments")
.populate("creator")
.exec(function(err, doc){
/*do stuff*/
});
````

**Comment by jakubstrama** [comment]
+1

**Comment by dmarcelino** [comment]
Closing this as a duplicate of #308, please continue the discussion there.

**Comment by felipecm** [comment]
+1

**Comment by pavel-anisimov** [comment]
+1

**Comment by dmarcelino** [comment]
Please continue the discussion in #308.
