### ISSUE TITLE
[FEATURE REQUEST] Nested Create

### ISSUE THREAD

**Issue by TheFinestArtist** [balderdashy/waterline#329]
I have two model "User" & "Course"

User has attribute supervising_courses 
Course has attribute managers
Those are connected as many to many association.

Whenever a user create a course, I have to connect supervising_courses and managers. But I like to do it on life cycle callback such as beforevalidate or beforecreate.

But it's kind of impossible because course has not created for the callback (beforeValidate, afterValidate, beforeCreate) and user information can't be retained at the callback (afterCreate). So I have to override action create or make new action for this. Is there any good solution for this? I want to do it on lifecycle callback.

I like to associate this two model at Course Life Cycle Callback! Is is possible?

User Model
```
module.exports = {
  attributes: {
    // Many to Many
    supervising_courses: {
    	collection: 'Courses',
    	via: 'managers',
    	dominant: true
    } 
  }
};
```

Course Model
```
module.exports = {
  attributes: {
    // Many to Many
    managers: {
    	collection: 'Users',
    	via: 'supervising_courses'
    }    
  },

  beforeValidate: function(values, next) {
    next();
  },

  afterValidate: function(values, next) {
    next();
  },

  beforeCreate: function(values, next) {
    next();
  },

  afterCreate: function(values, next) {
    next();
  }
};
```

**Comment by kevinob11** [comment]
Any news on this? I've used nested create somewhat successfully, but with some weird results. It appears when I do a nested create that the afterCreate lifecycle callback is never called on the primary model, instead beforeUpdate and afterUpdate are called. The model instances do get saved to the database as expected though.

**Comment by dmarcelino** [comment]
@tjwebb I can see that waterline-adapter-tests already cover this scenario in [create.nested.js](
https://github.com/balderdashy/waterline-adapter-tests/blob/master/interfaces/associations/manyToMany/create.nested.js):

```javascript
            var data = {
              name: 'many to many nested',
              taxis: [
                { medallion: 1 },
                { medallion: 2 }
              ]
            };

            Associations.Driver.create(data).exec(function(err, values) { ... });
```

so I believe we can close this.

**Comment by dmarcelino** [comment]
Please reopen if this hasn't been fully answered.
