### ISSUE TITLE
[FEATURE REQUEST] create.populate & update.populate

### ISSUE THREAD

**Issue by TheFinestArtist** [balderdashy/waterline#354]
It will be awesome if I can populate on creation!
```
Users.create({
  username: username,
  password: password,
  email: email,		
  device: device.id
})
.populate('device')
.exec(function callback(err, user) {
  return res.send(user);
});
```

**Comment by kaduev13** [comment]
+1

**Comment by zzadik** [comment]
+1

**Comment by dmarcelino** [comment]
+1

**Comment by JThramer** [comment]
+1

**Comment by JibstaMan** [comment]
+1

**Comment by DrAlexMV** [comment]
+1

**Comment by jesucarr** [comment]
Is this planned? and the link to the FR should be this one: https://github.com/balderdashy/waterline/blob/master/ROADMAP.md

**Comment by dmarcelino** [comment]
@jesucarr, tentatively added this to WL_Next milestone which will be the feature release after 0.11.

**Comment by berrytree** [comment]
+1

**Comment by berrytree** [comment]
+1

**Comment by Andrew-Max** [comment]
@tjwebb 

When I use your suggested syntax above with waterline 0.10.19
```
Users.create({
  username: username,
  password: password,
  email: email,     
  device: device.id
})
.then(function (user) {
  return user.populate('device');
})
.then(function (user) {
  res.json(user);
});
```

I get an undefine method error on populate()

The second syntax: 
```
Users.create({
  username: username,
  password: password,
  email: email,     
  device: device.id
})
.then(function (user) {
  return User.find(user).populate('device');
})
.then(function (user) {
  res.json(user);
});
```

Works for me. Are they even any different under the hood? Is the first style making one less query?

Any ideas what needs to be true about creates return object to be able to call populate directly on it?

**Comment by dmarcelino** [comment]
```js
return user.populate('device');
```

@Andrew-Max, this would require an instance method `populate()` which doesn't exist yet, check #572.

The second approach is the only valid one at the current time.

**Comment by Andrew-Max** [comment]
Gotcha. Thanks for the clarification!

**Comment by makrolabs** [comment]
+1 for this

**Comment by lukaszgrolik** [comment]
+1

**Comment by particlebanana** [comment]
Plenty of workarounds and they require the same number of queries.
