### ISSUE TITLE
Association .populate() only populates defined attributes

### ISSUE THREAD

**Issue by danielbaak** [balderdashy/waterline#366]
When using adapters that support schemaless mode (i.e. `schema: false`) populating a One-to-many association only populates the attributes defined in the associated model being populated. 

I'm pretty sure this is undesired behaviour?

**Comment by particlebanana** [comment]
Submitted https://github.com/balderdashy/waterline/pull/985 which should be a fix for this but needs a bit of testing.

**Comment by dmarcelino** [comment]
Hey @particlebanana, I think tests for this feature would be great candidates to be placed in a `features/schemaless` folder and enabled via adapter package.json like `"features": ["schemaless"]`. More about this idea on PR balderdashy/waterline-adapter-tests#64.

**Comment by devinivy** [comment]
This helps me understand my questions in https://github.com/balderdashy/waterline/pull/985#issuecomment-102218703

Perhaps the `select` option should be removed altogether with #985.

**Comment by dmarcelino** [comment]
If it's removed will `find({select[]})` still work in schemaless mode? Or the `select` you mentioned is not related to this one?

**Comment by devinivy** [comment]
It appears to me that this `select` isn't directly related to the `find` option.  We could scour the code to confirm that, but the easiest thing to do would be to try and use sails-memory in schemaless mode :P

**Comment by dmarcelino** [comment]
>  the easiest thing to do would be to try and use sails-memory in schemaless mode :P

True :)

**Comment by dmarcelino** [comment]
`select` tests added in PR balderdashy/waterline-adapter-tests#71.

**Comment by dmarcelino** [comment]
Fixed by PR #985, please re-open if you are still experiencing this issue.
