### ISSUE TITLE
Use a model as the manyToMany relationship

### ISSUE THREAD

**Issue by marcelklehr** [balderdashy/waterline#391]
Suppose in some app, *users* can make *edits* to *documents*. So, I have a Document model,  a user model and an edit model.

A *document* has many *edits*. A *user* has many *edits*.

Now, you should be able to query the authors of a document as well as the documents that a user edited, so, usually you'd set up a many to many relationship between *document* and *user*.

However, since the edit model is already a manifestation of this relationship, my question is, if this existing model can somehow be utilized as the manyToMany relationship between document and user.

(in v0.10.x)

**Comment by dmarcelino** [comment]
@marcelklehr, the 2 solutions mentioned before are being discussed in different threads:

1. Many-to-many through associations: #705
2. Deeper populates: #308

So I'm closing this for now. Please reopen if you feel otherwise.
