### ISSUE TITLE
[Feature Request] SQLite Adapter

### ISSUE THREAD

**Issue by Globegitter** [balderdashy/waterline#405]
While I love the database support, SQLite support would be awesome because for some smaller projects in our environment it is just way easier to have the complete database in one file and you can just deploy it to the server like that without any extra configuration etc.
Or is there a user adapter for that already, by any chance?

**Comment by prodigitalson** [comment]
+1 for sqlite adapter

**Comment by AudreaM** [comment]
+1

**Comment by dmarcelino** [comment]
@Globegitter, @funkygibbing, @prodigitalson, @AudreaM how about you guys combining efforts and creating a sails-sqlite org and project? :smiley: Maybe you can leverage [waterline-sequel](https://github.com/balderdashy/waterline-sequel) to help generating the queries!

**Comment by devinivy** [comment]
(Bearing in mind other SQL adapters may be using Knex in the future, per https://github.com/balderdashy/waterline/issues/605)

**Comment by dmarcelino** [comment]
If waterline-sequel is modified to use Knex (https://github.com/balderdashy/waterline/issues/605#issue-40883930) that may become easier.

**Comment by dmarcelino** [comment]
Maybe this will help: https://github.com/AndrewJo/sails-sqlite3.

Closing this for now as I believe sqlite support will have to come from the community. Please re-open if you feel otherwise.

**Comment by tjwebb** [comment]
New SQLite Adapter: https://github.com/waterlinejs/sqlite3-adapter
