### ISSUE TITLE
multiple sort order error

### ISSUE THREAD

**Issue by zieglar** [balderdashy/waterline#407]
when I use sort like `.sort('firstletter asc').sort('id asc')` the Query sql is `ORDER BY b.id asc, b.firstletter asc`, but I need `ORDER BY b.firstletter asc, b.id asc`, please fix it!

**Comment by dmarcelino** [comment]
@zieglar, are you still experiencing this? Which adapter are you using? Thanks

**Comment by dmarcelino** [comment]
Closing this as duplicate of #694 which has a few suggestions on how to fix this. Thanks!
