### ISSUE TITLE
feature req: ability to declaratively define sanitize/transform rules

### ISSUE THREAD

**Issue by gebrits** [balderdashy/waterline#409]
Consider the example of storing/ quering an `email` field on a `User`. Common practice is to have this email-address lowercased and truncated before storing. 

Similarly, each `findX` method querying for an `email`-address should be preceded by some code to properly transform the email-address (lowercase + truncate). 

This obviously isn't DRY. 

What if you could declaratively define transformation/sanitization rules per field which would kick in on CUD + all Find-methods? 

Again `email` is just an example here. Imho it's broadly applicable.

**Comment by dmarcelino** [comment]
Hi @gebrits, `beforeFind` (#902) and `afterFind` (#923) will added in waterline 0.11. I believe those would be enough to address this. Please reopen if you feel otherwise, thanks.
