### ISSUE TITLE
[Feature Request] Optimistic Locking?

### ISSUE THREAD

**Issue by animedbz16** [balderdashy/waterline#426]
Has there been any discussion on supporting optimistic locking?

Such as only updating a record if the updatedAt parameter matches what is in the DB?

This could potentially allow for a findAndUpdate method.

**Comment by dmarcelino** [comment]
@animedbz16, this is very much in line with transactions which are being discussed in #755. I'm closing this for now to consolidate the discussions onto one thread, please continue the discussion there. Feel free to reopen if you feel otherwise.
