### ISSUE TITLE
One-to-many Relationship saves embedded collections

### ISSUE THREAD

**Issue by halissonvit** [balderdashy/waterline#429]
Hi,
Not sure if this is the expected behavior, since we should have only relations right?

I've the following models:

``` 
/** User.js */
module.exports = {
  attributes: {
    name: "String",
	  profiles: { collection: 'Profile', via: 'user' }
  }
};
```

```
/** Profile.js */
module.exports = {
	attributes: {
		email: 'email',
		user: { model: 'User' }
	}
};
```

When trying to create an user with the JSON:

```
{
  "name": "user",
  "profiles": [
    {
      "email": "user@user.com"
    }
  ]
}
```

It's creating an embedded collection on mongo:

```
/* 0 */
{
    "_id" : ObjectId("53750b6fc35a49901fb6efa9"),
    "name" : "user",
    "profiles" : [ 
        {
            "email" : "user@user.com"
        }
    ],
    "createdAt" : ISODate("2014-05-15T18:46:07.543Z"),
    "updatedAt" : ISODate("2014-05-15T18:46:07.550Z")
}
```

I'm using the following packages:
```
"sails": "~0.10.0-rc7", ----> "waterline": "0.10.0-rc12",
"sails-mongo": "0.10.0-rc4",
```

Thanks.

**Comment by charlietilt** [comment]
Setting `schema: true` does resolve this issue but also limits the flexibility of using a schema-less db such as mongo. I have an idea for a fix for this but was wondering if anyone else has any suggestions. Also, the Embedded Documents feature would resolve my issue as well but it seems like there could be a fix in place to resolve this before the embedded functionality is enabled.

**Comment by dmarcelino** [comment]
I've recently noticed something very similar when running the adapter tests against waterline-orientdb. If I use `schema: true` all tests pass. If I use `schema: false` 4 tests fail, namely:
```
Association Interface n:m association :: .update() update nested associations() with single level depth when associations have primary keys should update associat
ion values:
```

When inspecting the data passed on to `adapter.update()` I see embedded data which I don't think it should be there.
```javascript
{ name: 'm:m update nested - updated',
  taxis: 
   [ { '@type': 'd',
       '@class': 'taxiTable',
       medallion: 1,
       createdAt: Sat Feb 28 2015 17:06:47 GMT+0000 (WET),
       updatedAt: Sat Feb 28 2015 17:06:47 GMT+0000 (WET),
       id: '#23:26' },
     { '@type': 'd',
       '@class': 'taxiTable',
       medallion: 2,
       createdAt: Sat Feb 28 2015 17:06:47 GMT+0000 (WET),
       updatedAt: Sat Feb 28 2015 17:06:47 GMT+0000 (WET),
       id: '#23:27' } ],
  updatedAt: Sat Feb 28 2015 17:06:47 GMT+0000 (WET) } +4ms
```

Is this waterline core responsibility or does the adapter needs to compensate for this?

@charlietilt, no suggestions I'm afraid but would like to hear your ideas about a fix.

**Comment by devinivy** [comment]
After some digging, the only place that I see waterline paying attention to there being a schema or not is here: https://github.com/balderdashy/waterline/blob/master/lib/waterline/core/schema.js#L194

That seems benign to me, and pretty natural.  My inclination is that it probably _is_ up to the adapters to deal with this correctly.  @dmarcelino do you see the embedded data sent to the adapters whether schema is on or off?

**Comment by dmarcelino** [comment]
@devinivy, finally looked into this, when run the same test with `schema: true`, these are the values passed to `adapter.update()`:

``` javascript
{ name: 'm:m update nested - updated',
  updatedAt: Wed Apr 08 2015 21:23:21 GMT+0100 (WEST) }
```

I'm starting to think that waterline core is broken and that sails-memory/disk were built to cope with it...

**Comment by devinivy** [comment]
A hunch!

**Comment by dmarcelino** [comment]
Just for reference, as mentioned on https://github.com/balderdashy/sails-mongo/issues/254#issuecomment-94304674, I've tried commenting out [schema.js#L198](https://github.com/balderdashy/waterline/blob/713d9677dec0e0a252028eab67e8007b665b07be/lib/waterline/core/schema.js#L198):
``` javascript
if(!this.hasSchema) return values;
```

And it makes all sails-orientdb tests pass when `schema: 'false'` which is a big improvement! So I think @devinivy is onto something!

**Comment by devinivy** [comment]
I don't have access to a computer with node today, but I can provide a PR soon!  I understand the problem at hand.  We also need failing tests, so if anyone wants to write those, that'd be amazing.  The tests should ensure that when `schema: true`, adapter methods `update` and `create` receive values with collection and non-defined attributes stripped.  When `schema: false`, adapter methods `update` and `create` receive values with just collection attributes stripped.  There may possibly be relevant integration tests too.

**Comment by devinivy** [comment]
PR #959 posted!

**Comment by dmarcelino** [comment]
@devinivy, your change fixes 1 error from the 4 errors I'm experiencing in sails-orientdb schemaless:
1. Association Interface 1:1 association :: .update() update nested associations() with single level depth when association have primary keys should update association values:
2. ~~Association Interface 1:m association :: .update() update nested associations() with single level depth when associations have primary keys should update association values~~: Fixed :white_check_mark: 
3. Association Interface n:m association :: .update() update nested associations() with single level depth when associations already exist should reset associations with the updated associations:
4. Association Interface n:m association :: .update() update nested associations() with single level depth when associations have primary keys should update association values:

Given the title of the current issue I would say it effectively fixes this but I also think we're close to fix the others.

**Comment by devinivy** [comment]
@dmarcelino do you have some tests that would be reusable in other adapters?

**Comment by dmarcelino** [comment]
The tests I'm mentioning are the default waterline-adapter-tests ran against sails-orientdb schemaless. These pass when `schema: 'true'`.

**Comment by dmarcelino** [comment]
Given the operation is an update that updates values returned by the adapter itself I'm now wondering the if the existence of some extraneous fields is coming from waterline core or sails-orientdb. An example of such case is `adapter.update()` being called with values:
```javascript
{ '@type': 'document',
  '@class': 'driverTable',
  name: 'm:m update nested - updated',
  createdAt: Mon Apr 20 2015 17:02:40 GMT+0100 (WEST),
  updatedAt: Mon Apr 20 2015 17:02:40 GMT+0100 (WEST),
  out_driver_taxis__taxi_drivers: [ { cluster: 27, position: 6 }, { cluster: 27, position: 7 } ],
  id: NaN }
```

`@type` and `@class` are OrientDB record fields and are benign but I haven't yet figured out if `out_driver_taxis__taxi_drivers` is there because sails-orientdb returned it or if waterline is putting it there. Still investigating...

**Comment by dmarcelino** [comment]
So, from what I can grasp sails-orientdb is not adding `out_driver_taxis__taxi_drivers` to the values so it seems sails-orientdb is doing this. Why I am not sure...

**Comment by devinivy** [comment]
@dmarcelino is there a typo up there?  Seems that one of those "sails-orientdb" should be "waterline", but I don't know which one!

**Comment by dmarcelino** [comment]
Fixed :smiley:

**Comment by devinivy** [comment]
I noticed that sails-orientdb has adapter methods that directly pass the query down to "connection" methods, which directly pass the query down to "collection" methods.  Do you find those extra properties on the `values` object as early as [here](https://github.com/appscot/sails-orientdb/blob/master/lib/adapter.js#L300)?  That's the method that waterline will call.

**Comment by dmarcelino** [comment]
But yes, that's precisely where I'm monitoring those properties ;)

**Comment by dmarcelino** [comment]
@devinivy, the presence of that extra field is a `sails-orientdb` issue. Your fix seems solid and opens a pathway that should allow sails-orientdb to support schemaless mode. Thanks again!

**Comment by devinivy** [comment]
Very glad!  Let's get that PR reviewed, and hopefully we can close this one out soon!

**Comment by devinivy** [comment]
https://github.com/balderdashy/waterline/pull/959 merged.  Look for the fix in the next patch update to waterline.
