### ISSUE TITLE
 `waterline` considers `array` as a `string`

### ISSUE THREAD

**Issue by clarkorz** [balderdashy/waterline#477]
// attribute
    images: [{ url: 'string', width: 'integer', height: 'integer'}]
    // OR
    images: ['url']

This can pass `anchor#to()`, but `waterline` considers `images` as a `string` type.

**Comment by dmarcelino** [comment]
Any updates on this? See also #698 which could be related.

**Comment by dmarcelino** [comment]
Closing this as unresponsive, please feel free to reopen at any time!
