### ISSUE TITLE
join table name for an association can be longer than mysql allowed

### ISSUE THREAD

**Issue by mkeremguc** [balderdashy/waterline#497]
when using somewhat long model names and associating them between, the auto-generated join table name is greater than the mysql's allowed (64 chars). i searched but couldn't find to neither increase the mysql table name size nor defining a custom join table name for sails/waterline. it fails to lift with 'ER_WRONG_TABLE_NAME: Incorrect table name'.. any workaround ?

**Comment by mkeremguc** [comment]
how are we gonna solve this ? i can make an immediate PR that truncates the join table's name at 64 chars length. however i doubt that may lead to duplicate join table names

**Comment by dmarcelino** [comment]
@mkeremguc, there's a more recent discussion about this on #725 (even though it kind of stalled in December).

**Comment by dmarcelino** [comment]
This needs to be addressed in sails-mysql: raised balderdashy/sails-mysql#197. For the longer discussion on this read #725.
