### ISSUE TITLE
Return 0 if no results returned at Model.count()

### ISSUE THREAD

**Issue by gaprl** [balderdashy/waterline#630]
At [dql.js#L201](https://github.com/balderdashy/waterline/blob/master/lib/waterline/adapter/dql.js#L201) waterline is returning `models.length` for the count() method but if you pass a query where the return of Model.find() is `undefined`, .count() will return an error - trying to get length of undefined.

I think the correct would be to just return 0 if no models are found:

````javascript
    this.find(criteria, function(err, models) {
        if(!models) return cb(null, 0);

        cb(err, models.length);
    });
````

**Comment by devinivy** [comment]
This appears to be fixed: https://github.com/balderdashy/waterline/commit/900d7d13a0b76baa4e6b3ad980d8a4eb8ccc98d7

We'll reopen if anyone finds otherwise!
