### ISSUE TITLE
Can a model access other collections?

### ISSUE THREAD

**Issue by eddieajau** [balderdashy/waterline#653]
Using standalone Waterline (no global `Sails` object), can a model access the `collections` object somehow from a lifecycle event handler or from a custom behaviour function?

**Comment by dmarcelino** [comment]
@eddieajau, did you find a solution for this?

My suggestion is that in waterline standalone you can also make `collections` global.

**Comment by devinivy** [comment]
Just make sure the orm is in the scope of the model definitions, and you'll be all set.  In my project my model definition might look like,
```
module.exports = function(waterline) {

    /* now waterline is in the scope of the model definition */

    return {/* model definition with lifecycle callbacks, etc. */}
}
```

And I register the models as such,
```javascript
var waterline = new Waterline();

// If the provided model info is a function, it wants waterline passed to it.
// This is used for lifecycle callbacks to have access to collections, etc.
if (typeof model === 'function') {
    model = model(waterline);
}

waterline.loadCollection(
    Waterline.Collection.extend(model)
);
```

**Comment by eddieajau** [comment]
I've moved onto using Sails proper, but I'd probably go with something like the suggestion from @devinivy if I was to go back to just using Waterline.
