### ISSUE TITLE
Can you disable associations on update?

### ISSUE THREAD

**Issue by eddieajau** [balderdashy/waterline#654]
I'm having all sorts of trouble with validation failures when trying to update a model with associations. For example I might load a `Person` and a person can have a type of `Job` (butcher, baker, etc). I can load the person and populate their job. But when I come to update the person, sometimes the validator chokes on job and the stack trace is insufficient to find out exactly what's going wrong. What I think is happening is Waterline looks at the whole association object and tries to validate it, rather than just just looking at the foreign key.

So is there a way to just update the properties of that primary person object and ignore the actual association object(s)?

Thanks in advance.

**Comment by dmarcelino** [comment]
See also https://github.com/balderdashy/waterline/issues/964#issuecomment-95626676.

**Comment by dmarcelino** [comment]
Guys, can you check @devinivy's answer in https://github.com/balderdashy/waterline/issues/964#issuecomment-95626676:

> The way nested updates works is as such,
> 
> 1. When an id is specified on a nested record passed to `Collection#update`, update those nested records.
> 2. Remove all associations with the parent record, either by removing associations from a junction table (m:n) or by setting child record foreign keys to null (1:n).
> 3. For those nested records passed to `Collection#update` without specified without ids, create them.
> 4. Gather ids from all nested records, now created or updated, and associate those records with the parent record.
> 
> Step two is failing for you.  In your case, since nested updates reset associations entirely, doing updates like this is generally _bound_ to orphan post records, which isn't allowed by your model.  If your records aren't allowed to be orphaned, it might be better to update those child records directly, so that their foreign keys are explicitly switched.  I hope it's clear: doing a nested update like this will leave you with exactly one post associated with your user.

I think that explains what's going on. 

In #975 there is an ongoing discussion on what can be done to fix this. Please continue the discussion there. If you feel the issues are different please reopen this! Thanks.
