### ISSUE TITLE
toJSON inconsistency between find() and create() for associations

### ISSUE THREAD

**Issue by arcseldon** [balderdashy/waterline#662]
Am using Waterline ORM with SailsJS. For the purposes of this explanation, my domain model contains two models - Admedia and AdmediaField. An Admedia can have many admediaFields. An admediaField can belong to only one Admedia. So one to many.

Admedia.js

  fields: {
      collection: 'admediafield',
      via: 'admedia'
    },

AdmediaField.js

  admedia: {
      required: true,
      notNull: true,
      columnName: 'admedia_id',
      model: 'admedia'
    },

Now:

when I create a new AdmediaField, toJSON returns with just the id of the Admedia (to which it is associated)

when I find a new AdmediaField, toJSOn returns with a populated Admedia object (to which it is associated).

It is really helpful in SailsJS, for REST responses etc to be able to override the toJSON() method and customise it according to requirements.

Because of the differences above, all the model objects require hacks like below to cater for either a Create / Get op type:

toJSON: function () {
      var obj = this.toObject();
      obj.admedia = obj.admedia.id ? obj.admedia.id : obj.admedia;
      delete obj.mappings;
      delete obj.createdAt;
      delete obj.updatedAt;
      return obj;
    }

This is a really simple example, it gets more pronounced in cases where there are greater number of complex associations.

Issue: Can we make toJSON consistent so that regardless of Action it consistently returns the same JSON output?

Benefit: That way, conditional logic can be removed / haviing to explicitly override toJSON all the time can be avoided.

**Comment by anasyb** [comment]
Indeed there is an issue for associations, and its in the toObject methods of waterline. You might want to have a look at some workarounds towards the end of the thread here: https://github.com/balderdashy/waterline/issues/317#issuecomment-87274671

**Comment by dmarcelino** [comment]
Hi @arcseldon, regarding:

> Be nice if Create() could create and populate. Perhaps I am missing knowledge of such a method.. ?!

There is already another request for that in #354.

As @anasyb mentioned, the issue with `.toJSON()` seems to be the same in #317.

Please continue this discussion there, closing this as duplicate. Reopen if you feel otherwise.
