### ISSUE TITLE
Pass options into query

### ISSUE THREAD

**Issue by seth2810** [balderdashy/waterline#668]
Hello everyone. I am developing an application on the sails, and faced with the need to pass additional parameters adapter for each request generated by the model. Maybe there are already any ways how this can be done more or less transparent? Maybe there is something like the middleware?

**Comment by devinivy** [comment]
It seems like the upcoming `beforeFind` lifecycle feature will suit you here!  See #902.  If you have more specific questions about this, we can reopen this issue.
