### ISSUE TITLE
populate() and populateAll() with 2 connections

### ISSUE THREAD

**Issue by pablovilas** [balderdashy/waterline#677]
Hello,

I've a model A with memory conection and a model B with redis conection.

A is:

attributes: {
        code: 'integer',
        B: {
            model: 'B'
        },
}

B is:

attributes: {
        code: 'integer',
        otherData: 'string',
}

If I do this:
 A.findOne(1).populateAll().exec(function(err, a){
      // a.B is undefined!!!
      // the same if I use populate('B');
});

**Comment by dfulgham** [comment]
Still not working in

waterline@0.10.18
sails-mysql@0.10.11
sails-disk@0.10.7

See my comment on similar issue:
https://github.com/balderdashy/waterline/issues/779#issuecomment-72872342

**Comment by dmarcelino** [comment]
Should be fixed by #925 / #984. Please re-open if this re-surfaces.
