### ISSUE TITLE
Array of JSON attribute for models

### ISSUE THREAD

**Issue by MrDHat** [balderdashy/waterline#695]
Array of json is a common occurrence in MongoDB models. However, there is no documentation (or I cannot find anything?) pertaining to this.
What is the best way of representing such an attribute?
I am not looking for a one-many relationship via associations, I want to use embedded documents in Mongo.

**Comment by devinivy** [comment]
@hellowin the only practical difference is how a particular adapter might handle them differently.  Either type of value should come out of the database as an `array` or `json` object respectively!  This seems answered now, but if someone disagrees, we can reopen!
