### ISSUE TITLE
Teardown adapter method on waterline collection is taking wrong arguments.

### ISSUE THREAD

**Issue by devinivy** [balderdashy/waterline#697]
This piece of code that attaches non-CRUD adapter methods onto a waterline collection does not apply the correct arguments specifically for the teardown method.  Most adapter methods begin with a `connection` then a `collection`/`tableName` argument, which is what is assumed [here](https://github.com/balderdashy/waterline/blob/4653f8a18016d2bcde9a70c90dd63a7c69381935/lib/waterline/query/adapters.js#L34).

> `var args = [conn, tableName].concat(Array.prototype.slice.call(arguments));`

But the teardown method is an exception this rule.  It takes a connection, but not a table name.  What ends up happening is that you get a type error: `TypeError: string is not a function`

It's trying to call the table name string as the callback since the arguments are all out of whack.

**Comment by dmarcelino** [comment]
@devinivy, is this still an issue?

**Comment by devinivy** [comment]
I do believe so, yup!

**Comment by nethoncho** [comment]
This is causing issues in one of the projects I am working on. See Buto/sails-oracledb-sp#3
The first argument to teardown is always null
Sails 0.11.0
Node v0.12.7

**Comment by devinivy** [comment]
I don't have time to make a PR for this at the moment, but it should be a fairly simple change.  See the original post for details.

**Comment by particlebanana** [comment]
So we just need to tap into it and if the method is `teardown` only pass the connection? Sounds easy enough, I can knock this out.

**Comment by nethoncho** [comment]
Currently ```connection``` is undefined
My adapter only needs ```connection```. It appears that the other adapters only need ```connection``` also
