### ISSUE TITLE
How can i load models dynamically ?

### ISSUE THREAD

**Issue by debianmaster** [balderdashy/waterline#720]
My requirement is to load models dynamically (i..e after the connection is established)

This works fine 

Steps:-    Procedure 1
Step 1:--   orm.loadCollection(collection);
Setp 2:-    orm.initialize(config)   

But i need this:-   Procedure 2

Steps:-    
Setp 1:-    orm.initialize(config)   
Step 2:--   orm.loadCollection(collection);   --  this should load collection dynamically

But i have to re-initialize to make procedure 2 work  is there any work around?

**Comment by devinivy** [comment]
If this isn't an acceptable answer, please flag us to reopen!

**Comment by tjwebb** [comment]
> But i have to re-initialize to make procedure 2 work is there any work around?

This is the only way to connect up new associations; since your new model definition might affect other models' associations, the whole ORM graph needs to be re-examined.
