### ISSUE TITLE
mn-table name too long

### ISSUE THREAD

**Issue by nichdiekuh** [balderdashy/waterline#725]
Hello,

the way waterline builds association table names quickly exceeds the max table name length in mysql - it's just 64 characters.

For instance:
I have two models with the following names:
- InterpretationParameters
- ParameterValueInterpretations

Both models have an mn-association and the resulting tablename is:

```
 ER_WRONG_TABLE_NAME: Incorrect table name 'interpretationparameter_parametervalueinterpretations__parametervalueinterpretation_interpretationpa'
```

I think this naming scheme is quite wasteful and should be changed. As soon as both table names combined are >30 characters, the creation of mn-tables will fail. 

My proposal :
`mn__table_table2`

**Comment by dmarcelino** [comment]
My suggestion regarding waterline core changes is for it to support a new parameter named **joinTableName** within the association attribute like below:

``` javascript
{
  tableName: 'driverTable',
  identity: 'driver',

  attributes: {
    taxis: {
      collection: 'taxi',
      via: 'drivers',
      joinTableName: 'drives',  // sets junction tableName without affecting its identity
      dominant: true
    },
}
```

PS: I've actually tried to implement this via adapter ([waterline-orientdb](https://github.com/appscot/waterline-orientdb)) but I got errors like the below:
  ```
  Association Interface n:m association :: .add() create nested associations() with single level depth and objects should create a new driver and taxis and associate them:
     Error: Unknown rule: joinTableName
      at Object.matchRule (/Users/warchild/Development/node/waterline-orientdb/node_modules/waterline/node_modules/anchor/lib/match/
matchRule.js:37:11)
  ```

**Comment by mkeremguc** [comment]
can we discuss on a solution to this ?.. btw, it seems that postgresql also limits the jointable names at 64chars, but it doesn't give error so it seems postgre truncates the table name internally

**Comment by devinivy** [comment]
The solution to this primarily involves updates to waterline-schema so that it respects the new option.  I'll take a deeper look at this today.  Additionally, each adapter should deal with any constraints on their own.  The postgresql adapter has the ability to shorten table names that are too long or to internally-to-the-adapter create its own junction table name convention.  Or just throw an error and tell the user to use the soon-to-be feature of assigning a custom junction table name of appropriate length!

**Comment by devinivy** [comment]
I opened the requisite stories in sails-postgresql and waterline-schema to fully address this issue (see referenced issues above).  The onus is no longer on waterline itself for now, so I'm closing this bug–it should be taken care of in the adapter.

**Comment by dmarcelino** [comment]
@devinivy, I got the impression from @mkeremguc that Postgres was handling the long names well:
> it seems that postgresql also limits the jointable names at 64chars, but it doesn't give error so it seems postgre truncates the table name internally

@mkeremguc can you comment?

Anyway we also need a fix for MySQL adapter so I've raised balderdashy/sails-mysql#197.

**Comment by devinivy** [comment]
Cool, good thought!  Do we need one for mongo too?  Yeah, as I understand it, postgresql automatically does the truncation.  Perhaps the adapters would want to deal with this more "smartly", esp for join tables.   From http://www.postgresql.org/docs/9.3/static/sql-syntax-lexical.html , 
>The system uses no more than NAMEDATALEN-1 bytes of an identifier; longer names can be written in commands, **but they will be truncated**. By default, NAMEDATALEN is 64 so the maximum identifier length is 63 bytes.

**Comment by dmarcelino** [comment]
Oh I see, you are probably right, the adapter can be made aware of it and at least throw an error if after truncation there is table name collision, for example.

Regarding mongo, I'll quote @nichdiekuh:

> http://docs.mongodb.org/manual/reference/limits/
> 
> Namespace Length
> Each namespace, including database and collection name, must be shorter than 123 bytes.

It has a limit which is harder to hit... I would say MySQL is the priority.

**Comment by mkeremguc** [comment]
@dmarcelino, yea devinivy already proved postgre handles it internally.
+1 for MySQL priority

**Comment by jasonmcneill** [comment]
Couldn't the sails-mysql adapter just use SHA-256 on the existing long name of the many-to-many join table before creating it?  If mySQL has a 64-character limit for tables, then using SHA-256 will guarantee that (A) the new table name will be precisely 64 characters long, and (B) there will be no naming conflicts.
