### ISSUE TITLE
save() performs differently than standard API functionality for URL datatype

### ISSUE THREAD

**Issue by drj-io** [balderdashy/waterline#738]
I'm a little reluctant to report this as I don't have a lot of information, but I wanted to at least tell SOMEONE!

sending a standard URL to the URL Type via the API saves fine.

But when you run save() on the same model, the URL doesn't validate at all.  

I didn't have a lot of time to debut, so I just changed my app out to STRING.

Hope this helps!

**Comment by dmarcelino** [comment]
Hi @drj-io, @arcseldon, if I understand correctly this is an issue with validations, where you have a model with `type: 'url'`. And the validation will work for:
```
Collection.create({ url: "http://www.google.com" }).then(...);
```
But i fails for:
```
Collection.find(1).then(function(err, model){
  model.user = "http://www.google.com";
  model.save(); // behaves differently than example above?
});
```

Is this what you are saying or did I misunderstand?

**Comment by dmarcelino** [comment]
I'm closing this for now as we don't have enough information to reproduce. Please add more more details (a failing test would be awesome) and reopen.
