### ISSUE TITLE
one-to-one becoming one-way

### ISSUE THREAD

**Issue by gotmikhail** [balderdashy/waterline#753]
Posted this in sails, but after almost two weeks of no response, I thought I would try waterline...

I noticed I was not getting the same response on a post as I was on a get. Specifically, associations.

Referencing 'Create new record while associating w/ another new record'
https://github.com/balderdashy/sails-docs/blob/master/reference/blueprint-api/Create.md

I recreate the scenario from the documentation with `sails new testProj`, then `sails generate api pony` and `sails generate api pet`, then update the models to have a one-to-one association.

Pony
```javascript
module.exports = {
    attributes: {
        pet: {
            model: 'pet'
        }
    }
};
```
Pet
```javascript
module.exports = {
    attributes: {
        pony: {
            model: 'pony'
        }
    }
};
```
Then, `sails lift` away.

`POST /pony`
JSON Req
```javascript
{
  "name": "Pinkie Pie",
  "hobby": "ice skating",
  "pet": {
    "name": "Gummy",
    "species": "crocodile"
  }
}
```
JSON Res
```javascript
{
  "name": "Pinkie Pie",
  "hobby": "ice skating",
  "pet": 1,
  "createdAt": "2014-11-21T19:18:09.161Z",
  "updatedAt": "2014-11-21T19:18:09.161Z",
  "id": 1
}
```
As you can see, the `res`ponse did not include the full pet object, just its id. In the documentation, it shows the full object being returned.

The entries and the association were definitely created successfully, 
`GET - /pony/1`
```javascript
{
  "pet": {
    "name": "Gummy",
    "species": "crocodile",
    "createdAt": "2014-11-21T19:18:09.157Z",
    "updatedAt": "2014-11-21T19:18:09.157Z",
    "id": 1
  },
  "name": "Pinkie Pie",
  "hobby": "ice skating",
  "createdAt": "2014-11-21T19:18:09.161Z",
  "updatedAt": "2014-11-21T19:18:09.161Z",
  "id": 1
}
```

Is this an error in documentation, or an error in code? Either way, is there a way we can specify that we want the associations to be returned?

One-to-one associations are just showing up as the linked id, many to many do not show up at all. I was looking into the `toObject()` function for `waterline` for another issue when I saw the `showJoins` option; it looks like it might be related to that.

In addition, this one-to-one association is actually only being created as a one-way association.

After completing the same as above:

`GET - /pet/1`
```javascript
{
  "name": "Gummy",
  "species": "crocodile",
  "createdAt": "2014-12-03T20:50:31.346Z",
  "updatedAt": "2014-12-03T20:50:31.346Z",
  "id": 1
}
```
Notice that no pony is returned.

Just to make sure...
`GET - /pony/1/pet`
```javascript
{
  "name": "Gummy",
  "species": "crocodile",
  "createdAt": "2014-12-03T20:50:31.346Z",
  "updatedAt": "2014-12-03T20:50:31.346Z",
  "id": 1
}
```
`GET - /pet/1/pony`
```javascript
Specified record (1) is missing relation `pony`
```

Pony has a pet, pet has no pony.

**Comment by kevinob11** [comment]
Is there a way to allow a one-to-one version of the collection type of association? Something like:

Pony
```
module.exports = {
    attributes: {
        pet: {
            model: 'pet'
        }
    }
};
```

Pet
```
module.exports = {
    attributes: {
        pony: {
            model: 'pony',
            via: 'pet'
        }
    }
};
```

You would still create the relation through the Pony model, by nesting or pointing at an ID, but the relation would be accessible from the pet model much like a one-to-many collection is. Thoughts?

**Comment by tjwebb** [comment]
> one-to-one version of the collection type

You're going to help me out with that one. That sounds self-contradictory.

**Comment by kevinob11** [comment]
Ha fair point. When I said collection type I didn't mean it was a collection (yep...wow), I was referring to the fact that relation attributes that use the collection prop don't require the use of a database column or join table on that model, it infers the relation from the explicit relation column on the other model. Could a one-to-one use the same implied relation logic?

**Comment by tjwebb** [comment]
I think I understand. What you're asking for I think isn't as crazy as it sounds, but I don't think is necessary; in that, it doesn't accommodate any currently-impossible use case.

Boiling all this down, I think what you're talking about is just a one-to-one that's *represented as* as one-to-many in the database, but which happens to contain only one record on the "many" side; is that basically right? If so, what you're asking for represents a way of thinking about database structure that is atypical. You can do this if you want, but it's not something we're going to support OOTB. In fact, I specifically would recommend working within the existing structure, and not inventing special ways to do stuff like this.

**Comment by kevinob11** [comment]
Hrm, yeah I suppose that makes sense. I wasn't so much trying to solve a specific impossible use case, I just want to be able to see my one-to-one relations from both models without writing a function to update the other side every time one is saved.

I realize the following from @particlebanana is true
> All it knows is that the Pony wants to be friends with the Pet (type model) but maybe the Pet doesn't like that Pony and would prefer to be friends with a different Pony

but it would be nice to have a way of saying that the pet _has_ to be friends with that pony

**Comment by dmarcelino** [comment]
Please reopen if you feel the answers weren't adequate.

**Comment by gotmikhail** [comment]
I'll pass this on to `sails-docs`, as the documentation is still incorrect.

**Comment by dmarcelino** [comment]
Thanks @gotmikhail, a PR would be appreciated :smiley:

**Comment by shaunc** [comment]
@tjwebb, @kevinob11 -- databases typically support `1 -> {0,1}` via a 1-many with "unique" specified. Then if Pony likes Pet, it can have pets ID, and Pet can find out which Pony (if any) likes it with a query. As waterline supports "unique" this gets you most of the way there I think?

**Comment by kevinob11** [comment]
@shaunc perhaps I'm missing something here but I didn't see any differing results with this. Let me make sure I understand; I have a person model that (1:1) points at a pet model:
```javascript
person: {
  attributes: {
    name: {
      type: 'text'
    },
    pet: {
      model: 'pet'
    }
  }
}
```
and a model for pet that (1:n) points at my person model:
```javascript
pet: {
  attributes: {
    name: {
      type: 'text'
    },
    person: {
      collection: 'person',
      via: 'pet'
    }
  }
}
```
If I pull a list of pets, they will show their related person, but it will be an array. My goal was simply to make that array simply the single person object in situations where I knew it was safe via that relation to do so. I thought, based on your comment you were saying that if I add unique to the person attribute of the pet (see below), that this would achieve that. This doesn't seem to be the case in my testing. If that isn't what you were saying I think I'm a little behind, can you explain with an example?
```javascript
pet: {
  attributes: {
    name: {
      type: 'text'
    },
    person: {
      collection: 'person',
      via: 'pet',
      unique: true
    }
  }
}
```

Thanks!

**Comment by dmarcelino** [comment]
For reference: there has been a feature request made for strict one-to-one associations in #1053.

**Comment by kevinob11** [comment]
Hey-o this is exactly what I'm looking for! thanks @dmarcelino

**Comment by dmarcelino** [comment]
I just copied the last comments from @shaunc and @kevinob11 to https://github.com/balderdashy/waterline/issues/1053#issuecomment-119621204. Let's all continue this discussion there.

**Comment by Sarabpreet** [comment]
facing the same problem 💯
