### ISSUE TITLE
Underscored createdAt and updatedAt

### ISSUE THREAD

**Issue by awm33** [balderdashy/waterline#754]
Is there a way to change the default createdAt and updatedAt to created_at and updated_at while keeping the automatic behavior for updated_at? created_at could just use a defaultTo

I'm trying to use waterline with an existing database that uses underscores

**Comment by elad** [comment]
@particlebanana  I'd like to do this too, would you be receptive to such a change?

If yes, I have two ideas:
  * Repurpose `autoCreatedAt` and `autoUpdatedAt` so they either accept a boolean (current functionality) or a string to be used as the field name. As in, `autoCreatedAt: 'created_at'`.
  * Introduce two new options to specify field names.

Thoughts? (I prefer the first)

**Comment by awm33** [comment]
@elad I like the first one as well, just modifying `autoCreatedAt` and `autoUpdatedAt`. I'd be opening to adding it / contributing it. I'm just not sure how @particlebanana / the community would want it work. I've actually never contributed to a large open source project before

**Comment by Esya** [comment]
I just started implementing this change, pull-request incoming soon.

**Comment by devinivy** [comment]
See @Esya's PR https://github.com/balderdashy/waterline-schema/pull/23
