### ISSUE TITLE
autoIncrement not work on sails-mongo

### ISSUE THREAD

**Issue by khanghoang** [balderdashy/waterline#762]
This is my model structure

```
module.exports = { 
  autoPK: false,
  schema: true,

  attributes: {

    id: {
      type: 'integer',
      autoIncrement: true,
      primaryKey: true,
      unique: true
    },

    name : {
      type: 'string'
    }

  }
};
```

What i expect is that there is a field named "id" and it's auto increment.  
But when i try to create a user model, there is no "id" field

**Comment by dmarcelino** [comment]
Hi @khanghoang, according to sails-mongo:
> sails-mongo maps the logical id attribute to the required _id physical-layer mongo id.

Because of this I don't believe you can have an `id` of `type: 'integer'`.

Please re-open if you think this doesn't fully answer your question.

**Comment by siddharthapoladi** [comment]
Even this not working.?


```
module.exports = {
    attributes: {
        mobileNumber:{
            type:'integer'
        },
        city:{
            type:'string'
        },
        date_time:{
            type:'string'
        },
        priority:{
            type:'boolean'
        },
        status:{
            type:'string', defaultsTo:'Active'
        },
        tokenNum: {
            type: 'integer',
            autoIncrement: true
        }
    }
};

```

**Comment by siddharthapoladi** [comment]
@dmarcelino  Is there AutoIncrement feature to Attribute in Sails Mongo with waterline??
