### ISSUE TITLE
Is it possible to create a record without assigning a PK & saving?

### ISSUE THREAD

**Issue by cha0s** [balderdashy/waterline#763]
I'd like to be able to create an instance of a model without actually saving it or generating a PK (ID would equal null). Is this possible? I'd like to get an instance with all defaults populated, etc. but not actually save it.

**Comment by particlebanana** [comment]
This *should* work: `new Pet._model(values);`

**Comment by cha0s** [comment]
Using an underscored method is a code smell. Can we have this as a public API, please?

**Comment by particlebanana** [comment]
Sure mind putting together a pull request?

**Comment by cha0s** [comment]
Yup I'll get to this later tonight


Sent from my T-Mobile 4G LTE Device

<div>-------- Original message --------</div><div>From: Cody Stoltman <notifications@github.com> </div><div>Date:01/16/2015  12:17 PM  (GMT-06:00) </div><div>To: balderdashy/waterline <waterline@noreply.github.com> </div><div>Cc: Ruben Rodriguez <cha0s@therealcha0s.net> </div><div>Subject: Re: [waterline] Is it possible to create a record without assigning a
  PK & saving? (#763) </div><div>
</div>Sure mind putting together a pull request?

**Comment by cha0s** [comment]
Do you have a preference about the syntax? In the project I desired this functionality in, I augmented all collections with `.instantiate`, so I could do `var user = User.instantiate();`.

Does that seem like a god name? Should we go with `instance`, or something else do you think?

Might as well talk about it a little before I bother with a PR :)

**Comment by andrewjmead** [comment]
+1 for this. I wouldn't mind helping out with a PR as waterline has saved me a ton of development and maintenance time.

My use case is creating multiple instances of a model, but only if they are all valid.

**Comment by rishabhmhjn** [comment]
Was any method to support this feature added?

**Comment by devinivy** [comment]
No, there wasn't, but I would love to see a PR for this!  Using `Collection._model({/* record */})` still works (and I _expect_ it will work until there is a breaking change in waterline), though it doesn't feel great to use the private method.

**Comment by ejlangev** [comment]
`Collection._model({ /* data */})` doesn't seem to work very well.  I'm using waterline 0.10.26.  The method initially works and returns an instance of the model but if I try to call save on that model I immediately get an error "Error: No Primary Key set to update the record with! Primary Key must have a value, it can't be an optional value."

Some example code:

```js
var user = User._model({ email: 'foo@bar.com' });

user.save()
  .then(function() {
    console.log(user.id);
  })
  .catch(function(err) {
    console.log(err);
  });
```

**Comment by devinivy** [comment]
Ah, correct– `save()` only really knows how to perform an update.  I'm not sure.  I never really use it this way.  _Maybe_ `Collection.create(modelInstance)` works for your purposes.

**Comment by elennaro** [comment]
I have a similar problem: 

```
	/**
	 * MongoDB native findAndUpdate
	 * @name DbHelperService._findAndUpdate
	 * @param {Object} criteria
	 * @param {Object} model Waterline model
	 * @param {Object} update values to update { key: value }
	 * @param {Function} cb
	 * @private
	 */
	_findAndUpdate: function (criteria, model, update, cb) {
		console.log('0000', model);
		model.native(function (err, collection) {
			if (err)
				return cb(err);

			collection.findOneAndUpdate(criteria, update, { new: true }, function (err, result) {
				cb(err, result && result.value && new model._model(result.value));
			});
		});
	}
```

this method does not return a good model, for example it does not convert `_id<BSONObject>` to `id<String>`.

Help, please!

**Comment by devinivy** [comment]
sails-mongo has a utility method to normalize results based upon a schema: https://github.com/balderdashy/sails-mongo/blob/master/lib/utils.js#L78-L96

**Comment by ejlangev** [comment]
> Maybe Collection.create(modelInstance) works for your purposes.

Unfortunately it doesn't in this case.  I'm trying to build an adapter between waterline and [factory girl](https://github.com/aexmachina/factory-girl) and part of the interface is the ability to build a record without saving it and then subsequently save it later on.  I hacked around it myself for now but would be nice to fix the underlying issue so I can build the adapter into a real node package and release it.  I'll try to submit a pull request that fixes this since it seems like you're open to it.

**Comment by devinivy** [comment]
I am open to it– not sure where @particlebanana and others are with this.  But at least in the next big waterline release, I would love to see a proper public API for creating model instances.

**Comment by elennaro** [comment]
@devinivy +10000547

**Comment by particlebanana** [comment]
Yeah having `.save` do a create if there is no primary key is probably an ok solution or just allowing the `.create` method to accept a model instance would be the easiest. Just check if the data has a `toObject` method and if so call it.

**Comment by ejlangev** [comment]
I think I like the former solution of `.save` doing a create if there is no primary key.  What would the create method do if it accepts a model instance that already has a primary key?  Would it create a new record or try to update the existing one.  Seems like an easy mistake to make.
