### ISSUE TITLE
Stop validation after required fails

### ISSUE THREAD

**Issue by randallmeeker** [balderdashy/waterline#767]
currently if I have required: true on an attribute I get two error messages when it is not found

```
{
    rule: "string",
    message: "`undefined` should be a string (instead of "null", which is a object)"
},
{
    rule: "required",
    message: ""required" validation rule failed for input: null"
}
```

These messages are redundant and confusing. Should not the validation check required first and stop after if validation fails?

**Comment by dmarcelino** [comment]
I'm not sure if this is particular to `required` I think waterline/anchor just go through all the validation rules for each attribute. Fore example:
``` javascript
        email: {
          type: 'string',
          required: true,
          email: true
        }
```

yields:
```
{ email: 
   [ { rule: 'string',
       message: '`undefined` should be a string (instead of "null", which is a object)' },
     { rule: 'required',
       message: '"required" validation rule failed for input: null' },
     { rule: 'email',
       message: '"email" validation rule failed for input: null' } ] }
```

I can't say I feel particularly strong about stopping immediately or continuing...

**Comment by devinivy** [comment]
@tjwebb any feelings about this?  If so, this should probably be moved to anchor.  Otherwise, I think this can be closed.

**Comment by dmarcelino** [comment]
Closing this for now, please re-open if you feel otherwise.
