### ISSUE TITLE
make it clear whether `paginate` will iterate through the result set 

### ISSUE THREAD

**Issue by kevinburke** [balderdashy/waterline#771]
will `paginate(limit: 10)` only return the first ten results, or will it page through your data until no results are left? if it only returns one page, it would be great to have docs on how to page through multiple result sets. if it pages through the whole thing, it would be good to note this.

**Comment by dmarcelino** [comment]
Judging solely from https://github.com/balderdashy/waterline-docs/blob/master/query.md#paginate, `paginate({ limit: 10 })` is equivalent to `paginate({ page: 0, limit: 10 })` which would translate to:
```javascript
Model.find()
.skip(0)
.limit(10)
.exec(function(err, records) {});
```

So it would only return the first 10 records. @kevinburke, is there anything you think that needs to be changed on https://github.com/balderdashy/waterline-docs/blob/master/query.md#paginate?

**Comment by dmarcelino** [comment]
Closing this for now, please reopen if you think the docs can be improved. Thanks.
