### ISSUE TITLE
Waterline custom validator

### ISSUE THREAD

**Issue by slyder** [balderdashy/waterline#775]
Could not add custom waterline validator. I have next model: http://pastebin.com/6zj9vcxn, and after Payment2.create().then(console.log, console.log), i recieve only 1 field error message: "Invalid attributes sent to Payment2: userId", but i should have error for RUBLES field also. Looks like waterline ignores my validation rules. 
BUT if i uncomment required: true rule for rubles-field. Waterline starts use my custom validators also. Looks like waterline bug? Or i do something wrong? 
Here is pastebin of examples: http://pastebin.com/HgBcGaD8

**Comment by websquared** [comment]
Same issue here - it's ignoring my custom validation types - not even calling invitation_field function:
```
  types: {
    invitation_field: function(value) {
      sails.log.info(value);
      return (this.status == 'invited') ? Boolean(value) : true;
    },
  },
  attributes: {
    ...
    inviteEmail: {
      type: "string",
      invitation_field: true
    },
}
```

**Comment by websquared** [comment]
Thanks @particlebanana. I see, it makes sense now, because in my case value was empty. 

Is there a way then to check if value is empty based on other value? In other words set field as required if another field is set - similar to #579?

**Comment by particlebanana** [comment]
I just pushed out bd5152416753d035086825e021e8b11eeb2e0f78 which should work for #579

**Comment by slyder** [comment]
@particlebanana thanks for answer, for now i set defaultsTo rule so waterline apply custom validators.

But in case if i want leave value as null or undefined i add next function with validation
```javascript
  beforeCreate: function (values, next) {
    // validator
    if (values.rubles <= 0 && values.bonuses <= 0) {
      return next({err: ["Amount of payment should not be zero."]});
    }
    next();
  },
```

It works good also, but is there any way to make same type as native waterline error (Error (E_VALIDATION))? So i could be able filter all errors by same error code.
For example:
```javascript
			.fail(function(err) {
				if (err.code === "E_VALIDATION") {
					res.status(400)
					return res.json(err);
				}
				return next(err);
			});
```

**Comment by devinivy** [comment]
@slyder you can get that error constructor by requiring from the waterline package:
```
var WLValidationError = require('project_root/node_modules/waterline/lib/waterline/error/WLValidationError');
```

Then you can use it as it's used here: https://github.com/balderdashy/waterline/blob/master/lib/waterline/query/validate.js#L43-L48

I'm going to close this out, but if you still feel unanswered, we can open this issue up again.
