### ISSUE TITLE
Binary fields passed as Buffers can not be saved to the database in 0.10.15

### ISSUE THREAD

**Issue by DavidEBest** [balderdashy/waterline#792]
After updating to 0.10.15, I started receiving this message from calls to `create`:
``` json
{
  "error": {
    "error":"E_VALIDATION",
    "status":400,
    "summary":"1 attribute is invalid",
    "model":"File",
    "invalidAttributes": {
      "data": [ {
        "rule":"binary",
        "message":"`undefined` should be a binary (instead of \"[object Object]\", which is a object)"
      } ]
    }
  }
}
```

Switching back to 0.10.13 got everything running smoothly again.

Looking through the changes, I believe that the the switch to using cloneDeep in 4eea538a089c0a29d96ef634595eb646042aade2 introduced the bug.

According to the cloneDeep documentation [here](https://lodash.com/docs#cloneDeep):
> ...objects created by constructors other than Object are cloned to plain Object objects

I believe these cloned Buffers no longer pass the `Buffer.isBuffer()` validation check.

**Comment by particlebanana** [comment]
Ouch! Ok yeah we will need to loop through and pull out any buffers before cloning and then re-insert them in the cloned object. I'll take a look.

**Comment by particlebanana** [comment]
Ok I pushed out Waterline 0.10.16 which should fix this up. Let me know if you still have issues with it.

**Comment by DavidEBest** [comment]
Works great! Thanks for the quick response, @particlebanana.
