### ISSUE TITLE
[Feature Request] in save method add parameter to run or not to run life cycle callbacks

### ISSUE THREAD

**Issue by nuclear-icebreaker** [balderdashy/waterline#793]
In save method it should be possible to specify whether to run or not to run life cycle callbacks. Use case is preordered tree operations. When change on one record triggers changes on many of them.

Example code is in question I posted on SO http://stackoverflow.com/q/26427356/1695418

**Comment by dmarcelino** [comment]
@particlebanana, @devinivy, @tjwebb, what do you guys think about being able to disable lifecycle callbacks on a save/update/destroy operation?

**Comment by devinivy** [comment]
I would opt to go a different route here, such as providing the ability to pass meta information (in the form of an object) to the adapter and lifecycle callbacks.  Then the lifecycle callbacks could act on any any information that the user would like to provide them.  The object would be an optional parameter to `Model#save` and all the public `Collection` methods.

**Comment by dmarcelino** [comment]
I see what you mean @devinivy, something similar (regarding the adapters) has been discussed in  #780: Queries language: passing adapter specific parameters. I think that could be a reasonable tradeoff.
