### ISSUE TITLE
No index is created on association column on mysql / postgresql 

### ISSUE THREAD

**Issue by nozer** [balderdashy/waterline#794]
When I create an association like this,
```...
owner: {
    model: 'user'
},
...
```

I expected that an index is created on the owner column in the database (such as mysql / postgresql) because that column will probably be used to join the tables when populating and must be indexed by default. It was not indexed as I checked on mysql and postgresql. 

I wonder if sails team could add automated indexing of association columns in the next version of sails / waterline. That would be much appreciated!

**Comment by randallmeeker** [comment]
+1

**Comment by andyhu** [comment]
+1 this would probably happen also with sails-mongo

**Comment by drmikecrowe** [comment]
+1 (issue for sails-mongo -- no index is created for the model attribute)

**Comment by prisonier** [comment]
Did you put your migrate setting to drop or alter ? 
If you have migrate : safe in /config/models.js, nothing will happen to your tables when you lift.

**Comment by nozer** [comment]
Yes I did. Also, index is not created when tables are created for the first time (clean db).

**Comment by prisonier** [comment]
It works for me on sails 0.10.2 & mysql 5.5.41, migrate : alter

I've tried : 
index : true then lift -> index created
remove index:true then lift -> index removed
index : true then lift -> index recreated

i'm sorry for you dude.

I've also tried the script given by @drmikecrowe, but it gave me the following error :  

        model.native(function(err, collection) { ensureIndexCreated(model, col
              ^
TypeError: Object #<bound> has no method 'native'
  at /home/me/myapp/api/hooks/reindex-db.js:56:15


Good luck !

**Comment by nozer** [comment]
Did you try it on a column (attribute) that is an association ? (having model:'some model') value

**Comment by prisonier** [comment]
Absolutely, 

This is my 'Order' model : 

module.exports = {
  attributes: {
    star : {
      model : 'star',
      required : true,
      index: true // Create an Index in MySQL
    },
  }
};

I have another model that have the star attribute without the required : true : 

This is my 'Staraccount' model : 
module.exports = {
  attributes: {
    star : {
      model : 'star',
      index : true // Create an Index in MySQL
    },
  }
};

Both of them have the star_index created on MySQL and PostgreSQL.

**Comment by prisonier** [comment]
what sails version are you using ?

**Comment by nozer** [comment]
I just tried on postgres and it did create. I was first aware of this a few months ago when I was working on some sails project and it really did not create on mysql (cannot remember the version). My current sails version is 0.10.5 and I think the other one was above 0.10 as well. 

Thanks a lot. I will update the issue above to say that index is created if index: true is specified; association attributes should still be indexed by default for performance reasons.

**Comment by prisonier** [comment]
>association attributes should still be indexed by default for performance reasons.

+1

**Comment by dmarcelino** [comment]
@nozer, could you raise this on sails-mysql/sails-postgresql or potentially waterline-sequel? I don't think there is anything to be done on the waterline core side.

**Comment by dmarcelino** [comment]
Closing this as it's an adapter issue and should be dealt in the appropriate adapter project. Please reopen if you feel otherwise. Thanks!

**Comment by cardimajs** [comment]
+1
