### ISSUE TITLE
Contains Does Not Sanetize Correctly!! Sql Injection Critical

### ISSUE THREAD

**Issue by kennysmoothx** [balderdashy/waterline#802]
When doing a query using 'contains'

Waterline does not sanetize correctly for instance:

```
Movies.find({
	title : {
		'contains': title,
	},
	on_server: true,
	deleted: false
}).exec(function (err, movies) {

});
```

If title = "www.google.com"

We get the following error:

```
[Error (E_UNKNOWN) Encountered an unexpected error] Details:  Error: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '."google"."com%"  AND `movies`.`on_server` = true AND `movies`.`deleted` = false' at line 1 
```

**Comment by tjwebb** [comment]
Does this happen with other adapters besides MySQL?

**Comment by particlebanana** [comment]
Yup looks like waterline sequel doesn't escape `.` properly. I'll get a patch pushed out.

**Comment by particlebanana** [comment]
ok give sails-mysql `0.10.10` a shot

**Comment by kennysmoothx** [comment]
sails-mysql `0.10.10` fixes it! Thanks @particlebanana 

However the following issue needs to be fixed before I can push this up to production:
balderdashy/sails-mysql#180

I believe there's a PR for it aswell.

**Comment by kennysmoothx** [comment]
@particlebanana thanks for your quick update, `0.10.11` fixes this issue now and the other issue as well.

**Comment by kevinburke** [comment]
What (if any) is the attack vector? are people running less than 0.10.11
vulnerable?


--
Kevin Burke
phone: 925.271.7005 | twentymilliseconds.com

**Comment by kennysmoothx** [comment]
Hello @kevinburke ,

Essentially anyone with sails-mysql under `0.10.11` will have an error with queries which use `contains` and the string has a period, because the period is not escaped correctly, meaning that any and all queries with a period in the string will cause a MySQL `ER_PARSE_ERROR`. 

Although I've tried to actually inject other SQL with this vulnerability it's particularly hard because everything else is escaped correctly so I do not think that injection is all that serious(or possible), however queries will break and cause errors.
