### ISSUE TITLE
`sails lift` pegs CPU and crashes after a while due to lack of memory with migrate:'alter'

### ISSUE THREAD

**Issue by secrettriangle** [balderdashy/waterline#804]
migrate:'safe' works great. I am using PostgreSQL 9.3. I have ~20K rows in a table -- the only change I made was adding a few indices, which shouldn't take more than a few seconds and shouldn't make node itself peg the CPU.

**Comment by particlebanana** [comment]
Yeah `migrate: alter` isn't that smart. It doesn't create any kind of diffs at all, it simply recreates your table and reinserts the rows. You don't want to use it with any sort of data!

Checkout https://github.com/BlueHotDog/sails-migrations which works pretty well and allows you to have versioned migrations.

**Comment by devinivy** [comment]
Sounds like `alter` doesn't work well for this particular situation.  I think the question has been answered– if you feel otherwise, we can reopen.  If you think there's a feature request lurking here, please create a new issue.
