### ISSUE TITLE
Searching inside a collection type

### ISSUE THREAD

**Issue by freesuraj** [balderdashy/waterline#808]
Here's the scenario
 ` Post : { title: {type: 'string'}, body: {type: 'text'}, likes: {collection:'like'}} `
` Like: {object_id: {type: 'string'}, object_type: {type: 'string' }, count: {type: 'integer'}, users: {collection: 'user'} }  `

Query: Find the likes by user `1`
I need to search inside the `Like` table's `users` collection for given `user`. How do I do this ?

I tried this, doesn't work

`Like.find({users: {contains: user.id}})`

Thanks.

**Comment by devinivy** [comment]
You want to populate the likes on a user.  Analogously to your example, 
```javascript
User.findOne(user.id).populate('likes').exec(function(err, user) {

    var likes = user.likes;
});
```

If your question remains unanswered, we can reopen this!
