### ISSUE TITLE
Update behavior for nested models

### ISSUE THREAD

**Issue by JThramer** [balderdashy/waterline#822]
If i'm reading this line of code right (https://github.com/balderdashy/waterline/blame/master/lib/waterline/utils/nestedOperations/update.js#L516), updates to records with nested models seem to work iff the record attribute name is the same as the model name. 

Is this intended behavior? and if so, why is it not documented?

Thanks!

**Comment by JThramer** [comment]
(Technically, this works if `association` (which, in testing, seems to be the attribute name) is equal to the name of the collection that the attribute's model represents. Since the collection name is the same as the model name, this is tantamount to `association` being equal to the Model name.)

**Comment by devinivy** [comment]
This is actually a bug that has been fixed in the tests (https://github.com/balderdashy/waterline-adapter-tests/pull/44) and the code (https://github.com/balderdashy/waterline/pull/934)!  Thanks for bringing it up!
