### ISSUE TITLE
Incompatibility with moment.js between 0.10.14 and 0.10.18

### ISSUE THREAD

**Issue by gotmikhail** [balderdashy/waterline#826]
I understand this is compatibility with another library, `moment.js`, so there may not be any motivation to fix it, but just wanted to report that somewhere between `waterline` `0.10.14` and `0.10.18` the compatibility with `moment` objects in validation was broken. Note that I've tried with both `moment.js` `2.8.4` and `2.9.0` to see if it was an update with `moment.js`. With both of those versions, `waterline` `0.10.14` works and `0.10.18` doesn't.

The error reported is 
`'undefined' should be a datetime (instead of "[object Object]", which is a object)`

Note that I actually haven't tested this with a `Date() object`, so there may be an issue there as well.

**Comment by dmarcelino** [comment]
Closing this as a duplicate of #835, given the latter has more participants. Please reopen if you feel otherwise.

**Comment by dmarcelino** [comment]
Actually, I could have been wrong, in #835 the objective is to add a new type called `time` while here the issue is with `datetime`, right?

@gotmikhail, before 0.10.14 were you able to use  `moment` objects?

**Comment by gotmikhail** [comment]
@dmarcelino Correct, it was with `datetime`.

While I was on `0.10.14` I was able to simply send in a `moment` object as a datetime, after the update to `0.10.18` that no longer worked. I turned to using `moment().format()`. That way you're sending a string instead, so that works, but the `moment` object did not.

**Comment by dmarcelino** [comment]
@gotmikhail, can you check if PR #764 fixes your issue? It has been merged to master so you just need to try the latest github version.

**Comment by dmarcelino** [comment]
@gotmikhail I'm closing this for now assuming #764 fixes this, please reopen if that's not the case. Thanks
