### ISSUE TITLE
ORD

### ISSUE THREAD

**Issue by gunish** [balderdashy/waterline#831]
Hi,

Is there an automatic way to generate an ORD / ERD from the waterlock models ? Something on the lines of SchemaSpy ?

**Comment by dmarcelino** [comment]
Hi @gunish, waterlock is a project independent of waterline and is maintained by different people. In it's README it says:
> Waterlock works by hooking into your model and controller files adding the functionality needed. 

So it seems to me that waterlock hooks into your models and extend them generating the models you need. To create a DB schema from these models in a development environment you should only need to set `migrate: 'alter'` and sails will create the DB schema on `sails lift`. More on this in: http://sailsjs.org/#!/documentation/concepts/ORM/model-settings.html?q=migrate

Please reopen if this doesn't fully answer your question.

**Comment by gunish** [comment]
Hello, 

Thanks for your reply, and I apologies my issue description was wrong,

I am looking for a schema diagraming tool to visualise the Models which I created for my SailsJS app. 

If there is such a thing!
