### ISSUE TITLE
bluebird methods missing

### ISSUE THREAD

**Issue by phishy** [balderdashy/waterline#836]
.each(), .return(), and all Bluebird utilities except for then(), spread(), and catch() are missing.

**Comment by bberrySTW** [comment]
+1

**Comment by nozer** [comment]
+1

**Comment by tjwebb** [comment]
Make sure your global sails is updated to the latest version. We've seen this issue before where the local sails module is up-to-date, but the global one is not.

**Comment by phishy** [comment]
Oh interesting. I assumed because they were not explicitly defined here, that they weren't mapped. I'll try that.
https://github.com/balderdashy/waterline/blob/b20dbe6ff79ebf55abfddb44d0aec2b3d2595e1d/lib/waterline/query/deferred.js#L520

**Comment by toolbear** [comment]
@phishy @tjwebb 

Does that mean this code is *supposed* to work:

```
user = User.find().tap(function(user) {
   …
}).then(…)
…
```

Or do I still need to call `then`, `spread`, or `catch` (or `toPromise`) at least once before I have all the Bluebird utilities?

**Comment by devinivy** [comment]
@phishy @toolbear any word on if those bluebird utilities work with the latest version of waterline?

**Comment by toolbear** [comment]
@devinivy no word, sorry.

We stopped using Sails Models and Waterline because our app's DB doesn't have a Waterline adapter and writing one ourselves proved not to be the best use of our time at the moment.

**Comment by tjwebb** [comment]
@toolbear which database is this?

**Comment by toolbear** [comment]
@tjwebb Parse.com

Using the waterline adapter starter project we got an adapter up and running with CRUD fairly quickly, but got bogged down implementing relations. Starter project offered little/no direction past CRUD; I failed at finding additional guidance or articulating my need on gitter/IRC. Looking at the source of other adapters I had difficulty sussing out the waterline relationship specific parts.

Even with guidance a Waterline Parse adapter that fits our needs would be non-trivial; Parse has several ways of representing relations. Conceivably the adapter could support a subset of these initially. But our app doesn't have a greenfield database; it would take a mostly feature complete Parse adapter.

So we tabled the adapter for now and went with creating services that queried Parse directly via their SDK.

**Comment by tjwebb** [comment]
@toolbear have you seen https://github.com/zohararad/sails-rest? Might serve as a good starting point.

I'm on gitter all the time, perhaps we've just missed each other. Is your parse adapter project open source somewhere?

**Comment by dmarcelino** [comment]
Any update on this?

**Comment by dmarcelino** [comment]
Closing this as unresponsive, please reopen if you feel otherwise of if there are any updates. Thanks
