### ISSUE TITLE
Need help removing null values

### ISSUE THREAD

**Issue by dottodot** [balderdashy/waterline#841]
I have somehow managed to get a null value stored in my mongodb on an attribute that should an associated collection.

I'm using sails-mongo and there are 1000's of entries and I can't find a way to retrieve these entries and remove the attribute.

Any help would be greatly appreciated.

**Comment by tjwebb** [comment]
Might have more luck filing in the sails-mongo repo

**Comment by CWyrtzen** [comment]
@dottodot Have you asked on the Google Group: https://groups.google.com/d/forum/sailsjs

**Comment by devinivy** [comment]
This does sound like it requires some adapter-specific knowledge.  I highly suggest asking the question in [sails-mongo](https://github.com/balderdashy/sails-mongo/issues)!  Also might be worth checking-out http://stackoverflow.com/questions/9312067/mongodb-queries-with-null-value .  Also, keep in mind that you can use the adapter's `native` method.

I think this is just about as much help as the waterline core repo has to offer for this mongo-related question–good luck!
