### ISSUE TITLE
Created records not populated

### ISSUE THREAD

**Issue by LoveIsGrief** [balderdashy/waterline#842]
Hello,

I have a simple One-to-many association in my SailsJS app

`Person.js`
```javascript
module.exports = {

	// Disallows record with unknown attributes
	// https://github.com/balderdashy/waterline-docs/blob/1a993393a3efccf6c8e96d7f051e2c67949ac773/models.md#schema
	schema: true,

	attributes: {

		name:{
			type: "string"
		},

		houses : {
			collection: "house",
			via: "person"
		}
	},
};
```

`House.js`
```javascript
module.exports = {

	attributes: {
		person:{
			model: "person"
		},
		address: {
			type: "string",
			required: true,
			unique: true
		}
	}
};
```

When I try to create a Person with houses and reuse that person with the houses, it won't work:

```javascript
Person.create({
  name: "Prat Baker",
  houses: [
    {
      address: "Baker Street 101, Wherever,Australia"
    }, {
      address: "Hollister Ave 211, Hun,Australia"
    }
  ]
}).populate("houses").then(function(createdPerson) {
  return Person.findOne({
    id: createdPerson.id
  }).populate("houses").then(function(foundPerson) {});
});
```
**Output:**

    sails> Created person:  { name: 'Prat Baker',
      createdAt: Mon Feb 16 2015 20:55:26 GMT+0100 (CET),
      updatedAt: Mon Feb 16 2015 20:55:26 GMT+0100 (CET),
      id: 1 }
    { houses: 
       [ { address: 'Baker Street 101, Wherever,Australia',
           person: 1,
           createdAt: Mon Feb 16 2015 20:55:26 GMT+0100 (CET),
           updatedAt: Mon Feb 16 2015 20:55:26 GMT+0100 (CET),
           id: 1 },
         { address: 'Hollister Ave 211, Hun,Australia',
           person: 1,
           createdAt: Mon Feb 16 2015 20:55:26 GMT+0100 (CET),
           updatedAt: Mon Feb 16 2015 20:55:26 GMT+0100 (CET),
           id: 2 } ],
      name: 'Prat Baker',
      createdAt: Mon Feb 16 2015 20:55:26 GMT+0100 (CET),
      updatedAt: Mon Feb 16 2015 20:55:26 GMT+0100 (CET),
      id: 1 }

As you can see, I have to run `findOne` again. 

I hope I'm doing it right. If so, if this is done millions of times, I believe it would put quite a strain on the db.

Cheers

**Comment by tjwebb** [comment]
When you run an `INSERT` query, you don't get back the row(s) you inserted, so even in straight SQL you have to make an additional query anyway. If you just want the data, you already have it: you passed the object into `Person.create`.

**Comment by LoveIsGrief** [comment]
Yes you are correct, but the way we have to write it now there are 2 additional queries, unless I'm mistaken.

The data passed doesn't have the IDs, createdAt, updatedAt, validated or ignored fields, etc.  
In short the data isn't populated, so in my opinion there are 2 options:

 * Mark in the documentation that `populate` does not work with `create`
 * Update the code to make `populate` work with `create`

**Comment by CWyrtzen** [comment]
Howdy folks, is this resolved?

**Comment by LoveIsGrief** [comment]
Haven't retested with a newer version, but it hasn't been referenced so I believe there haven't been any developments.

**Comment by dmarcelino** [comment]
Hi, there is another issue open requesting support for create.populate and update.populate: #354. I'm closing this as a duplicate, please reopen if you feel otherwise.
