### ISSUE TITLE
Cross adapter associations generate incorrect child operations

### ISSUE THREAD

**Issue by bradshja** [balderdashy/waterline#847]
While testing more associations between sails-memory and sails-mysql, I ran into a bug where populating all of my record's associations would cause the record to not be found.  The problem only occurred when I included the sails-mysql model in the associations along with more than one association from sails-mysql.

I ultimately tracked down the problem in query/finders/operations.js on line 214.  It appears that while building up the operations, it attempts to find child operations of previous operations, but doesn't check if it's already set the child of that operation and overwrites it.

By modifying this check so that it won't set the child if there already is one, it creates a new operation that runs correctly.

I admit that I don't fully understand the consequences of doing this, but it works for my case.  It seems like it should be possible to make the child operations a list, which would probably also fix it.

I'm going to submit a pull request that fixes my case, and if I encounter further problems I can try extending it to make it a list.

**Comment by dmarcelino** [comment]
@bradshja, would you mind adding a test to your PR please?

**Comment by dmarcelino** [comment]
Moved #976 from @stellarashes here:

> When I set a cross database association in my model, calling populate on the association would result in empty object for that member, whereas populating the association in the same database worked as expected (both the associations are 1-1).  After much debugging, I realized the results from the same database had the query results for population with the key of child key, whereas the cross database had the results with the key of the alias.  Further debugging showed that this key, being an alias, gets overwritten during the _transformer.unserialize() method, resulting in the row(s) from the other database being lost, and eventually gets resolved to an empty object.  When I've set populate.js line 54 from alias to fkToChild, everything worked as expected (but of course it caused unit tests to fail).  Was this intentional? (version 0.10.21 of waterline)

@stellarashes, there is an open PR for this, #848 can you try it please?

**Comment by dmarcelino** [comment]
@stellarashes, thanks for investigating! I've tried to run your code change suggestion against some cross connection associations tests I've *created* in https://github.com/balderdashy/waterline-adapter-tests/commit/dc7c871377b2a6e2c89f1719c9675309cf966c6e and it actually broke more tests than are currently broken... :disappointed:  I suppose there is some issue with [populate.js#L54](https://github.com/balderdashy/waterline/blob/master/lib/waterline/query/integrator/populate.js#L54) but the solution will probably have to be different....

**Comment by dmarcelino** [comment]
Should be fixed by #925 / #984, please re-open if the issue persists.
