### ISSUE TITLE
Batch Update

### ISSUE THREAD

**Issue by mpduffey** [balderdashy/waterline#851]
Is there an option to run a batch update to insert an array of record to be updated? For example, if I have a rank order field priority_rank and I change the order of one item in a list, all rows need to be updated uniquely. I would like to perform this with one transaction by uploading and array of objects with the id and new priority_rank.

Thanks,
Mike

**Comment by devinivy** [comment]
Sounds like a feature related to transaction support: #755

**Comment by dmarcelino** [comment]
Yes, this seems pretty intertwined with #755, it's probably a good idea to move it there for now. @mpduffey please continue this discussion in #755 given transactions are still in the drawing board. Closing this for now.
