### ISSUE TITLE
this.waterline.schema is undefined

### ISSUE THREAD

**Issue by marbemac** [balderdashy/waterline#854]
I'm trying to use my Sails.js models outside of the sails context. I have one simple model called "Request", and I'm using the sails-disk adapter. Everything works fine inside the Sails app, but when I try and use the model outside the app (I'm running a separate proxy server that needs to save requests passing through it) I get the error below. It seems that this.waterline.schema is undefined for some reason.

**Error:**
```
/path-to-app/node_modules/sails/node_modules/waterline/lib/waterline/core/index.js:70
var schemaAttributes = this.waterline.schema[this.identity].attributes;
                                                                        
TypeError: Cannot read property 'request' of undefined
```

**api/models/Request.js**
```js
module.exports = {
  identity: 'request',
  schema: true,
  autoCreatedAt: true,
  autoUpdatedAt: true,
  migrate: 'alter',
  attributes: {
    id: {
      type: 'string',
      primaryKey: true,
      required: true
    },

    method: 'string',
    url: 'string'
}
```

**./proxy.js attempt to load sails waterline model in external script (abbreviated)**
```js
var uuid = require('node-uuid'),
  Waterline = require('sails/node_modules/waterline'),
  RequestCollection = require('./api/models/Request.js'),
  sailsDisk = require('sails-disk');

RequestCollection.adapter = 'localDiskDb';
var Request = Waterline.Collection.extend(RequestCollection);

new Request({
  adapters: {
    localDiskDb: sailsDisk
  }
}, function(err, collection) {
  if (err) {
    console.error(err);
    return;
  }

  // Save the request
  collection.create({
    id: uuid.v4(),
    method: 'foo method',
    url: 'foo url'
  }).exec();
});
```

**Comment by airandfingers** [comment]
I'm having this issue as well. Using v0.10.18 from NPM.

I poked around in the source code a bit, and I didn't see anything obviously wrong.

**Comment by particlebanana** [comment]
Checkout the [express example](https://github.com/balderdashy/waterline/blob/master/example/express/express-example.js) for an example of loading the collections. Also checkout @joshbeitler project [Piranha](https://github.com/joshbeitler/piranha) for an easy to use solution.

`new Request` isn't the correct way to load the collection.

**Comment by airandfingers** [comment]
Okay, so both the README.md and [waterline-docs](https://github.com/balderdashy/waterline-docs) (neither of which mentions new Waterline() or initialize) describe an obsolete interface.

What documentation describes basic usage of the current version of Waterline, beyond the examples?
