### ISSUE TITLE
Find/filter by association

### ISSUE THREAD

**Issue by Globegitter** [balderdashy/waterline#855]
I want to query my model, but just find the ones that have a certain association, in an efficient manner.
So if I have a `ResearchProject`, a 1:n relationship to `Funds` I want to only select `ResearchProjects` that have funding.

I think something like `ResearchProject.find({ funds: { 'not': null }).limit(20).exec()` is what I imagined but is not working.

I suppose the way to do that right now is `ResearchProject.find().limit(20).populate('funds').exec(function(err, project){})` and then filter for `project.funds.length > 0`, right?

This works, but then is hard to actually get to return exactly 20 records and for large datasets that also makes it pretty inefficient, to query the db for all records and then filter, rather than filter on the db level in the first place.

I actually don't know how waterline handles associations under the hood, if it creates the relationships in the db, etc. but that would imo be highly useful to have.

**Comment by dmarcelino** [comment]
Hi @Globegitter,

I'm not sure if this works, but have you tried using `.find().populate([WHERE])`, something like:
```javascript
ResearchProject.find().limit(20).populate('funds', { id: { 'not': null }}).exec(function(err, project){})
```
Its efficiency would depend on the adapter.

Associations are handled by the adapters if they implement the `Associations` interface or by Waterline core otherwise.

**Comment by Globegitter** [comment]
@dmarcelino Thanks that is a good idea but unfortunately didn't work. Ah yeah that makes sense about `Associations`.

**Comment by dmarcelino** [comment]
@Globegitter, I just stumble upon #266 which this issue seems to duplicate. If you agree can you close this and comment there? Thanks.

**Comment by Globegitter** [comment]
@dmarcelino You are right, if this issue also covers the `not: null` it is a duplicate and it certainly makes sense to move that to the same issue.

**Comment by dmarcelino** [comment]
Good stuff! It's impressive how many good features have been suggested 6-10 months ago and still haven't been implemented. Though I'm optimistic given how much progress has been made recently! :smile:
