### ISSUE TITLE
Remove/save behaving very incorrectly for many-to-many relationship.

### ISSUE THREAD

**Issue by devinivy** [balderdashy/waterline#858]
In a rush... I will fill this out more soon.

But `remove` with a `save` is basically removing _all_ associated records instead of just those specified.  I'm using sails-mysql, but I've found that the issue lives in waterline itself.  `save` triggers a removal of many-to-many records correctly, but the nested operations for `save`'s implicit `update` is completely destroying all of a person's friends (per example below).  There seems to be a sync of join table data going awry.  I was bummed to see that approach to keeping nested elements up-to-date– it cannot work for non-transactional queries, which waterline does not support.  And it's prone to error when racing against a possibly simultaneous `remove` operation.

```
person.friends.remove(1);
person.save(function() {
    // now person has no friends
});
```

If you use many-to-many associations, this affects you!  Would love to get a PR up today.  Workin' on it, but would love some help.

**Comment by devinivy** [comment]
Update...
Seems this happens when `person` is populated with a subset of `friends`.  Only that subset will be restored during the nested operations update.  Definitely a huge bug!  @particlebanana what's the purpose of adding/removing relations during an update?  It not documented and _seems_ unnecessary to sync, but I'm curious to get some input.  I do agree that updating the values of nested objects makes sense, but I don't think that syncing the relationships themselves is a good idea, especially via syncing.  Code example of the issue:

```
Person.findOne(666).populate('friends', {id: 42})
.then(function(person) {
    person.friends.remove(42);
    person.save() {
        // now I have no friends, since nested operations assumed that this person had only one friend to begin with (friend 42), which is false.
    }
})
```

**Comment by devinivy** [comment]
Relevant stack trace of the save/update causing this,
```
    at module.exports [as update] (XXX/node_modules/waterline/lib/waterline/query/dql/update.js:29:13)
    at new module.exports (XXX/node_modules/waterline/lib/waterline/model/lib/associationMethods/update.js:61:14)
    at Array.async.auto.updateRecord [as 1] (XXX/node_modules/waterline/lib/waterline/model/lib/defaultMethods/save.js:73:41)
    at XXX/node_modules/waterline/node_modules/async/lib/async.js:487:38
    at Array.forEach (native)
    at _each (XXX/node_modules/waterline/node_modules/async/lib/async.js:46:24)
    at Object.async.auto (XXX/node_modules/waterline/node_modules/async/lib/async.js:458:9)
    at new module.exports (XXX/node_modules/waterline/lib/waterline/model/lib/defaultMethods/save.js:42:9)
    at prototypeFns.save (XXX/node_modules/waterline/lib/waterline/model/index.js:34:14)
```

**Comment by particlebanana** [comment]
Nested updates were the worst thing we ever added to Waterline. If I could easily strip them out today I would do it in a heartbeat. Yes this whole problem is because you only have a single record in the population and the `sync` that happens when you call save will think there is only a single record.

For now remove the population before the `add` or `remove` and you will be safe. If someone has a use case for nested operations now is the time to state your case or they are getting ripped out.

**Comment by devinivy** [comment]
Cool!  Good to hear.  Thx for the quick response.  I think the nested update is reasonable, but I never use it.  The nested add/removes, though, don't seem needed.  When I comment that out my code works, but a test fails.  At first glance I think it'll be relatively easy to take that out.

**Comment by particlebanana** [comment]
It's all about the `save` method here. You have the whole object on the instance so when you call `.save` it's doing the nested `sync` stuff. That way when someone populates friends and then changes `person.friends[0].name = 'bob'` and then calls `person.save` it just works. If they were using a nosql database that's find but by making that work across all adapters you end up with a horrible mess.

**Comment by tjwebb** [comment]
Nested create is pretty useful for associations. I'm not clear on what's so different about nested update that makes it totally crazy.

**Comment by devinivy** [comment]
Updating doesn't require the `sync` craziness, is all.  One model can't assume that it's populated with every instance of a particular association if you're also allowing for criteria when populating an association (which seems to be a crucial feature).  Again, I don't mind the simple nested updates, but it seems like the sync needs to go–it's a data-ruiner!

**Comment by devinivy** [comment]
Posted a PR.

**Comment by particlebanana** [comment]
@devinivy thanks I'll take a look today. It's pretty big so I'll need to do some testing.

**Comment by Latros** [comment]
I posted in the sailsjs core google groups about what I think? might be us experiencing the same issue. It's the only kink remaining before our app can hit production :(

**Comment by devinivy** [comment]
Yes, I've had to limit access to certain API endpoints because of this too, which breaks some functionality.  Can you link to your post here?

**Comment by Latros** [comment]
it's technically a private google group but in case you get access: https://groups.google.com/forum/#!topic/sailsjs-core-team/UeNaTZ1cCxI

**Comment by dmarcelino** [comment]
@devinivy, can we close this one now?
