### ISSUE TITLE
can waterline add exec use like mongoose in koa

### ISSUE THREAD

**Issue by ckken** [balderdashy/waterline#864]
like this:
```javascript```
var list = yield D(R.c).find(map).sort(bysort).skip((page - 1) * perPage).limit(perPage).lean().exec();

````````

my project :https://github.com/ckken/koa-project/blob/master/controller/blog/common.js

**Comment by ckken** [comment]
I find it work for koa  example:
var data = yield app.models.user.find().toPromise()

**Comment by ptariche** [comment]
https://github.com/ptariche/koa-waterline
