### ISSUE TITLE
has bug when use unique

### ISSUE THREAD

**Issue by ckken** [balderdashy/waterline#869]
[Error (E_UNKNOWN) Encountered an unexpected error] Details:  MongoError: E110
00 duplicate key error index: weixin.user.$email_1  dup key: { : "ck22ken@wvovo.
com" }

**Comment by ckken** [comment]
[Error (E_VALIDATION) 1 attribute is invalid] Invalid attributes sent to undef
ined:
   • email
     • A record with that `email` already exists (`ck22ken@wvovo.com`).

**Comment by ckken** [comment]
app error Error (E_UNKNOWN) :: Encountered an unexpected error
MongoError: E11000 duplicate key error index: weixin.user.$email_1  dup key: { :
 "ck22ken@wvovo.com" }

**Comment by ckken** [comment]
defaults: {
            migrate: 'safe'
        }

**Comment by ckken** [comment]
"sails-mongo": "^0.10.5",

**Comment by ckken** [comment]
fixed it

**Comment by ckken** [comment]
use koa framework

**Comment by ckken** [comment]
it not return error json , return error in node cli

**Comment by Kikobeats** [comment]
first use the search, second go to #193

**Comment by dmarcelino** [comment]
@ckken what is the status of this? Is there still an issue? Your description is not very clear.

**Comment by devinivy** [comment]
If this doesn't move along in a week, I think we'll have to close this out.  @ckken is the issue that there's an uncaught error somewhere?
