### ISSUE TITLE
New adapter for ArangoDB

### ISSUE THREAD

**Issue by rosmo** [balderdashy/waterline#871]
Hello,

I just pushed a new adapter for Waterline: https://github.com/rosmo/sails-arangodb

**Comment by tjwebb** [comment]
Can you submit a PR to waterline-docs and add it to the list of community adapters? Thanks

**Comment by rosmo** [comment]
Looks like to the up to date list of adapters is on waterline (not -docs)? Did you mean that?

**Comment by tjwebb** [comment]
If that's where it is then my mistake. Yes.

**Comment by dmarcelino** [comment]
Thanks @rosmo!
