### ISSUE TITLE
Cannot use attribute `type: 'longtext'` because it always fails validation

### ISSUE THREAD

**Issue by cspotcode** [balderdashy/waterline#878]
Anchor doesn't have a validation rule for 'longtext', so if any of your model attributes have `type: 'longtext'`, they will always fail validation.

**Comment by dmarcelino** [comment]
Closing this as duplicate of balderdashy/anchor#71 (which should be fixed by balderdashy/anchor#73). Please reopen if the referred issue and PR don't fix this.
