### ISSUE TITLE
Add community adapter waterline-orientdb to documentation / readme

### ISSUE THREAD

**Issue by dmarcelino** [balderdashy/waterline#883]
Hi,

I finally feel [waterline-orientdb](https://github.com/appscot/waterline-orientdb) is ready for *prime time*, please add it to documentation / read me.

Pull requests:
* [x] #882 
* [x] balderdashy/waterline-docs#48
* [x] balderdashy/sails-docs#428
* [ ] balderdashy/sails#2740

I think I've covered all the places where community adapters are mentioned but let me know if I missed any page.

**Comment by tjwebb** [comment]
I support merging this.

**Comment by dmarcelino** [comment]
Thanks @tjwebb, @jub3i, @CWyrtzen and @particlebanana! Can we please also merge balderdashy/waterline-docs#48 and balderdashy/sails#2740? If you have any concerns with the PRs let me know and I'll address them.

**Comment by particlebanana** [comment]
Merged the waterline docs

**Comment by particlebanana** [comment]
and sails

**Comment by dmarcelino** [comment]
Nice, thanks @particlebanana!
