### ISSUE TITLE
autoMigrate only partially restores data

### ISSUE THREAD

**Issue by gotmikhail** [balderdashy/waterline#884]
Using `sails`, we get this error on `sails lift`. `Error: The hook `orm` is taking too long to load.` Ignoring the cause for that, the next thing that happens is we either lose our entire database (sometimes), or only partial.

It doesn't make a lot of sense that the orm took too long to load, but we were still able to wipe the database ... but that's a different issue.

The data logged to `stdout` was only partially restored. Looking at the printout, 

    ================================
    Data backup:
    ================================
    [
    { id: '1', appointment_users: '1', user_appointments: '10' },
    { id: '2', appointment_users: '1', user_appointments: '9' },
    { id: '3', appointment_users: '2', user_appointments: '8' },
    ...
    { id: '144', appointment_users: '70', user_appointments: '15' },
    { id: '145', appointment_users: '71', user_appointments: '39' },
    { id: '146', appointment_users: '71', user_appointments: '27' },
    { id: 147, appointment_users: 72, user_appointments: 27 },
    { id: 148, appointment_users: 72, user_appointments: 39 },
    ...
    { id: 333, appointment_users: 161, user_appointments: 41 },
    { id: 334, appointment_users: 161, user_appointments: 108 } ]

Seems like the individual records were not lost, but the `associations` between them.

Only about ~1/2 the records were restored. I noticed a pattern from stdout that some records were printed out in key/value pairs w/ the value quoted while others weren't. Looking at the example, it was actually the first 146 records (~1/2) that were printed correctly, the next half was printed w/ no values quoted. The properly structured records (w/ single quotes `'`) are what was restored, the rest were lost.

**Comment by particlebanana** [comment]
If you have any sort of data in the db you should be setting your migrate settings to `safe` and be using migrations. `alter` is really dumb and not made for anything with more than a few records in. @dmarcelino recently added a `create` migrate strategy to add columns that might be useful. I'll get that pushed to npm in the next day or so.

**Comment by particlebanana** [comment]
To clarify (maybe we need better docs) `alter` pulls all the data out of a table, drops it, re-creates it, and then re-inserts the data. It's really bad if you have any amount of data in there. I can't recommend https://github.com/BlueHotDog/sails-migrations/ enough. We need to just plaster it all over the docs.

Let me know if you have any questions @gotmikhail or where the docs were lacking.

**Comment by dmarcelino** [comment]
@particlebanana, idea for a future version of waterline: **manual migrations** (inspired in BlueHotDog/sails-migrations). This would imply expanding the adapter interface but would give the user a common interface across adapters. I bring this up because OrientDB also supports migrations and eventually I'll add support for them in `waterline-orientdb` (without a standardised interface).

**Comment by gotmikhail** [comment]
Completely understand the danger of `alter`. We have it disabled by default even in a development `env`. I just found it interesting that the records were printed out differently, some key/value pairs w/ the value quoted, followed by a set without, and all the pairs quoted were restored whereas the next sequence was not.
