### ISSUE TITLE
Can I use Custom Types to create a PostGIS geometry data type?

### ISSUE THREAD

**Issue by kevbaker** [balderdashy/waterline#886]
I'm hoping to use the "Custom Types" features to make a PostGIS geometry data-type. Is this possible

**Comment by devinivy** [comment]
Yes, it is.  The "custom type" is really just custom validation.  It's typically up to the adapter to understand the attribute's type and properly store it in the database.  Which adapter are you using?

**Comment by dmarcelino** [comment]
Please reopen if you feel the answer wasn't adequate.
