### ISSUE TITLE
migrate: 'alter' when using Waterline standalone

### ISSUE THREAD

**Issue by davidhq** [balderdashy/waterline#887]
I got bitten by this gotcha and lost (development) data...

I and some others on gitter chat think default should be `migrate: 'safe'`

https://github.com/balderdashy/waterline/blob/63effdb480ae9bd61cd78fd534e1e513294bd98d/lib/waterline/collection/defaults.js

@dmarcelino edit: this issue has been split into 2 parts (check the below [comment](https://github.com/balderdashy/waterline/issues/887#issuecomment-84045351)):
 - [x] Prevent users from using alter/drop in production by throwing an error. That way they can fix their config: #893
 - [ ] Change default migration to `'safe'` (or `'create'`)

**Comment by robertbak** [comment]
Applies to production to.
See this TODO`s: 
https://github.com/balderdashy/waterline/blob/25ccb99e92ea018ca832bd4497af903c4212b34e/lib/waterline/adapter/sync/strategies/alter.js#L22
https://github.com/balderdashy/waterline/blob/25ccb99e92ea018ca832bd4497af903c4212b34e/lib/waterline/adapter/sync/strategies/drop.js#L20

**Comment by davidhq** [comment]
Something else I'd like to add... since I'm using this separately from Sails, I will use the exact same code / setup on production... 

So I think this really should not be the default...

**Comment by dmarcelino** [comment]
I believe a good candidate for a default migration strategy in Waterline standalone is `migrate: 'create'` (#846). It's on master branch and it hasn't been released yet. `'create'` has the advantage of creating tables when one first launches waterline and it never deletes any data. It will also create any missing tables/columns in subsequent initialisations. It can be seen as *safeish* alter migration.

**Comment by devinivy** [comment]
I would vote for `'safe'`

**Comment by particlebanana** [comment]
I'm cool with either `safe` or `create`. The tricky part is when you start with:

```javascript
username: {
    type: 'string'
}
```

and then change it later to:

```javascript
username: {
    type: 'string',
    unique: true
}
```
With `alter` it would pull the data out and make sure these indexes get built. To be honest for sql databases we switched to migrations long ago on our projects so mine is set to `migrate: 'safe'` from the start but I'll let you guys choose whatever works best for your use cases and we can set that as the default. Losing data is bad and if what we have now isn't working for people it's an easy change.

**Comment by dmarcelino** [comment]
Regarding @robertbak's [comment](https://github.com/balderdashy/waterline/issues/887#issuecomment-81255895), I've created PR #893 which will prevent drop/alter migrations from running on production. Pretty simple changes:
```javascript
  // Refuse to run this migration strategy in production.
  if (process.env.NODE_ENV === 'production'){
    return cb();
  }
```
I don't think we need new tests for them.

@particlebanana, that's the downside of `'create'`, it only performs additive changes. I do wonder if we can improve `alter`, maybe by delegating some of its work to the adapter?

**Comment by devinivy** [comment]
Just to entertain the thought: does this silent loss of (dangerous) functionality warrant a breaking change or at least some sort of error for the developer?

Also @particlebanana, is there a way I'm not aware of to override the Waterline default migration strategy across all models?  Based upon what you said, it seems like there may be.  I think I heard that sails does this, but does WL itself?

**Comment by dmarcelino** [comment]
@devinivy, currently it would silently prevent the migration from happening if NODE_ENV is set to 'production' without breaking any other behaviour. It's not throwing an error nor logging anything. That's actually something I'm not sure which is the best way to deal with as this code is ran for all collections, so it can potentially throw a lot of output... Throwing an error has the annoying effect of preventing the app from starting even if no changes have been done to the schema. What do you think it's the best behaviour?

Regarding your second question, you can pass a "defaults" object to waterline when you initialise it:
```javascript
var options = {
  adapters: {...},
  connections: {...},

  // you can override adapter default options
  defaults: {
    migrate: 'safe',
  }
}

waterline.initialize(options, cb);
```

I don't think it's documented anywhere apart from adapters READMEs.

**Comment by devinivy** [comment]
What if we instead changed the default for production to `"safe"`?  That seems like a way to leave the (dangerous) functionality should someone want to use it and avoid the necessity of a failure or logging if someone alters/drops on prod.

**Comment by dmarcelino** [comment]
I still think it's really 2 different issues:
1. Change default away from `'alter'`: everyone agrees on this one :white_check_mark: ;
2. Prevent users from using `'alter'`/`'drop'` in production: even with the default set to `'safe'` it's possible for someone to screw up, copy a config from dev and lose production data (that person probably doesn't deserve their job :smile: ) :question: .

**Comment by devinivy** [comment]
Ah!  Gotchya.  In that case, my take would be to,
1. Set default to `"safe"`.
2. Prevent users from using alter/drop in production by throwing an error.  That way they can fix their config.  Given that the default is `"safe"`, the error would only occur if their configuration is broken.

If we weren't changing the default, it would be more unclear to me whether to throw an error or silently skip migration.  Since we are changing the default, an error seems appropriate.

**Comment by dmarcelino** [comment]
1. Changing the default itself is easy ([defaults.js#L8](https://github.com/balderdashy/waterline/blob/master/lib/waterline/collection/defaults.js#L8)), but the fixtures in [waterline-adapter-tests](https://github.com/balderdashy/waterline-adapter-tests) will need to be updated at the same time otherwise the tests break;
2. Throwing error in commit 113dab2 (PR #893).

**Comment by dmarcelino** [comment]
PR #893 has been merged, the only thing standing is changing the default migration.

**Comment by tribou** [comment]
Forgive me if I'm missing something obvious, but what strategy are you supposed to use with waterline to migrate a production schema with a SQL adapter?  [Sequelize-CLI](http://docs.sequelizejs.com/en/latest/docs/migrations/) or gulp tasks, etc??

**Comment by particlebanana** [comment]
@tribou we use https://github.com/BlueHotDog/sails-migrations and it's worked out really well

**Comment by tribou** [comment]
Thanks @particlebanana!  Looks like a good defined migration option.

**Comment by devinivy** [comment]
@dmarcelino do you remember what needs to be done to close this out, regarding changing the default strategy and corresponding tests?

**Comment by dmarcelino** [comment]
@devinivy, take a look at #962 and balderdashy/waterline-adapter-tests#50. Those should do it.

**Comment by dmarcelino** [comment]
BTW @devinivy, this is slightly off topic but I just noticed that the integration tests have 2 new broken sails-mysql tests:
* Association Interface Has Many Association create nested associations() with single level depth and objects should create a new customer and payment association
* Association Interface 1:m association :: .update() update nested associations() with single level depth when associations already exist should reset associations with the updated associations

Build: https://travis-ci.org/balderdashy/waterline-adapter-tests/jobs/57844170#L548

This suggests that some unreleased change in waterline (from these [13 commits](https://github.com/balderdashy/waterline/compare/v0.10.21...master)) have caused it. I don't have MySQL installed on my machine so it's not easy for me to say which one caused it.

**Comment by devinivy** [comment]
@dmarcelino feeling pretty sure it's just about this change https://github.com/balderdashy/waterline/compare/v0.10.21...master#diff-762fb5e96b0c3cfe800c9025650adbb6R68 and assumptions around order that records are created.  Mind console.logging around those tests? :P

**Comment by dmarcelino** [comment]
@devinivy, regarding the above broken tests you were correct, I've just issued PR balderdashy/waterline-adapter-tests#52 which fixes them!
