### ISSUE TITLE
Tag Git versions 0.10.14 through 0.10.17

### ISSUE THREAD

**Issue by kevinburkeshyp** [balderdashy/waterline#890]
Tags make it really easy to browse back and forth between revisions. the `master` version reports 0.10.17, however the latest git tag is 0.10.13. It would be nice if you could tag versions.

`npm` has a tool for this; if you type `npm version [patch|minor|major]` it will increment the patch/minor/major version number, create a commit with the new version number, and a corresponding git tag.

(I suspect this is also why half of the git tags begin with `v` and half of them do not.)

**Comment by devinivy** [comment]
I'm seeing tags for 0.10.15 through 0.10.17 here: https://github.com/balderdashy/waterline/tags
Do you agree that only 0.10.14 needs a tag, or am I misunderstanding?  (Also, looks like 0.10.11 does not have a tag.)

**Comment by particlebanana** [comment]
Looks like we are missing `0.10.11` and `0.10.14` but the rest are there. Didn't realize I sometimes put a `v` in front though...whoops! @kevinburkeshyp where are you seeing that last tag at `0.10.13`?

**Comment by kevinburkeshyp** [comment]
Just realized I might have had pulled master /still had outdated tags locally.. whoops. Thanks for fixing.
