### ISSUE TITLE
Embedded association creates duplicate data 

### ISSUE THREAD

**Issue by dylanbathurst** [balderdashy/waterline#892]
I've been reading other [issue threads](https://github.com/balderdashy/sails-mongo/issues/44) talking about embedded documents, as well as looking through the code to see where this is happening but couldn't find an answer.

It seems as though I can create two models with an association between them, and create the two new documents (using sails-mongo) at the same time with one object of values. Ex:

```
// models/User.js
// models/Pet.js
```
```
// controllers/UserController.js
var UserWithPet = {
    name: 'Foo',
    email: 'foo@bar.com',
    pet: {
        type: 'dog',
        fluffyScore: 20
    }
};

User.create(UserWithPet)
       .exec(function () {})
```
What I expect to happen is for two documents to be created with an association between them like:

```
// user collection in mongo
{
  "id": 1,
  "name": "Foo",
  "email": "foo@bar.com"
}

// pet collection in mongo
{
  "id": 1,
  "type": "dog",
  "fluffyScore": 20,
  "userId": 1 // automagically associated for me somewhere
}
```

But what actually happens is:

```
// user collection in mongo
{
  "id": 1,
  "name": "Foo",
  "email": "foo@bar.com",
  "pet": {
    "type": "dog",
    "fluffyScore": 20
  }
}

// pet collection in mongo
{
  "id": 1,
  "type": "dog",
  "fluffyScore": 20,
  "userId": 1 // automagically associated for me somewhere
}
```

So it is working to create the two documents I want, but it's duplicating the pet data in the user document. Is this just part of the greater conversation about embedded documents or a bug, or am I just doing it wrong?

**Comment by tjwebb** [comment]
I would file an issue in the mongo adapter repository and link to this issue. The SQL-based adapters implement this by storing Pet and User in separate tables, but I'm not sure offhand how Mongo deals with this. The maintainers in the sails-mongo repository will be able to offer more clarity on this.

If anyone here has insight, though, feel free to jump in.

**Comment by devinivy** [comment]
This seems right to me!  I didn't know that sails-mongo supported this yet, however.  I thought it was in the works.  The idea of embedded documents is to sidestep the necessity of relational data, and to instead store the associated data directly on the record (by duplicating it).  Now when you update the pet record, it should use its automagically generated userId field to update the embedded pet record on the user with id 1.  This puts the onus on database writes to do work for you upfront instead of reads ad hoc.

1. Does that make sense?  Is that what you were trying to acheive by using embedded documents?
2. How are you able to configure use of embedded documents in sails-mongo?  It's not part of any docs.
3. When you update the pet does it update the embedded pet record on your user?

**Comment by dylanbathurst** [comment]
Thanks for the reply @devinivy. It is working properly I just needed a lesson in Mongodb modeling. After reading through this article http://docs.mongodb.org/manual/tutorial/model-embedded-one-to-many-relationships-between-documents/ I see why it's duplicating the data.

**Comment by devinivy** [comment]
Welcome!  @dylanbathurst do you mind sharing your model definition?  I'm curious how to get embeddings working with mongo.  Where did you find any sort of documentation for that?

**Comment by dylanbathurst** [comment]
I actually didn't find any documentation on them, hence my confusion and original question. My models have pretty straight forward 1-many relationships. 

```
// Owner.js
attributes: {
  ownerName: {
    type: 'string',
    required: true
  },

  pets: {
    collection: 'pets',
    via: 'ownerId'
  }
}

// Pet.js
attributes: {
  petName: {
    type: 'string',
    required: true
  },

  ownerId: {
    model: 'owner'
  }
}
```

And when I run `Owner.create(...)` and pass an object like:

```
var UserWithPet = {
    ownerName: 'Bill',
    pets: {
        petName: 'Skippy'
    }
};
```

It creates the user document with the embedded pet document as well as the pet document in the `pets` collection. I haven't yet tested if the embedded document and the individual one in the `pets` collection stay in sync when updated.

**Comment by devinivy** [comment]
I did not know that the mongo adapter did this without any further configuration–curious!

**Comment by dylanbathurst** [comment]
I just ran a couple test to see if I could update one document to see if the changes were reflected in the embedded document (and vice versa) but no luck. Only the document I was directly updating would change it's values in the db. the linked embedded document would not update.

**Comment by devinivy** [comment]
Thanks for testing this out!  Very bizarre :/  Do you mind asking about this over on the [sails-mongo](https://github.com/balderdashy/sails-mongo/issues) adapter and referencing back to this issue?
