### ISSUE TITLE
Bug: `contains: "%"` always matches every row, but it shouldn't

### ISSUE THREAD

**Issue by cspotcode** [balderdashy/waterline#899]
This code returns all rows, but it shouldn't:
```
MyModel.find().where({name: {contains: "%"}}).exec(//...
```

I'm using MySQL.  EDIT: I can also confirm this behavior using blueprints and hitting the following URL:
`.../api/user?where={%22name%22:{%22contains%22:%22%25%22}}`

Possibly related to #802.

This function calls `normalize.likeCriteria`.  It seems to have been written in a hurry since the usage message is for `startsWith`, not `contains`.  Presumably `likeCriteria` should be escaping percent signs, but it's not.
https://github.com/balderdashy/waterline/blob/4653f8a18016d2bcde9a70c90dd63a7c69381935/lib/waterline/query/finders/helpers.js#L61-L72

Here's `likeCriteria`:
https://github.com/balderdashy/waterline/blob/912734b0fbb05d179d7183c0932b83c8010cf4bc/lib/waterline/utils/normalize.js#L267-L286

This function is never called; not sure why: https://github.com/balderdashy/waterline/blob/4653f8a18016d2bcde9a70c90dd63a7c69381935/lib/waterline/utils/normalize.js#L383-L386
EDIT: also that function doesn't make sense to me.  It will not touch percent signs at the beginning or end of the string, it won't touch adjacent percent signs, and it won't prefix percent signs with a backslash.

**Comment by dmarcelino** [comment]
Hi @cspotcode, I'm not sure this is a waterline core issue, it looks more like a [waterline-sequel](https://github.com/balderdashy/waterline-sequel) (which is used by sails-mysql) issue. Check:
https://github.com/balderdashy/waterline-sequel/blob/master/sequel/lib/criteriaProcessor.js#L623-L645

@tjwebb, what do you think?

**Comment by cspotcode** [comment]
In that case, what is the purpose of the waterline code I found?  Is it not being used?  I unfortunately don't have time to do more debugging or write a fix.  This bug does affect my work, so I will be grateful for a fix to be implemented.

Thanks in advance.

**Comment by dmarcelino** [comment]
I honestly can't tell as I am myself getting acquainted with it. But I don't think waterline core would be able to do this escaping as it supports all kind adapters, of which many are not SQL.

**Comment by randallmeeker** [comment]
I'm not sure I see the error 

```Model.find().where({name: {contains: "%"}})``` this based on looking it it would generate the follow sql statement ```select * where name like '%'```

This is valid SQL and does return all records. It may be not be ideal, but its valid.

**Comment by cspotcode** [comment]
Yeah, I know it's valid SQL, but is it the valid & intended behavior for waterline's "contains" query?  Waterline is a multi-DB ORM that claims you can use the same queries with any supported DB, without modification.  If I say 'contains': '100%', what does that mean?  Does it mean I'm looking for an attribute containing the string "100%"?  Will it behave the same way in MySQL, sails-disk, and MongoDB?  What about the meaning of "_"?  Of ".", "^", or "$"?

From the sails documentation (http://sailsjs.org/#!/documentation/concepts/ORM/Querylanguage.html)

> The Waterline Query language is an object-based criteria used to retrieve the records from any of the supported database adapters. This means that you can use the same query on MySQL as you do on Redis or MongoDb. This allows you to change your database without changing your code.

...and further down:

> #### 'contains'
> A shorthand for pattern matching both sides of a string. Will return records where the value contains the string anywhere inside of it.
>
>     Model.find({ class: { 'contains': 'history' }})
>     // The same as
>     Model.find({ class: { 'like': '%history%' }})

"where the value contains the string anywhere inside of it."  No mention of SQL-specific behavior.

Unless I'm mistaken, the Mongo adapter does things differently, and does not convert all `%` into `.*`:

https://github.com/balderdashy/sails-mongo/blob/1e7f2e1d3798fcf0a510455d54cbacd0f7a0125f/lib/query/index.js

Waterline claims to implement a consistent interface across databases, but it doesn't.  It should either update the docs to explain the differences, update the docs to explain the "%" and "_" wildcard matching, or normalize behavior across DB backends.  I'm not sure which is the bug, but either way there's a bug.

**Comment by randallmeeker** [comment]
i get you, my bad

```Model.find().where({name: {contains: "%"}})``` should be generating the following SQL then ```select * where name like '%/%%'``` where it escapes the percent and encapsulates it. Intead its not escaping the reserved characters and giving us ```like %%%```

That code you found https://github.com/balderdashy/waterline/blob/4653f8a18016d2bcde9a70c90dd63a7c69381935/lib/waterline/utils/normalize.js#L383-L386
would fix it, but in reality it should be escaping all reserved characters, not just %. 

That code not withstanding it is a  a waterline-sequel issue. Agreed that it is confusing with the odd code in waterline.

**Comment by cspotcode** [comment]
Tiny nitpick, just to clarify: the generated SQL should use a backslash instead of a forward slash, so `select * where name like '%\%%'` 

In MySQL LIKE queries the underscore also has a special meaning, so it should be replaced with `\_`.

**Comment by randallmeeker** [comment]
@cspotcode yup, my bad.

**Comment by dmarcelino** [comment]
@cspotcode, @randallmeeker, this has been raised in balderdashy/waterline-sequel#33, please continue the discussion there.
