### ISSUE TITLE
Update references to the OrientDB adapter

### ISSUE THREAD

**Issue by dmarcelino** [balderdashy/waterline#900]
Hi,

The developers of existing OrientDB adapters agreed to collaborate on a single adapter and as such
[sails-orientdb](https://github.com/appscot/sails-orientdb) is currently the *de facto* OrientDB adapter. Please update all references in the docs to reflect this and save users the confusion (and headache).

Pull requests:
* [x] #901
* [x] balderdashy/sails#2789
* [x] balderdashy/sails-docs#442

**Comment by dmarcelino** [comment]
Thanks @jub3i!

**Comment by jub3i** [comment]
glad to be of service @dmarcelino , keep up the good work :)

**Comment by tjwebb** [comment]
merged in balderdashy/sails

**Comment by dmarcelino** [comment]
Thanks @tjwebb! :D
