### ISSUE TITLE
orm hook takes too long to load when using sails-mongo

### ISSUE THREAD

**Issue by mkeremguc** [balderdashy/waterline#904]
i have ~150 models.
```
config/local.js:
 models: {
     connection: 'mongo',
     migrate: 'safe'
 }
```
`sails lift --silly` logs the last model as `silly: Registering model `user` in Waterline (ORM)` and waits there about 6-7 minutes using 100% CPU then goes to next hook (grunt) and finishes lifting.

what i tried so far:
1. disable grunt hook: same
2. disable views etc: same
3. sails-disk as adapter: no problems there and lifts fast enough
4. sails-postgresql as adapter: no problems there and lifts fast enough

using:
nodejs v0.10.37
sails v.0.11.0
waterline v0.10.19
sails-mongo v0.10.6

not sure if it is adapter issue so posted here.

**Comment by particlebanana** [comment]
Do you have lots of data in the mongo database? By default it has an `alter` migration set. With mongo just set `migrate: safe` in `config/models.js` if you are using Sails.

**Comment by mkeremguc** [comment]
no i don't have lots of data it is blank database. also it is set `migrate: safe` in config/models.js

**Comment by mkeremguc** [comment]
some debug and i found where it takes time:
node_modules/sails-mongo/lib/collection.js line 358: `collectionDef = _.cloneDeep(definition);`
in _parseDefinition function, it deep clones the definition object which is a circular structure that has `waterline` attribute that has `collections` and `schema` attributes. that `definition` is just a key of waterline.collections attribute itself. so deep cloning that big circular structure takes time on every model and makes orm hook take too long. removing clone and just referencing like `collectionDef = definition` fixed the issue. however, this needs feedback for a permanent fix on sails-mongo adapter. lemme know if i should open this issue in sails-mongo

**Comment by dmarcelino** [comment]
Thanks for investigating @mkeremguc! I've moved this to balderdashy/sails-mongo#253, please add any other further comments there!
