### ISSUE TITLE
How does one mock a waterline model in tests?

### ISSUE THREAD

**Issue by sfabriece** [balderdashy/waterline#910]

**Comment by dmarcelino** [comment]
Hi @sfabriece, depending on what you want to do you should be able to do something like:
``` javascript
var modelMock = {
  find: function(){
    return { name: "john doe"};
  },
  update: function(){ /*...*/},
  create: function(){ /*...*/},
  destroy: function(){ /*...*/},
  etc: function(){ /*...*/}
}
```
Or am I misunderstanding your question?

**Comment by sfabriece** [comment]
@dmarcelino Thanks for the feedback.
I also have a question on performance of waterline, compared to the MySQL module?

**Comment by dmarcelino** [comment]
I can't help you there as I don't use the MySQL module but many people use Sails which uses Waterline so it shouldn't be too bad. More on sails performance on this gitter chat: [March 30 2015 4:04 AM](https://gitter.im/balderdashy/sails?at=5518bd21ce384d5975425888) (a bit long but probably worth it).
