### ISSUE TITLE
association data corruption

### ISSUE THREAD

**Issue by anasyb** [balderdashy/waterline#911]
This issue is tough one. I was creating a function to setup some demo data, and was testing things before converting it to async.series... when I stumbled over big data corruption:
First I setup main user, and then in another ```user.create``` setup some more users, and in a third post.create and post.update added posts to all of them... seems like the code for adding the posts was running while the other code was still running... very strangely ended up in all posts (25 in total) being assigned owner as main user... when in no command what so ever I assigned them to that user!!

While I got what I want for demo data once I made it all run in an async.series... the above could happen over http and such a corruption is crazy scary!! Those posts belonging to users who are in the process of being created should never got assigned to the main user?!

Sounds similar to https://github.com/balderdashy/waterline/issues/877 but not so sure its the same.

With mongo, waterline 0.10.18.

**Comment by dmarcelino** [comment]
@anasyb, can you provide a failing test so this can be reproduced?

**Comment by anasyb** [comment]
Thanks! Yes I wanted to... but this is a tough one to disentangle from particulars of my project... let me see what I can do..

**Comment by dmarcelino** [comment]
Thank you.

**Comment by devinivy** [comment]
Yes, I expect my PR #889 ought to fix this.  It's not so much an issue with high-frequency traffic as it is an issue with multiple association updates in the same tick, as far as I can tell.  The short-term patch is probably to wrap `Model#save` and `Collection#update` calls in `setTimeout`.  I hope my PR will go through soon to fix this issue!  @anasyb do you mind seeing if that PR fixes the issue?

**Comment by anasyb** [comment]
@devinivy you're right... I was just able now to re-create it with very low frequency... this is really a terrible bug all my associations got mixed up randomly... hope your PR fixes it, checking it now!
If so will close this one and keep the discussion in #877

**Comment by anasyb** [comment]
@devinivy very unfortunately the PR doesn't solve the issue. I ended up with so many records with association set to something when I never set it. I replaced the ```update.js``` with the one from your PR, and threw some breakpoints to make sure its being called... but no luck.
I didn't wrap my head on the issue of the PR, but just guessing: could it be the case that a similar problem persists in ```create```?

**Comment by devinivy** [comment]
The PR is a fix for high-frequency updates used to sync associations.  I can't make that work incorrectly any more.  But there could be another bug kicking around here.  Does it seem like your main issue is with `create`?

**Comment by devinivy** [comment]
Here's the model created to make the associations during `create`: https://github.com/balderdashy/waterline/blob/e9b618fe0910dd4ffc4a9e4af43a494592c4e9ff/lib/waterline/query/dql/create.js#L225

And here are the associations being created: https://github.com/balderdashy/waterline/blob/e9b618fe0910dd4ffc4a9e4af43a494592c4e9ff/lib/waterline/utils/nestedOperations/create.js 

Looks alright to me at first glance.

**Comment by dmarcelino** [comment]
@anasyb, @devinivy created a really nice test to reproduce the nested update issue: https://github.com/balderdashy/waterline-adapter-tests/pull/42/files.

Based on that, do you think you can come up with one for the nested create issue? It would make it much easier to find the root cause. Thanks.

**Comment by anasyb** [comment]
cool... 
- I confirm that the PR solves the initial issue I had, namely when I was running assoc updates in parallel. The PR is really awesome and critical, I hope it get merged soon.
- I can't pin point the issue happening with more complex setup involving many create/update... am so much behind schedule so doing lot of catching... but will dig into it as soon as I can

**Comment by anasyb** [comment]
ok guys... so it turned out to be a combination of what the PR solved + something wrong with multiple `findOrCreate` coming in together. I guess I'll close this issue and open another one for the `findOrCreate`.
