### ISSUE TITLE
(bug) N-N assoc don't sync

### ISSUE THREAD

**Issue by anasyb** [balderdashy/waterline#912]
Somehow related to https://github.com/balderdashy/waterline/issues/907# but this time with many to many. I have to manually update both sides in order for them to stay in sync:

```javascript
//User model
...
groups: {
    collection: 'workgroup',
    via: 'members',
    dominant: true
},
...

//Workgroup model
members: {
    collection: 'user',
    via: 'groups'
},
```

Now in action:
```javascript
//get members into workgroup, but does NOT sync User records
Workgroup.update({id:"10"},{members:["1","2","3","4"]}).exec(cb)

//have to do this in order to sync
User.update({"id" : "1"}, {groups:[10]}).exec(cb);
User.update({"id" : "2"}, {groups:[10]}).exec(cb);
User.update({"id" : "3"}, {groups:[10]}).exec(cb);
User.update({"id" : "4"}, {groups:[10]}).exec(cb);
```

With this N-N issue, https://github.com/balderdashy/waterline/issues/911, https://github.com/balderdashy/waterline/issues/907, https://github.com/balderdashy/waterline/issues/908 in less than 48 hours, not to mention the >1yr old https://github.com/balderdashy/waterline/issues/317... associations has been a nightmare for me... its either too buggy to be useful or I should increase the caffeine intake... am almost quitting on sails, just can't seem to get work done!

waterline 0.10.18 w/ mongo

**Comment by particlebanana** [comment]
@anasyb do you have anything special going on with the `id` fields on your models? In the example above it works for me if I use the default mongo id's that get generated on the model.

**Comment by anasyb** [comment]
Nothing special, though I am specifying exactly what the id is. Here exactly how my demo data code looks like (i removed other associations that are going on):

```javascript
var tasks = [];
/**
*	CREATE
*/

//create main user
tasks.push(function(cb){User.create({"id" : "54e8cc422acb5e5b03d5c845","firstName" : "Kitten","lastName" : "Handsome"}).exec(cb);});

//create fellow users
tasks.push(function(cb){User.create([{"id" : "54ee20a72acb5e5b03d5c8a0","firstName" : "User2","lastName" : "User2"},{"id" : "54ee20a72acb5e5b03d5c8a1","firstName" : "User3","lastName" : "User3"},{"id" : "54ee20a72acb5e5b03d5c8a2","firstName" : "User4","lastName" : "User4"}]).exec(cb);});


//create workgroup
tasks.push(function(cb){Workgroup.create([{"id" : "54ee23b82acb5e5b03d5c8a3", "fullName":"Kittens club"}]).exec(cb);});


/**
*	UPDATE ASSOCIATIONS
*/

//update workgroup with members
tasks.push(function(cb){Workgroup.update({id:"54ee23b82acb5e5b03d5c8a3"},{members:["54e8cc422acb5e5b03d5c845","54ee20a72acb5e5b03d5c8a0","54ee20a72acb5e5b03d5c8a1","54ee20a72acb5e5b03d5c8a2"]}).exec(cb);});


//WITHOUT this it does NOT sync both
tasks.push(function(cb){User.update({"id" : "54e8cc422acb5e5b03d5c845"}, {groups:["54ee23b82acb5e5b03d5c8a3"]}).exec(cb);});
tasks.push(function(cb){User.update({"id" : "54ee20a72acb5e5b03d5c8a0"}, {groups:["54ee23b82acb5e5b03d5c8a3"]}).exec(cb);});
tasks.push(function(cb){User.update({"id" : "54ee20a72acb5e5b03d5c8a1"}, {groups:["54ee23b82acb5e5b03d5c8a3"]}).exec(cb);});
tasks.push(function(cb){User.update({"id" : "54ee20a72acb5e5b03d5c8a2"}, {groups:["54ee23b82acb5e5b03d5c8a3"]}).exec(cb);});
//END WITHOUT


async.series(tasks, function(){console.log("Demo data init done!")});



//this works even if we didn't run the WITHOUT block
Workgroup.findOne("54ee23b82acb5e5b03d5c8a3").exec(function(err, group){
	console.log(group.members.length);//=> 4
});

User.findOne("54e8cc422acb5e5b03d5c845").exec(function(err, user){
	console.log(user.groups.length);//=> 0 if we didnt't run WITHOUT block; => 1 otherwise
});
````

**Comment by particlebanana** [comment]
Hmm not sure how you would be getting `members` back in this line without a populate:

```javascript
Workgroup.findOne("54ee23b82acb5e5b03d5c8a3").exec(function(err, group){
    console.log(group.members.length);//=> 4
});
```

Are your models different than the ones posted above? If you are getting data back there the associations aren't setup correctly and it's doing a sort of embedded association that isn't supported.

Running this script works for me on the latest sails-mongo and waterline: https://gist.github.com/particlebanana/f199ecf93af91af46b10. I threw it in a controller but it could live anywhere.

**Comment by anasyb** [comment]
Thanks for the promptness!
- No, association definitions are copy paste from my model files and are defined exactly like in your link. 
- In that line I am not getting the full records, just the array of pk. And after running the WITHOUT block I also get the array of pk when querying User as mentioned above.
- I think we have different definitions for "works for me"... for me if I am getting an array, but an empty one, for the associated pk (like userRecord.groups and groupRecord.members) it tells me there are no associated records. If that's for some crazy reason isn't how waterline logic is, at least it should consistently be an empty array.

**Comment by particlebanana** [comment]
When you define a "collection" attribute it's a virtual attribute. When you run the query without populate you should only get back an attribute for `members` with a getter/setter not an array. So anytime you get a value back it's not working as expected, whether thats an empty array or an array with pk values. 

If you look in the database none of your `user` or `workgroup` records should have an attribute for `groups` or `members`. All the records should be in the join table. Waterline doesn't support mongo embedded associations so it treats it like a relational database.

When you query Workgroup without `populate` you should get this back:

```javascript
{ fullName: 'Kittens club',
    createdAt: Sun Mar 29 2015 14:18:21 GMT-0700 (PDT),
    updatedAt: Sun Mar 29 2015 14:18:21 GMT-0700 (PDT),
    id: '54ee23b82acb5e5b03d5c8a3' }
```

and same for user:

```javascript
{ firstName: 'Kitten',
    lastName: 'Handsome',
    createdAt: Sun Mar 29 2015 14:18:21 GMT-0700 (PDT),
    updatedAt: Sun Mar 29 2015 14:18:21 GMT-0700 (PDT),
    id: '54e8cc422acb5e5b03d5c845' }
```

**Comment by anasyb** [comment]
isArray(group.members) is returning true... it's an array of PKs, and also has two special functions: add and remove

>If you look in the database none of your user or workgroup records should have an attribute for groups or members....

Indeed, they shouldn't, yet they do. That's in addition to the presence of ```user_groups__workgroup_members```.

> When you query Workgroup without populate you should get this back:

Do you mean *before* calling ```toObject```? The arrays am getting are on the raw record passed to the callback of ```.exec```.

I will remove sails module and npm install.

**Comment by anasyb** [comment]
Re-installed completely sails, and updated sails-mongo 0.10.5 to 0.10.6.. dropped the whole db and re-run the demo data commands... same issue, and mongo collections are having array of PKs in them.

**Comment by anasyb** [comment]
@particlebanana I just noticed you're using ```res.json(group);``` in your gist to test... that would result in a call to toObject which would obviously omit the arrays. 

Can you instead call ```console.log(group.members);```

**Comment by particlebanana** [comment]
Do you have anything that's using the native mongo driver or a bootstrap file or another app that would be adding them? I just don't see how you could have the join table and the arrays on the records. 

The `toObject` stuff is the same, just leaves in the getter/setter for calling `.add` and `.remove` on the virtual collection. If I look in the db I don't have arrays on those records.

A test to narrow it down some would be to switch to sails-disk and see if you get the same results.

**Comment by anasyb** [comment]
I have nothing of that.
I just created a new project and copy/pasted the code in your gist. Dropped the whole db. Did:
```
sails> demo.run()
```
My workgroup collection ended up like this:

```javascript
{
    "_id" : ObjectId("54ee23b82acb5e5b03d5c8a3"),
    "fullName" : "Kittens club",
    "createdAt" : ISODate("2015-03-30T01:53:01.811Z"),
    "updatedAt" : ISODate("2015-03-30T01:53:01.833Z"),
    "members" : [ 
        "54e8cc422acb5e5b03d5c845", 
        "54ee20a72acb5e5b03d5c8a0", 
        "54ee20a72acb5e5b03d5c8a1", 
        "54ee20a72acb5e5b03d5c8a2"
    ]
}
```
and sails console looks like this
```javascript
sails> demo.run()
undefined
sails> [ '54e8cc422acb5e5b03d5c845',
  '54ee20a72acb5e5b03d5c8a0',
  '54ee20a72acb5e5b03d5c8a1',
  '54ee20a72acb5e5b03d5c8a2',
  add: [Function: add],
  remove: [Function: remove] ]
4
```
uploaded the project [here](https://github.com/anasyb/sails-assoc-test).

**Comment by particlebanana** [comment]
Ok yeah I see it. Not sure why it's happening but if you force mongo to use the schema it works. So setting `schema: true` in `config/models.js` fixes it up. I created an issue in [sails-mongo](https://github.com/balderdashy/sails-mongo/issues/254). I just added @mgenev as a core contributor to the mongo adapter so he can give it a peek and see whats up.

**Comment by mgenev** [comment]
I will take a look this weekend
