### ISSUE TITLE
WLError getter for "stack" breaks bluebird

### ISSUE THREAD

**Issue by tjwebb** [balderdashy/waterline#913]
https://github.com/balderdashy/waterline/blob/master/lib/waterline/error/WLError.js#L146-L148

see https://github.com/petkaantonov/bluebird/issues/552

Bluebird needs to be able to set the `.stack` property on `WLError` but is unable to do so

**Comment by tjwebb** [comment]
Looks like using `__defineGetter__` is just generally a bad idea anyway: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/__defineGetter__

**Comment by petkaantonov** [comment]
This shouldn't break bluebird as of 2.9.21

**Comment by devinivy** [comment]
Thanks for chiming in, @petkaantonov !  We should update the WL dependency to reflect that, and also make a change here to avoid using `__defineGetter__`.

**Comment by tjwebb** [comment]
I already started work on this, which includes a needed refactor anyway.

Thanks for your input @petkaantonov
