### ISSUE TITLE
Dead Code?

### ISSUE THREAD

**Issue by randallmeeker** [balderdashy/waterline#915]
This started here https://github.com/balderdashy/waterline/issues/899

Is this code necessary or used in Waterline because it seems very SQL specific?

https://github.com/balderdashy/waterline/blob/4653f8a18016d2bcde9a70c90dd63a7c69381935/lib/waterline/query/finders/helpers.js

**Comment by dmarcelino** [comment]
I don't know, but if it helps, when I run a code coverage report (`npm run coverage`), I see 100% line coverage which means the automated tests are hitting every single line of that code.

PS: I had to add the below code to `waterline/test/adapter/runner.js` to get the full coverage report:
``` javascript
    // Mocha options
    // reference: https://github.com/mochajs/mocha/wiki/Using-mocha-programmatically
    mocha: {
      reporter: 'spec',
      grep: /findOrCreateEach|SQL injection/
    },
    
    mochaChainableMethods: {
      invert: 'true'
    }
```

**Comment by particlebanana** [comment]
Not dead, they are just helpers that call other other functions, `find` and `findOne`. The `%` symbol they add is a valid Waterline query modifier. We could remove them in `0.11` and we should also remove the dynamic finders in `0.11`.

**Comment by dmarcelino** [comment]
Regarding the coverage report I mentioned earlier, it's now possible to check it here: https://codeclimate.com/github/balderdashy/waterline/lib/waterline/query/finders/helpers.js

**Comment by dmarcelino** [comment]
Closing this for now as there is already a discussion about helpers and dynamic finders in #931. Please reopen if you feel otherwise.
