### ISSUE TITLE
autoIncrement doesn't work on non primary key fields

### ISSUE THREAD

**Issue by zeluis9** [balderdashy/waterline#916]
I currently do not know if this a design-spec or a bug. But with sails-mysql autoIncrement does not work on non primary fields..

**Comment by zeluis9** [comment]
My current workaround (that seems pretty ugly to me):

beforeCreate: function(myModel, next) {
    if(!myModel.id) {
 	    model.count(function(err,num) {
		    if(err){
			    next(err);
		    }
		    myModel.id = num + 1;
	    });
    } else {
	    next();
    }
}

**Comment by dmarcelino** [comment]
Hi @zeluis9, from what I can make of https://github.com/balderdashy/waterline-docs/blob/master/models.md#autoincrement:
> Will create a new auto-incrementing attribute. These should always be of type integer and will not be supported in all datastores. For example MySQL will not allow more than one auto-incrementing column per table.

This will only be responsible for signalling the adapter to mark the column as auto-incrementing in the schema. Was that your expectation? Did that not happen?

**Comment by dmarcelino** [comment]
Closing this for now, please reopen if you don't think the previous answer fully answers this question.

**Comment by zeluis9** [comment]
HI there. Sorry for the later answer. My model has only one auto-increment field(integer of course),  and with autoPK set to false. The column with autoIncrement set to true is not being incremented automatically and it's not being fulfilled at all.

**Comment by dmarcelino** [comment]
Hey @zeluis9, if you restart your waterline/sails instance using `migrate: 'drop'` or `'alter'` (on a development/test db where you can destroy the data) does the relevant MySQL table column become auto-incrementing in the schema?

If not, please raise an issue on the [sails-mysql project](https://github.com/balderdashy/sails-mysql) as this doesn't look like a waterline core issue.

**Comment by zeluis9** [comment]
Hi. I've tried that already. Not working... :s I'll raise an issue on sails-mysql. Thank you!
