### ISSUE TITLE
Truthy validation

### ISSUE THREAD

**Issue by kevinob11** [balderdashy/waterline#917]
The truthy validation is not working for me. I have the following attribute, which I expect to always fail validation, it does not, it consistently passes validation. Something I'm missing about custom validation functions?
```
test: {
  type: 'text',
  truthy: function() {
    return false;
  }
}
```

**Comment by kevinob11** [comment]
Hrm I'm thinking about this wrong aren't I? Is that function supposed to return the value to be evaluated or the boolean that represents whether or not you want your value to be truthy or not?

**Comment by dmarcelino** [comment]
Judging by the [code](https://github.com/balderdashy/anchor/blob/6c0c1edc1c88af857336b014a4508d93a8b33bf5/lib/match/rules.js#L76) it expects *the boolean that represents whether or not you want your value to be truthy or not*.

**Comment by kevinob11** [comment]
Thanks
