### ISSUE TITLE
Waterline adapter for Parse?

### ISSUE THREAD

**Issue by lance-anderson** [balderdashy/waterline#927]
Does anyone know if there is a Waterline adapter for Parse? 

I found this one:
https://www.npmjs.com/package/waterline-parse

But the GitHub page is a 404...

Has anyone out there used this adapter?

**Comment by dmarcelino** [comment]
I found [sails-parse](https://www.npmjs.com/package/sails-parse), repo https://github.com/murilopolese/sails-parse? Last commit was in Nov 5, 2013... I've also found https://github.com/tommy60703/sails-parse but doesn't seem to have a npm package and I'm not sure if it's a fork from the former. @lance-anderson, maybe you can contact the developers and even contribute? It would be great if the several developers involved could focus on a single high quality sails-parse adapter.

**Comment by devinivy** [comment]
If this isn't answered sufficiently, we can reopen the issue.  But that sounds good to me!
