### ISSUE TITLE
results of a security audit?

### ISSUE THREAD

**Issue by kevinburkeshyp** [balderdashy/waterline#936]
Has Waterline been subject to any type of professional security audit? For each (or any) backend has any verification been done to ensure that the library is not vulnerable to SQL injection?

**Comment by devinivy** [comment]
I'm unsure whether waterline or any organization using waterline has be audited in this way.  That said, I can tell you that this would be up to individual adapters to take care of primarily.  There is a [test](https://github.com/balderdashy/waterline-adapter-tests/blob/f0981e95fc3df9c9bdb2ecf2371f932a90119e23/interfaces/semantic/find.test.js#L73-L79) in the waterline adapter tests that deals with SQL injections.  I also know some community members would like to move community SQL adapters to use Knex behind the scenes.  Then waterline with a SQL adapter would be about as reliable as Knex security-wise.

**Comment by devinivy** [comment]
I see you opened an issue on the prostgres adapter here: https://github.com/balderdashy/sails-postgresql/issues/144
Would you like to close this out or leave it open for comment?

**Comment by dmarcelino** [comment]
balderdashy/sails-postgresql#144 seems to be progressing more, closing this for now, please reopen if you feel otherwise.
