### ISSUE TITLE
model.create - primaryKey

### ISSUE THREAD

**Issue by nitulkukadia** [balderdashy/waterline#943]
I have below model with primary key id:
attributes: {
  id: {
    type: 'integer',
    autoIncrement: true,
    primaryKey: true,
    unique: true
  },
  name: {
      type: 'string',
      unique: true,
      required: true
  },
}

I am creating model as below:
 var model = {
        id: undefined,
        name: 'name',
};
 waterlinemodel.create(model).exec(function(error, result) {});

But it throws below error:
Error (E_UNKNOWN) Encountered an unexpected error] Details:  error: null value in column "id" violates not-null constraint

As, 'id' is a primary key, waterline should not look at what is the value of 'id' property.

How to resolve this error? I do not want to remove 'id' because I have created value object for the model and it contains all the attributes of model.I am setting value object property as I need. I do not need to set id property for creation.

**Comment by dmarcelino** [comment]
Hi @nitulkukadia, instead of setting `id: undefined` have you tried not setting `id` at all? Which adapter are you using?

**Comment by nitulkukadia** [comment]
According to java script. If I do not define id or i assign value as undefine both are same. Still it gives me an error.

**Comment by dmarcelino** [comment]
That's not true, if you do something like:
``` javascript
var obj = {
  id: undefined,
  someProperty: 1
};
for(var key in obj) {
  console.log(key, obj[key];
}
```

You'll see that setting `id` to undefined it's different than not setting `id`.

Anyway you haven't told us which adapter you're using.

**Comment by nitulkukadia** [comment]
I am not using any adapter. I am just using a waterline model method to create model.

But blow code prints undefined for id and undefinedProperty.

var obj = {
  id: undefined,
  someProperty: 1
};
 console.log(obj.id);
 console.log(obj.undefinedProperty);

**Comment by tjwebb** [comment]
@nitulkukadia Just because console.log prints the same value does not mean and `undefined` value and a **missing** value are the same in Javascript. They are very different.

> As, 'id' is a primary key, waterline should not look at what is the value of 'id' property.

Are you filing this issue because you honestly want to set an actual database id to `undefined`? This is impossible, and is not something any ORM is going to support.

**Comment by devinivy** [comment]
@tjwebb I think that @nitulkukadia wants waterline to strip `undefined` properties.

**Comment by tjwebb** [comment]
A primary key cannot be undefined, or missing

Either way though, magically stripping undefined values would cover up a
lot of legit validation errors. If an undefined value makes some validation
fail, then I think it *should* fail.

**Comment by devinivy** [comment]
Yes, agreed!

**Comment by nitulkukadia** [comment]
@tjwebb   If an undefined value makes some validation
fail, then I think it *should* fail.

Yes it should fail the validation, you are right.
But I think: 
Update and delete operation can be performed by deletion based on id.
But, while creating model record in database, primary key never exist. Primary key created only after inserting record in database.
So, while creating, why waterline is looking for primary key.

**Comment by tjwebb** [comment]
> But, while creating model record in database, primary key never exist. Primary key created only after inserting record in database.

You're fundamentally mistaken about how databases work. There exists no database where you can define a `PRIMARY KEY` field and be able to insert a null/undefined value.

**Comment by devinivy** [comment]
I think @nitulkukadia is saying that it's some sort of auto-increment / uuid column that _will be_ assigned at the time of record creation by the database itself.  That said, I still think waterline needs to report a failure if the id is specified but not actually set.  After all, even in an auto-incrementing column you _can_ often set the primary key manually.

**Comment by tjwebb** [comment]
> After all, even in an auto-incrementing column you can often set the primary key manually.

Depends on the database. You cannot do this in SQL Server, for example. But even where you are allowed to manually set it, you still cannot ever set it to `null`.
