### ISSUE TITLE
Write and publish responsible disclosure policy

### ISSUE THREAD

**Issue by kevinburkeshyp** [balderdashy/waterline#945]
- If I find a critical vulnerability in the waterline codebase, how should I communicate it to the core team? 
- What guarantees are given about time to a patch? 
- Will reporters be credited for their work in finding a vulnerability?
- How are critical security vulnerabilities disclosed to the community? 
- Are vulnerabilities given a CVE number? 
- Once you write a page like this, [how can I be expected to find it][broken]?

[broken]: https://github.com/balderdashy/sails/issues/2594

Here is an example of what a page like this should look like: http://docs.python-requests.org/en/latest/community/vulnerabilities/

**Comment by particlebanana** [comment]
This would be great! We'll take a stab at getting something together soon.

**Comment by tjwebb** [comment]
@kevinburkeshyp Thanks for the suggestion. We'll continue the discussion here, which we'd apply to sails and waterline: https://github.com/balderdashy/sails/issues/2830
