### ISSUE TITLE
Condition in populate is not working.

### ISSUE THREAD

**Issue by sucheep-sri** [balderdashy/waterline#955]
Image.find().populate( 'user', {status : 'ban'} ).sort({ updatedAt: 'desc' }).exec(function(err, images){
    console.log(images);
});

I want to query image table that where user.status = 'ban'.
But my code is not working. It showed all image rows with all user.status.

**Comment by dmarcelino** [comment]
Hi @sucheep-sri, a couple of questions:
* which adapter are you using?
* Have you tried it without the `.sort()`? (wondering if `.sort()` is interfering with `.populate()`)

**Comment by sucheep-sri** [comment]
- I use sails-mysql.
- Yes, I have but it's still same.

**Comment by devinivy** [comment]
As-is your query should return every single image.  On each image should be the associated banned users.  Consider flipping your query around:
```node
Users.find({status: 'ban'}).populate('image').exec(function(err, users) {/* look at users[i].image */});
```
Related: https://github.com/balderdashy/waterline/issues/266

**Comment by dmarcelino** [comment]
Yes, @devinivy is right. Closing this for now, @sucheep-sri please reopen if it doesn't fully answer your question.
