### ISSUE TITLE
extra fields on many to many relationships join table (feature request)

### ISSUE THREAD

**Issue by elennaro** [balderdashy/waterline#957]
I didn't find solution in documentation so I suppose this feature is not implemented.
It's a widely used approach when we save extra data with relation.
Like quantity for sold products in order-product relation.
Like expiration on user-post-ban. etc. etc.

I'd also appreciate any help on how to do it manually.
I've even created a [question](http://stackoverflow.com/questions/29734488/sails-js-extra-fields-on-many-to-many-relationships-join-table), but no luck with a proper answer yet.

**Comment by dmarcelino** [comment]
Hi @elennaro, what you are asking for doesn't exist yet and it will (or should be) part of many-to-many through associations. Check #705 for checking the current status of through associations.

**Comment by elennaro** [comment]
Thannk you @dmarcelino.

**Comment by dmarcelino** [comment]
No worries, would you mind bringing that requirement on the #705 thread? I'd like keep all things related to through associations there and close this issue to keep everything tidy :)

**Comment by elennaro** [comment]
Sure, thanks again.
