### ISSUE TITLE
A way to make case insensitive queries

### ISSUE THREAD

**Issue by sahanDissanayake** [balderdashy/waterline#961]
Im trying to make case insensitive queries and It seems like Waterline does not like case sensitivity
https://groups.google.com/forum/#!topic/sailsjs/bydNURBmE8Q

**Comment by dmarcelino** [comment]
Hi @sahanDissanayake, this seems odd as all official adapters (including sails-postgresql) pass the case insensitive tests in [caseInsensitive.test.js](https://github.com/balderdashy/waterline-adapter-tests/blob/master/interfaces/queryable/caseInsensitive.test.js#L33). Can you try updating your sails-postgresql adapter to version 0.10.14 and waterline to v0.10.21 and try again?

**Comment by sahanDissanayake** [comment]
Thanks @dmarcelino  
Im using sails-mysql V 0.10.11
Sails V 0.10.5

I cannot see the waterline in my package.json file :confused:

**Comment by dmarcelino** [comment]
Waterline would be on Sails' package.json hence inside sails/node_modules. Still, sails-mysql passes the case insensitive tests I've mentioned earlier. Can you tell us which queries are you running and how your data looks like? Alternatively a failing test would be even better.

**Comment by sahanDissanayake** [comment]
These are my files

package.json
```javascript
{
  "name": "myApp",
  "private": true,
  "version": "0.1.0",
  "description": "a Sails application",
  "keywords": [],
  "dependencies": {
    "bcrypt": "^0.8.0",
    "ejs": "~0.8.4",
    "grunt": "0.4.2",
    "grunt-contrib-clean": "~0.5.0",
    "grunt-contrib-coffee": "~0.10.1",
    "grunt-contrib-concat": "~0.3.0",
    "grunt-contrib-copy": "~0.5.0",
    "grunt-contrib-cssmin": "~0.9.0",
    "grunt-contrib-jst": "~0.6.0",
    "grunt-contrib-less": "0.11.1",
    "grunt-contrib-uglify": "~0.4.0",
    "grunt-contrib-watch": "~0.5.3",
    "grunt-sails-linker": "~0.9.5",
    "grunt-sync": "~0.0.4",
    "include-all": "~0.1.3",
    "rc": "~0.5.0",
    "restler": "~3.2.2",
    "sails": "~0.10.5",
    "sails-disk": "~0.10.0",
    "sails-mysql": "~0.10.11",
    "skipper-s3": "~0.5.5",
    "skipper-s3-alt": "~0.1.0",
    "html-minifier": "~0.6.8",
    "ejs-locals": "~1.0.2"
  },
  "scripts": {
    "start": "node app.js",
    "debug": "node debug app.js"
  },
  "main": "app.js",
  "repository": {
    "type": "git",
    "url": "git://github.com/sahan/myApp.git"
  },
  "author": "sahan",
  "license": ""
}
```


my Query made on VenueController

```javascript
indVenueWithUserInput: function(req, res) {
        var userinput = _.escape(req.param('query'))
            toLookFor = '%'+userinput;
        Venue.find({ where: { name: userinput }, limit: 20 }).exec( function(err, results) {
                if (err) {
                    return res.badRequest(err);
                }
                if (results.length) {
                    return res.ok(results);
                } else {
                    return res.notFound('No results found');
                }
            });
    },
```
My venue.js Model
```javascript
module.exports = {

    attributes: {
        about: {
            type: 'text'
        },
        name: {
            type: 'string'
        }
    }
};
```

**Comment by sahanDissanayake** [comment]
Any thoughts @dmarcelino  please?

**Comment by sahanDissanayake** [comment]
So this is what Im going wit bro

```javascript
findVenueWithUserInput: function(req, res) {
        var userinput = _.escape(req.param('query')),
            query       = 'SELECT * FROM `venue` WHERE UPPER(`name`) LIKE UPPER(\'%'+userinput+'%\')';
        // http://stackoverflow.com/questions/16082575/sql-ignore-case-while-searching-for-a-string
        Venue.query(query, function(err, results) {
            if (err) {
                console.log(err);
                return res.badRequest(err);
            }
            sails.log.info(results.length)

            if (results) {
                return res.ok(results);
            } else {
                return res.notFound('No results found');
            }
        });
    }
```

**Comment by dmarcelino** [comment]
Regarding this part of your code:
```javascript
        var userinput = _.escape(req.param('query'))
            toLookFor = '%'+userinput;
        Venue.find({ where: { name: userinput }, limit: 20 }).exec( function(err, results) {
```

* You shouldn't need escaping the query as sails-mysql will do that for you, I believe;
* in `.find` you are not using `toLookFor` which seems that you forgot;
* If you want to use '%' / `LIKE` your criteria should use `like` such as `{ where: { name: { like: toLookFor } } }`, take a look at the [waterline docs](https://github.com/balderdashy/waterline-docs/blob/master/query-language.md#like).

If you are still having problems, put a `console.log(user input)` before `Venue.find()` and share it with us to see what is actually being supplied to waterline/sails-mysql.

**Comment by sahanDissanayake** [comment]
Yep, Still no luck with using the the Sails ORM. So I used exactly what you have mentioned on the previous comment,

So on the client I type 'jam' > My intention is to find James
But on my DB there are Jamis, James, Jami, Jamerson....

So when I type 'jam' on the client and when I do a console log before the Venue.find()

```javascript
console.log(userinput); // output > jam
Venue.find({ name: { 'like': toLookFor }}).exec( function(err, results) {
```

I do not know what the problem here is, But as I mentioned in a previous comment Raw sql query works perfectly, its just the orm that's struggling here

**Comment by dmarcelino** [comment]
If you are trying to find James you will need to change `toLookFor = '%'+userinput;` into `toLookFor = '%' + userinput + '%';`.

**Comment by sahanDissanayake** [comment]
Awesome,,, Now we are getting somewhere,, :+1: 

So now there are results being served, 
But still I have to capitalise the word, because the search in SailsJS is case sensitive for some weird reason, :cry: 

Dont know why tho

**Comment by dmarcelino** [comment]
I'm still confused as to why you are experiencing this... sails-mysql passes the following [test](https://github.com/balderdashy/waterline-adapter-tests/blob/master/interfaces/queryable/caseInsensitive.test.js#L134):

```javascript
      it('like should work in a case insensitive fashion by default', function(done) {
        Queryable.User.find({ first_name: { like: '%hete%'}, type: 'case sensitivity' }, function(err, users) {
          assert(users.length === 3);
          assert(users[0].id);
          assert(users[0].first_name === 'tHeTest');
          done();
        });
```

@sahanDissanayake, can you try the github version of sails-mysql (`npm i balderdashy/sails-mysql`)?

@devinivy, any ideas?

**Comment by sahanDissanayake** [comment]
So this is what i did,

Went in to my app folder and typed npm i balderdashy/sails-mysql
And then restarted the server

Still does not work.

Could you kindly tell me how to undo "npm i balderdashy/sails-mysql" command ?

**Comment by dmarcelino** [comment]
`npm i sails-mysql@latest` will do it.

**Comment by sahanDissanayake** [comment]
Thanks Dário, Hope we will be able to find a solution for this, 
Just as a not : my DB type is utf8_bin

**Comment by dmarcelino** [comment]
Ah, can you try not setting collation just for the sake of testing? Judging from http://stackoverflow.com/a/5890422/4249576 that may be the cause since strings will be compared by their binary value.
> With utf8_general_ci, matches occur without taking case and accentuation into account. It may be a good thing when you need to perform queries on words.
> 
> In utf8_bin, the match only occurs when strings are strictly the same. Queries are faster this way.

**Comment by sahanDissanayake** [comment]
Yeah bro,,, Hells yeah,, :fireworks: 
That did the trick..

I changed the collation to utf8_general_ci
Restarted the server

And now the case insensitive search work perfectly :)

**Comment by dmarcelino** [comment]
Cool, good to hear that! :smiley:

**Comment by sahanDissanayake** [comment]
thanks for all your effort, really appreciate it

**Comment by devinivy** [comment]
@dmarcelino Good find.  Do we need to make a point about collations in sails-mysql?

**Comment by dmarcelino** [comment]
It's probably a good idea, yes.
