### ISSUE TITLE
How to render selected fields ?

### ISSUE THREAD

**Issue by keniosor** [balderdashy/waterline#963]
Hi,

I use the Waterline ORM for my Sails Js applications.
For queries, I would like to render selected fields.

In the documentation, there is an example using the find() method :
User.find()
.where({ id: { '>': 100 }})
.where({ age: 21 })
.limit(100)
.sort('name')
.exec(function(err, users) {
// Do stuff here
});

But, it renders all the fields of the User model.
How to render selected fields ?. for example how to render only the name field ?.

Thanks﻿

**Comment by dmarcelino** [comment]
Hi @keniosor,

You can use `select` like this:
``` javascript
User({ select: ['name'] })
```

More details on http://stackoverflow.com/a/29769995/4249576
