### ISSUE TITLE
GeoSpatial indexes support (feature request)

### ISSUE THREAD

**Issue by elennaro** [balderdashy/waterline#970]
PostgreSQL, MySQL and MongoDB, all support geo spatial indexes.
Do you plan to support them?

**Comment by dmarcelino** [comment]
For reference, this relates to balderdashy/sails-postgresql#4, balderdashy/sails-mongo#46 and #71.

I can also see that `anchor` has support for `geojson` in [rules.js](https://github.com/balderdashy/anchor/blob/master/lib/match/rules.js#L49) which could be used for this.

At this point I'm not sure if there is anything required of waterline core or if it's a matter of adapter implementation. @elennaro, are you aware of what's needed to implement this?

**Comment by elennaro** [comment]
I'm not sure, didn't review the Waterline's sources thoroughly.
1. I hope there could be a "geojson" Model attribute type, say in [GeoJSON](http://geojson.org/) form, and I see it in `anchor`.
2. Then there could be
* generation of proper indexes in database adapters
* mapping
* query for geospatial search with realizations in each adapter like [geoNear](http://docs.mongodb.org/manual/reference/command/geoNear/) etc.
I know the MongoDB way and could help with realization in sails-mongo.

Does Waterline support all the types from [anchor](https://github.com/balderdashy/anchor)?

**Comment by dmarcelino** [comment]
Waterline uses `anchor` for validation so whatever types are there should passthrough to the adapter.

**Comment by elennaro** [comment]
And then it will cal the adapter to create index and to do the mapping will it?

**Comment by dmarcelino** [comment]
Disclaimer: I've never used geospatial indexes so I'm not familiar with geospatial indexes and mapping.

Assuming you had something like:
``` javascipt
attributes: {
  location: {
    type: "geojson",
    index: true
  }
}
```

The adapter would get all this info and it should act on it creating an appropriate index.

**Comment by elennaro** [comment]
I see it now, thanks.

**Comment by dmarcelino** [comment]
Closing this as I don't think there is anything to be done on waterline core. Furthermore PR #981 will make it even easier for adapters to extend and validate data types. Please reopen if you find anything that needs change in waterline core.

**Comment by PascalAnimateur** [comment]
See [here](https://gist.github.com/PascalAnimateur/b73617f0a27475fd4ccb) for an example of geospatial indexing in Sails.js using native MongoDB queries.
