### ISSUE TITLE
Deferred object from Raw Query.

### ISSUE THREAD

**Issue by stefan1968** [balderdashy/waterline#974]
I need to populate associations from a raw query:- model.query(sql, cb).populate('pets'), or alternatively have a none deferred method of populating associations.

i.e record.populate('pets) - record is just a returned model schema not a defered object.

Is this possible?

**Comment by dmarcelino** [comment]
Hi @stefan1968, this is impossible. raw queries are adapter/db specific and they can return anything, from records, to counts, to admin operation results, etc. without any control from waterline core. The returned result format itself will vary between adapters. If you are doing raw query why not do your JOIN (that's essentially what populate does) operation in the query itself? You will like get more performance from it.

Regarding `record.populate('pets')` there is an open issue for that: #572 - Add "Populate" instance method to Waterline. Please note that in this case `record` would need to be an instance of model, in other words something returned by `.find()`, `.update()` or `.create()`.

**Comment by stefan1968** [comment]
Thanks for the response. The raw query explanation makes perfect sense. What is the timeline on record.populate ?

**Comment by dmarcelino** [comment]
You're welcome! I'm not aware of anyone currently working on it and it's not assigned to any version to be released soon. It's labelled as "Help Wanted" so any help is welcome, mind giving it a shot? :smiley:

**Comment by stefan1968** [comment]
Haha. If only I had time, I've just basically ported our companies server from LocmotiveJS/Sequelize to SailsJS/Waterline, and whilst Waterline is not as mature yet, the way it does stuff is far easier to handle.

Having said that, find with selected attribute returns is a must. I believe thats on its way?

**Comment by tjwebb** [comment]
> Having said that, find with selected attribute returns is a must. I believe thats on its way?

It's here. See https://github.com/balderdashy/waterline-docs/blob/master/query-language.md#select
