### ISSUE TITLE
Make .exec() return promise when no callback is provided. (To be used with generators/node-fibers async workflow)

### ISSUE THREAD

**Issue by Zaggen** [balderdashy/waterline#983]
When using promises in waterline models is necessary to call **then** to execute the query, which is perfect, but if one is using synchronous-like workflow by using generators or a library like [asyncawait](https://github.com/yortus/asyncawait) or [co](https://github.com/tj/co) or even [ES7 async/await](https://github.com/lukehoban/ecmascript-asyncawait) in the future, calling **.then** sounds confusing when reading it. So i'm proposing a little syntactic sugar to use in these cases.
Making **exec** to return a promise when called with no callback argument, or an alias like **defer** or **execAsync**  to the **then** method.

Here is the current workflow using **ES7 async/await** (Just for simplicity):
Note: When using a library like **yortus asyncawait**, those keywords are actually **functions** and when using using **generators**, the **yield** keyword is used instead of await.

```javascript
// Some requires
var User = Waterline.Collection.extend({/* ... */}});
async function() {
    try {
      var data = await User.find().then();
      console.log('results', data);
    } catch (error) {
      // Handle error
    }
}
```
Proposed sugar method worflow
```javascript
// Some requires
var User = Waterline.Collection.extend({/* ... */});
async function() {
    try {
      var data = await User.find().exec();
      console.log('results', data);
    } catch (error) {
      // Handle error
    }
}
```
I think this feature makes makes the code more readable when using this kind of workflow, which is something we all probably will be using in the near future, if not already....

Pst: This is my first time proposing a feature here, if i made a mistake, please let me know :)

**Comment by dmarcelino** [comment]
Hi @Zaggen, this looks interesting. Tell me, is returning a promise for `.exec()` a best practice or a common thing in a *synchronous-like workflow*? I mean would people using such workflow expect for `.exec()` to return a promise?

I would say this shouldn't be too difficult, the changes should be done in [deferred.js](https://github.com/balderdashy/waterline/blob/master/lib/waterline/query/deferred.js#L486) but I'd like to understand if this is where the community is going towards.

**Comment by Zaggen** [comment]
Hi @dmarcelino,  indeed for this to work a promise is needed,  it will only work with one.

**Comment by dmarcelino** [comment]
Hey @Zaggen, my question was more in the sense to figure out what people are already using outside waterline/sails. Is there any convention for what that keyword should be?

To me it looks like the solution would be for the CRUD methods to return the promise, such as:
```javascript
var data = await User.find();
```

**Comment by Zaggen** [comment]
@dmarcelino Not quite sure, i don't think there is already a convention for dealing with this workflows and any ORM in js, but i think we should follow the sync conventions used by others frameworks/ORM in any language, like Active Record on Rails, so just as you proposed, that should be the cleanest way to do it, i just thought it could be complex that way, but if it is doable with out breaking much, what you proposed should be the best pattern.

**Comment by devinivy** [comment]
If the deferred class inherited from Promise, would that work for us?
https://github.com/balderdashy/waterline/blob/master/lib/waterline/query/deferred.js

I'd rather `.exec` not return a promise, since it seems it's _specifically_ for callbacks.  Also, even though waterline doesn't allow this right now, `User.create({}).exec()` could definitely appear to be a no-op on create.

**Comment by dmarcelino** [comment]
> If the deferred class inherited from Promise, would that work for us?

I believe so, yes.

**Comment by Zaggen** [comment]
@dmarcelino Does waterline optimize the query to be executed when exec() is called? I mean, if i call user.find().limit(5), those 2 chained methods result in a single query right?, if that the case, then there is no way (at least to me) to know which chainable method is supposed to be the last one and call exec internally to return a promise, so i  was thinking, that maybe we could make all of those query methods (find,limit,etc) to return a promise-like obj, that we can chain methods to it, with out using then (so we have the same interface that you proposed), and we can make a call to setInmediate() to call .exec().then() on that promise-like obj, and trigger the db call. Does this makes sense?, i'm not quite sure on how to implement that promise-like obj/state machine, but if you guys think this is a good idea, i might get hands into it and make a PR, i haven't read any of the waterline internals so it might take a while, but i'm guessing i'm the only one needing this right now, but i hope everybody starts using this feature soon.

Let me know what you think, if there is an easier or better approach to this, or else.

**Comment by dmarcelino** [comment]
> if i call user.find().limit(5), those 2 chained methods result in a single query right?

Precisely.

> then there is no way (at least to me) to know which chainable method is supposed to be the last one

Not sure about this part either...

> maybe we could make all of those query methods (find,limit,etc) to return a promise-like obj, that we can chain methods to it

I'm not sure how *promise-like* [deferred.js](https://github.com/balderdashy/waterline/blob/master/lib/waterline/query/deferred.js) is but it's already being returned by those chain methods.

**Comment by Zaggen** [comment]
> I'm not sure how promise-like deferred.js is but it's already being returned by those chain methods.
In that case it might be easier, i'll check into it.

**Comment by Zaggen** [comment]
@dmarcelino @devinivy I finally took the time to read deferred.js, and after reading it i realized that it already has what we need, since like dario said, is a promise-like fn, it has a `then` method that promisifies `exec` and calls it to return a real promise, and that `.then` method on the defered is all that it needs to work. I should have test it before waiting to have time to read the file though, but at least is good news, the functionality is already there, it might be a good idea to add some info to the docs regarding this.

Note: I've test it with yortus asyncawait and co + generators and works as expected.

```coffeescript
# Using coffeescript for simplicity

# co + generators
co ->
    data = yield Service.find()

# asyncawait
do async ->
    data = await Service.find()
```

**Comment by dmarcelino** [comment]
Good to know it works, thanks for letting us know!

**Comment by Zaggen** [comment]
@dmarcelino You welcome. It seems waterline is even better that i thought :)

**Comment by clonn** [comment]
but when we use `exec` method, it is not return promise object, it is still a callback method.

```
let user = await User.find({username: "test"}).populate("userRole").exec()
```

that will return error back.

**Comment by devinivy** [comment]
@clonn sorry, that's not supported.  `exec()` is specifically for use with callbacks.

**Comment by Zaggen** [comment]
@clonn When i initially suggested this feature, i assumed generators/fibers needed a real promise, that is why i was using it like this: `await User.find().then()` , i did thought that it would be ideal to just remove the `.then` and it'll get clearer, just as any synchronous api (like in rails) , just as @dmarcelino suggested,  but i just didn't tried that option. 

So after reading the deferred 'class' i realized there was no need to do such change as returning a promise when .exec() is called with no callback (which was clearer empty and lone .then but not as clear as with nothing after the query op) , `.exec()` as @devinivy pointed out, is designed for callbacks and should remain in that way. 

The thing is, generators/fibers don't care if is not a full implementation of a promise, as long as is a thenable (an object that has a then method) and that thenable in turn returns a real promise, this is because they are pretty much iterators (with push-pull capabilities), so in this case waterline returns a deferred, which has the `.exec` and `.then` methods, among others, and that `then` method returns a promise, so our generator iterates on the first `.then` and then the second one.

So just don't add `.exec` or `.then` at the end, it works as it is right now and is way better than what i suggested.

Like this:
```let user = await User.find({username: "test"}).populate("userRole")```   

Pst: There are more options to use with generators than just promises like thunks, arrays (for parallel execution), generators, etc.

**Comment by devinivy** [comment]
Thanks for compiling this info!

**Comment by Zaggen** [comment]
@devinivy You welcome, i hope it helps those interested in using waterline with generators/fibers  :)

**Comment by clonn** [comment]
@Zaggen  thanks for your explain, i discover that, when we use sails.js `0.11.2`, it used "waterline": "~0.10.17", that is not fully support promise yet.

if need use `await`, have to install newer than `"waterline": "^0.10.28"`, it works well.

thanks
