### ISSUE TITLE
Is there a way to ignore attributes during persistence?

### ISSUE THREAD

**Issue by LouisBarranqueiro** [balderdashy/waterline#990]
Is there a way to ignore attributes during persistence? I didn't find anything about that. I would be useful. For example by setting a ```persisted``` attribute to ```false```.

```javascript
attributes: {
    password: {
        type: 'string',
        required: true,
        columnName: 'password',
        regex: /.{8,}/,
        confirmPassword: true
    },
    passwordConfirmation: { // this attribute will not be persisted
         type: 'string',
         persisted: false
    }
}
```

**Comment by devinivy** [comment]
Do you know of any other ORMs that have a similar feature?  My first inclination is to say, if it's not persisted as an association or in a column, it doesn't belong as an ORM attribute.  Perhaps password confirmation should be taken care of in lifecycle callbacks or (better yet) in the controller that passwords are posted to.

**Comment by LouisBarranqueiro** [comment]
Yes for example, with EJB in Java, an entity class can have transient attributes then any attribute can be ignored with ```@transient``` annotation. Password confirmation is just an example, but there is maybe an other question behind : how to validate attribute with other transient attributes (not persisted) with custom type feature?

**Comment by devinivy** [comment]
Perhaps you could delete the attribute in the `afterValidate` lifecycle callback.

**Comment by LouisBarranqueiro** [comment]
Yes, but the goal is to do not persist this attribut, I don't want (for example) a column "password_confirmation" empty in my database. It doesn't make sense to save a value and delete it 1 second later.

**Comment by particlebanana** [comment]
In Waterline an attribute is meant to represent a column in a db. If it's not being saved we don't need it in the model.

For this use case comparing passwords is something we would do at the controller level before initiating the create call.

**Comment by LouisBarranqueiro** [comment]
Ok. I find that it not so good to split this kind of job. It's also harder to use custom validation messages by doing this way. In my opinion, the validation process have to be done by only one layer, Model layer in this case.

**Comment by dmarcelino** [comment]
@LouisBarranqueiro, have you tried using `beforeValidate()` [lifecycle callback](https://github.com/balderdashy/waterline-docs/blob/master/models.md#lifecycle-callbacks) to check the `passwordConfirmation` field? That way you don't have to add it to your model definition, you can also delete it there if you are working with a schemaless data-store. That's how I'm solving that problem in a project I'm working on.

**Comment by dmarcelino** [comment]
Actually what I'm doing is slightly different but the same principle holds:
``` javascript
  // Lifecycle Callbacks
  beforeValidate : function(values, next) {
    // encrypt password
    if (values.password) {
      values.salt = makeSalt();
      values.hashedPassword = encryptPassword(values.password, values.salt);
      delete values.password;
    }
    next();
  },
```

**Comment by LouisBarranqueiro** [comment]
I will try this. It seems to be a cleaner alternative. But i still find that a ```transient``` attribute would be useful and lighter and easier than utilisation of lifecycle callbacks. Thank you @dmarcelino .

**Comment by dmarcelino** [comment]
I can be wrong but in my personal opinion/experience using waterline there is little use for a `transient` parameter because it will only serve to delete variables before they are saved to the data-store. The tradeoff being polluting the model definition. Most times you send such extra information is to perform something with it, like a validation, and that can (and should) be handled in the lifecycle callbacks.

The reason why this is probably useful in Java is because at a given layer you'll need getters/setters for a given attribute. Perhaps a more complete alternative to that, and to `transient`, is the concept of "virtual attributes" being discussed in #201. Let us know what you think of that.

**Comment by dmarcelino** [comment]
Closing this for now as it seems to be answered. Please reopen if you have further queries related to this topic or want to further discuss it. Thanks.
