### ISSUE TITLE
Validation occurring several times on an entity with two collections

### ISSUE THREAD

**Issue by kvindasAB** [balderdashy/waterline#992]
Hello,

Im using Waterline with mongo, and sails of course.

The issue that Im having is that I have an entity (post) that contains 2 collections of another entity (user).

I override the beforeValidate method to include additional validations, and Im experiencing 2 issues.

The first is that the validation is executing several times on a record update.
The second issue is that on a record with no users in any of the collections, its trying to save in the relationship tables with null users, and of course I get an error as 
"err: [Error: Associated Record For user with id = null No Longer Exists] } ]"

But the entity has no records associated at all, so Im wondering why it is deducting I have records where none is found.

I have tried specifying the attributes as null, but so far the same behavior.

**Comment by devinivy** [comment]
This reminds me of some old behavior– particularly the error you mentioned.  What version of waterline are you using?

**Comment by kvindasAB** [comment]
Hello,

Im using "version": "0.10.16",

**Comment by dmarcelino** [comment]
The `beforeValidate` issue reminds me: #751.

@kvindasAB, that's an old version, can you try the latest (v0.10.21 if I'm not mistaken)?

**Comment by kvindasAB** [comment]
Just wondering, would that be compatible with sails 0.10.5?

**Comment by dmarcelino** [comment]
Should be as backwards compatibility has been kept throughout the patches.

**Comment by kvindasAB** [comment]
Great, thanks a lot, will try that.

**Comment by dmarcelino** [comment]
@kvindasAB, is it working now? Can we close this? Thanks

**Comment by kvindasAB** [comment]
Hello, truth is that I do not know if im missing something, because it did not worked.
I upgraded to version sails 0.11.0 which uses waterline 0.10.21 but the result was pretty much the same.

I ignore if Im messing with something on my model configuration that may be causing the issue.

**Comment by dmarcelino** [comment]
Can you share your model definitions and code snippet of where the issue happens?

**Comment by kvindasAB** [comment]
Hello Dario, here I attach a brief summary of my models.

----

USER Model

var User = {
  // Enforce model schema in the case of schemaless databases
  schema: true,

  attributes: {
    username  : { type: 'string', unique: true },
    email     : { type: 'email',  unique: true },
    passports : { collection: 'Passport', via: 'user' }
  }
};

module.exports = User;

----

POST Model

module.exports = {

  attributes: {
    author        : { model: "User", required: true },
    title         : { type: "string" },
    likeCount     : { type: "number", defaultsTo: 0 },
    shareDirectUsers: { collection: "User", dominant: true },
    shareTaggedUsers: { collection: "User", dominant: true },
  },

  // Lifecycle Callbacks
  beforeValidate: function (values, next) {
    console.log("************************");
    console.log("beforeValidate. STARTING");
    async.series({
        user: function(cb){
          if(!values.author){
            return cb(null);
          }
          User.findOne()
            .where(
              {
                or: [
                  {id: values.author},
                  {username: values.author}
                ]
              })
            .then(function(user){
              if(!user){
                return cb("User not found:" + values.author);
              }
              cb(null, user);
            })
            .catch(function(err){
              cb(err);
            });
        }
      },
      function(err, result){
        if(err){
          return next("Error saving post: " + err);
        }
        // other stuff here
        next();
      });
  }
}

**Comment by dmarcelino** [comment]
@kvindasAB, in your `Post` model you have:
```js
    shareDirectUsers: { collection: "User", dominant: true },
    shareTaggedUsers: { collection: "User", dominant: true },
```

But you don't have any corresponding `model`/`collection` attributes on the `User` model pointing at `Post`. You are also missing the `via` keywords. Please check the associations docs, if you want a [one-to-many associations](https://github.com/balderdashy/waterline-docs/blob/master/associations.md#one-to-many-associations):
> A one-to-many association states that a model can be associated with many other models. To build this association a virtual attribute is added to a model using the collection property. In a one-to-many association **one side must have a collection attribute and the other side must contain a model attribute**. This allows the many side to know which records it needs to get when a populate is used.
> 
> Because you may want a model to have multiple one-to-many associations on another model **a via key is needed on the collection attribute**. This states which model attribute on the one side of the association is used to populate the records.

In case you are trying to set [many-to-many associations](https://github.com/balderdashy/waterline-docs/blob/master/associations.md#many-to-many-associations):
> Waterline will look at your models and if it finds that **two models both have collection attributes that point to each other**, 
> (...)
> Because you may want a model to have multiple many-to-many associations on another model **a via key is needed on the collection attribute**. This states which model attribute on the one side of the association is used to populate the records.

**Comment by kvindasAB** [comment]
Hello Dario, understood.

Probably I misunderstood the one-way associations.

It will be good to clarify then in the one-way associations documentation that it only works for simple models (not collections) or I ignore if it works for scenarios where the there is a single collection pointing to the other model.

In any case, I will modify the models to have the via and being two-way and let you know how it goes.

Thanks a lot for the help and support.

**Comment by dmarcelino** [comment]
@kvindasAB, by "one-way" do you mean *one-to-one*? In that case the only possible keyword is `model`. If you look at the [one-to-one associations docs](https://github.com/balderdashy/waterline-docs/blob/master/associations.md#one-to-one-associations) the keyword `collection` is never used or mentioned. The reason for that is that collection means multiple models and in a one-to-one there is only one model pointing at another one. Hope that makes it clearer.

**Comment by kvindasAB** [comment]
Hello Dario, I do not, I refer to one-way associations, where only one end of the association contains the configuration.
http://sailsjs.org/#!/documentation/concepts/ORM/Associations/OneWayAssociation.html

**Comment by dmarcelino** [comment]
Those are the same as [one-to-one associations](https://github.com/balderdashy/waterline-docs/blob/master/associations.md#one-to-one-associations) :grinning: We should make the terminology consistent between sails and waterline :blush: 

It seems to me you'll want to use [one-to-many associations](https://github.com/balderdashy/waterline-docs/blob/master/associations.md#one-to-many-associations).

**Comment by kvindasAB** [comment]
ohh I see, my mistake then. :disappointed: 
I have used other ORM and understood the concept of one-way association as if you just configure it on one end.
In any case, thanks for the clarification.

**Comment by randallmeeker** [comment]
> Those are the same as one-to-one associations 

Not necessarily. 

A one-way association is the same as a one-to-one association in the same way that a one-way association is also the same as a one-many. In both cases your dropping one end of the association. A one-way association is valid and is missing from Waterline Docs.

**Comment by dmarcelino** [comment]
@randallmeeker, the first example of  [one-to-one associations](https://github.com/balderdashy/waterline-docs/blob/master/associations.md#one-to-one-associations) in waterline docs is actually a "one-way". The second example is a one-to-one association that has to be manually kept. So I don't think a "one-way" is missing but the terminology is not clear in waterline docs.

**Comment by randallmeeker** [comment]
@dmarcelino you are correct.

**Comment by kvindasAB** [comment]
Hello @dmarcelino 
I have some additional insights on this issue.

I changed the associations to be two-sided, on both post and user entities as recommended.
After this correction the row now saves successfully.
But the execution of 3 times of the validation continues to occur.

I thought it was related to an async call I had in beforeValidate, but still no luck, I remove the async code and I still see the validation being called 3 times.
At the moment it is not affecting me as the row is saving properly, but probably is something that should be looked at.

Again thanks a lot for the help.

**Comment by dmarcelino** [comment]
> The `beforeValidate` issue reminds me: #751.

That's a known issue @kvindasAB, it's best to continue that discussion in #751 to keep things in one place.

You're welcome! :wink:

**Comment by kvindasAB** [comment]
Hello @dmarcelino understood.
Will close this issue then.
Again all the help is deeply appreciated.
