### ISSUE TITLE
broken buffer for binary data in alter migration

### ISSUE THREAD

**Issue by atiertant** [balderdashy/waterline#996]
adapter receive a broken buffer in createEach function for binary data while migrating in alter mode, in https://github.com/balderdashy/waterline/blob/master/lib/waterline/adapter/sync/strategies/alter.js 
line 99 : 

    backupData = _.cloneDeep(existingData);

the original data is clone with lodash' cloneDeep,this is working for many value but not for buffer : 
https://github.com/lodash/lodash/issues/311

this line should be change by : 

    backupData = _.cloneDeep(existingData, function dealWithBuffers(val) {
      if (val instanceof Buffer) {
        return val.slice();
      }
    });

**Comment by devinivy** [comment]
Sounds like the right idea to me.  Feel free to submit a PR!

**Comment by atiertant** [comment]
@devinivy in which file/folder of test do you think this kind of tests should be ?

**Comment by devinivy** [comment]
Good question!  There are adapter integration tests for that here: https://github.com/balderdashy/waterline-adapter-tests/tree/1d190d5c664f803bbe02fc160955d518c019f21e/interfaces/migratable

**Comment by dmarcelino** [comment]
Yeah, migratable sounds like a good place for it.

**Comment by atiertant** [comment]
@devinivy, @dmarcelino  why adding this test in waterline-adapter-tests ? 
this is a waterline bug there is nothing that adapters developers can do... 
waterline test shouldn't unsure that passed value to adapters are correct ?

**Comment by devinivy** [comment]
You can create a unit test for this too.  Here are the unit tests: https://github.com/balderdashy/waterline/tree/master/test/unit

They generally mirror the directory structure of the waterline project itself, so you'll have to create the `adapter` folder in there to place the unit test.

**Comment by atiertant** [comment]
@devinivy what do you think of it ?

**Comment by dmarcelino** [comment]
Fixed via #1005. Thanks @atiertant and @khalilTN!
