### ISSUE TITLE
Date tranforme problem

### ISSUE THREAD

**Issue by fundon** [balderdashy/waterline#998]
I use PostgreSQL Database and set the `created_at` `updated_at` fields to `timestamp without time zone`(UTC by default).

My questions:

0. How to get raw row data?

0. How to disable `new Date(created_at)` or use `new Date(created_at + '+00:00')` ?

**Comment by dmarcelino** [comment]
Hi @fundon,

1. "raw" as in the actual date values in the DB? You would need to use the [.query()](https://github.com/balderdashy/waterline-docs/blob/67545664138e7362640756dd97205142cc72cac9/query-methods.md#query-query-data-callback-) method.
2. I don't believe that is possible, but you can [disable `createdAt` and `updatedAt`](https://github.com/balderdashy/waterline-docs/blob/32e3e8bed3915a043b89c42cc9f97c6a97fdf7d8/models.md#autocreatedat) and then you can create your own date attributes managed by yourself.

There is an ongoing discussion about how waterline handles dates in balderdashy/sails-postgresql#153 which can clarify how dates are handles by waterline and its adapters. There are also some proposals about how to improve it.

**Comment by fundon** [comment]
@dmarcelino Thanks

> I don't believe that is possible, but you can disable createdAt and updatedAt and then you can create your own date attributes managed by yourself.

Will get ` 2015-05-10 09:33:11.037000` when using `timestamp without time zone` type, so `new Date(' 2015-05-10 09:33:11.037000')` is wrong. That will be parsed by local time zone.

The right is `new Date('2015-05-10 09:33:11.037000+00:00')`.

**Comment by dmarcelino** [comment]
I think you're experiencing the issue described in balderdashy/sails-postgresql#153, namely https://github.com/balderdashy/sails-postgresql/issues/153#issuecomment-94753436:
> Currently, we insert as UTC for postgres and fetch as local timezone for all. MySQL also inserts for local timezone. This causes bugs.

Please take a look, it may be worth to continue the discussion there instead.

**Comment by dmarcelino** [comment]
Closing this as inactive / duplicate of balderdashy/sails-postgresql#153. Feel fee to re-open at any time if you think otherwise or if you want to resume this discussion.
