### ISSUE TITLE
Add pluralize for table name

### ISSUE THREAD

**Issue by listepo** [balderdashy/waterline#999]
I think pluralize for table name is good feature

**Comment by dmarcelino** [comment]
Hi @listepo, can you please expand on your suggestion?

**Comment by listepo** [comment]
That table is called ```transactions``` need to write in the model ```Transaction.js``` 
```
...
tableName: transactions
...
```
But this is not practical.

**Comment by dmarcelino** [comment]
That would be a sails.js feature, Waterline by itself does not use the model's filename to infer the tableName.

**Comment by listepo** [comment]
I understand, what you think about this functionality? I would he helpful

**Comment by dmarcelino** [comment]
Currently I'm not using sails.js so I'm not the best person to answer that... :blush: But I agree it can be helpful for some people in certain contexts. Maybe it should exist in a configurable way so people can turn it on/off? Try raising it in the sails project and see what people say there.

**Comment by listepo** [comment]
@dmarcelino, thanks
